import React from 'react';

const configs = {
  'marriage-bureau': { title: 'Marriage Bureau Details', fields: [['yearsExperience', 'Years of Experience'], ['serviceArea', 'Service Area']], checks: ['Matrimonial Registration', 'Profile Matching', 'Horoscope Matching', 'Family Consultation', 'Personalized Matchmaking', 'Online Matrimony', 'Offline Matrimony', 'NRI Matrimony', 'Community Matrimony', 'Second Marriage', 'Wedding Assistance'], extras: ['Membership Available', 'Enable Success Stories'] },
  'function-hall': { title: 'Function Hall Details', fields: [['venueType', 'Venue Type'], ['minCapacity', 'Minimum Capacity'], ['maxCapacity', 'Maximum Capacity'], ['cateringAvailable', 'Catering Available'], ['externalCatering', 'External Catering Allowed'], ['decorationAvailable', 'Decoration Available'], ['bookingRequired', 'Advance Booking Required'], ['startingPrice', 'Starting Price'], ['hallRentalPrice', 'Hall Rental Price'], ['packagePrice', 'Package Price']], checks: ['Air Conditioning', 'Parking', 'Generator', 'Power Backup', 'Stage', 'Bridal Room', 'Groom Room', 'Dining Hall', 'Kitchen', 'Sound System', 'Lighting', 'Decoration', 'Wi-Fi', 'Lift', 'Security', 'CCTV'], lists: [['halls', 'Halls / Venues']] },
  'event-organizer': { title: 'Event Organizer Details', fields: [['yearsExperience', 'Years of Experience'], ['eventsCompleted', 'Events Completed']], checks: ['Weddings', 'Engagements', 'Receptions', 'Birthdays', 'Anniversaries', 'Corporate Events', 'Baby Showers', 'Naming Ceremonies', 'Religious Events', 'Private Events', 'Event Planning', 'Wedding Planning', 'Venue Management', 'Decoration', 'Catering Coordination', 'Photography Coordination', 'Entertainment', 'Guest Management', 'Invitation Management', 'Vendor Management', 'Transportation', 'Stage Design'], lists: [['packages', 'Packages'], ['portfolio', 'Portfolio']] },
  'catering-service': { title: 'Catering Service Details', fields: [['yearsExperience', 'Years of Experience'], ['serviceArea', 'Service Area']], checks: ['South Indian', 'North Indian', 'Andhra', 'Telangana', 'Tamil', 'Kerala', 'Chinese', 'Continental', 'Traditional', 'Desserts', 'Snacks', 'Vegetarian', 'Non-Vegetarian', 'Jain', 'Vegan', 'Breakfast', 'Lunch', 'Dinner', 'Buffet', 'Full Meals', 'Corporate Catering', 'Wedding Catering', 'Function Catering', 'Outdoor Catering', 'Live Counters', 'Waiter Service', 'Decoration Support'], lists: [['menuItems', 'Menu Items'], ['packages', 'Packages']] },
  'flower-decoration': { title: 'Flower Decoration Details', fields: [['yearsExperience', 'Years of Experience'], ['decorationStyle', 'Decoration Style']], checks: ['Wedding Decoration', 'Stage Decoration', 'Mandap Decoration', 'Reception Decoration', 'Entrance Decoration', 'Floral Backdrop', 'Table Decoration', 'Car Decoration', 'Bridal Room Decoration', 'Flower Arrangements', 'Roses', 'Jasmine', 'Marigold', 'Lotus', 'Orchids', 'Artificial Flowers', 'Mixed Flowers'], lists: [['packages', 'Packages']] },
  'fashion-designer': { title: 'Fashion Designer Details', fields: [['yearsExperience', 'Years of Experience'], ['specialization', 'Designer Specialization']], checks: ['Bridal Wear', 'Groom Wear', 'Sarees', 'Lehengas', 'Sherwanis', 'Suits', 'Reception Wear', 'Engagement Wear', 'Party Wear', 'Traditional Wear', 'Custom Design', 'Stitching', 'Alterations', 'Bridal Styling', 'Groom Styling', 'Custom Measurements', 'Rental Available'], lists: [['collections', 'Collections']] },
  'beauty-parlour': { title: 'Beauty Parlour Details', fields: [['yearsExperience', 'Years of Experience']], checks: ['Bridal Makeup', 'Party Makeup', 'Engagement Makeup', 'Hair Styling', 'Hair Cut', 'Hair Color', 'Facial', 'Cleanup', 'Waxing', 'Threading', 'Manicure', 'Pedicure', 'Mehendi', 'Pre-Bridal Services', 'Draping'], lists: [['packages', 'Packages']] },
  'saloon-spa': { title: 'Saloon & Spa Details', fields: [['yearsExperience', 'Years of Experience'], ['membershipDescription', 'Membership Description'], ['membershipPrice', 'Membership Price']], checks: ['Hair Cut', 'Hair Styling', 'Hair Color', 'Hair Spa', 'Beard Styling', 'Grooming', 'Facial', 'Cleanup', 'Waxing', 'Threading', 'Manicure', 'Pedicure', 'Body Massage', 'Head Massage', 'Aromatherapy', 'Relaxation Therapy', 'Spa Treatments', 'Bridal Package', 'Groom Package', 'Couple Package'] },
};

const inputClass = 'mt-1 w-full rounded-lg border border-[#ead9df] bg-white px-3 py-2.5 text-sm outline-none focus:border-[#941f43]';

function ChoiceList({ title, options, values = [], onChange }) {
  return <div><h3 className="text-sm font-semibold text-[#5a3742]">{title}</h3><div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{options.map((option) => <label key={option} className="flex items-center gap-2 rounded-lg border border-[#ead9df] bg-[#fff8fa] px-3 py-2 text-sm"><input type="checkbox" checked={values.includes(option)} onChange={() => onChange(values.includes(option) ? values.filter((value) => value !== option) : [...values, option])} />{option}</label>)}</div></div>;
}

function DetailList({ title, items = [], onChange }) {
  const update = (index, key, value) => onChange(items.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item));
  return <div><div className="flex items-center justify-between gap-3"><h3 className="font-display text-lg font-semibold text-[#4b1227]">{title}</h3><button type="button" onClick={() => onChange([...items, { name: '', category: '', description: '', price: '', image: '' }])} className="rounded-lg bg-[#941f43] px-3 py-2 text-sm font-semibold text-white">+ Add</button></div>{items.map((item, index) => <div key={`${title}-${index}`} className="mt-3 grid gap-3 rounded-lg border border-[#ead9df] bg-[#fff8fa] p-3 sm:grid-cols-2">{[['name', 'Name'], ['category', 'Category'], ['price', 'Price'], ['image', 'Image URL (optional)']].map(([key, label]) => <label key={key} className="text-sm text-[#5a3742]">{label}<input value={item[key] || ''} onChange={(event) => update(index, key, event.target.value)} className={inputClass} /></label>)}<label className="text-sm text-[#5a3742] sm:col-span-2">Description<textarea rows={2} value={item.description || ''} onChange={(event) => update(index, 'description', event.target.value)} className={inputClass} /></label><button type="button" onClick={() => onChange(items.filter((_, itemIndex) => itemIndex !== index))} className="text-left text-xs font-semibold text-red-700">Remove</button></div>)}</div>;
}

export default function WeddingBusinessSpecificFields({ businessType, values = {}, onChange }) {
  const config = configs[businessType] || configs['event-organizer'];
  const setField = (key, value) => onChange({ ...values, [key]: value });
  const selectedServices = values.services || values.selectedOptions || [];
  return <section className="rounded-xl border border-[#ead9df] bg-[#fff8fa] p-5 sm:p-7">
    <p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#941f43]">{config.title}</p>
    <div className="mt-4 grid gap-4 sm:grid-cols-2">{config.fields.map(([key, label]) => <label key={key} className="text-sm font-medium text-[#5a3742]">{label}<textarea rows={2} value={Array.isArray(values[key]) ? values[key].join('\n') : values[key] || ''} onChange={(event) => setField(key, event.target.value)} className={inputClass} /></label>)}</div>
    {config.extras && <div className="mt-5 flex flex-wrap gap-4">{config.extras.map((extra) => <label key={extra} className="flex items-center gap-2 text-sm text-[#5a3742]"><input type="checkbox" checked={Boolean(values[extra])} onChange={(event) => setField(extra, event.target.checked)} />{extra}</label>)}</div>}
    {config.checks && <div className="mt-6"><ChoiceList title="Services & Options" options={config.checks} values={selectedServices} onChange={(items) => onChange({ ...values, services: items, selectedOptions: items })} /></div>}
    {config.lists?.length > 0 && <div className="mt-6 space-y-6">{config.lists.map(([key, title]) => <DetailList key={key} title={title} items={values[key] || []} onChange={(items) => setField(key, items)} />)}</div>}
  </section>;
}
