import React, { useMemo, useState } from 'react';
import ReviewsSection from '../../../components/ReviewsSection';
import { getProfileData, ImageFrame } from '../../../components/public/PublicProfileShared';
import { getWhatsAppUrl } from '../../healthcare-medical/healthcareUtils';

const mattressCategories = [
  ['Mattresses', 'Memory Foam, Orthopedic, Spring', '▰'],
  ['Pillows', 'Memory Foam, Comfort Pillows', '▱'],
  ['Mattress Protectors', 'Waterproof & Dustproof', '♢'],
  ['Bed Linen', 'Bedsheets, Quilts & Blankets', '▤'],
  ['Adjustable Beds', 'Modern Sleep Solutions', '▰'],
  ['Kids Mattresses', 'Safe & Comfortable for Kids', '♧'],
  ['Sleep Accessories', 'Cushions, Toppers & More', '♧'],
];
const infrastructure = [
  ['▦', 'Spacious Showroom', 'Wide display area with all brands'],
  ['⌖', 'Parking Facility', 'Ample parking space for customers'],
  ['➜', 'Home Delivery', 'Safe and fast delivery to your doorstep'],
  ['♙', 'Expert Guidance', 'Professional advice to choose the right mattress'],
  ['▰', 'Trial Experience', 'Try and feel the comfort before you buy'],
  ['◉', 'After Sales Support', 'Dedicated customer support'],
];
const videoTitles = ['Mattress Buying Guide', 'Our Showroom Tour', 'Customer Reviews'];

const toList = (value) => {
  if (Array.isArray(value)) return value.filter(Boolean);
  if (typeof value === 'string') return value.split(/[\n,]/).map((item) => item.trim()).filter(Boolean);
  return value ? [value] : [];
};
const firstList = (...values) => values.map(toList).find((items) => items.length) || [];
const mediaUrl = (item) => typeof item === 'string' ? item : item?.image || item?.url || item?.src || '';
const externalUrl = (value) => value ? (/^https?:\/\//i.test(value) ? value : `https://${value}`) : '';
const normalize = (value) => String(value || '').trim().toLowerCase().replace(/[_-]+/g, ' ').replace(/\s+/g, ' ');
const addressOf = (place) => [place.address, place.location?.area?.name, place.location?.city?.name, place.location?.district?.name, place.location?.state?.name].filter(Boolean).join(', ');

function MattressVideoModal({ video, onClose }) {
  const url = video?.url || video?.src || '';
  let source = url;
  let embed = false;
  try {
    const parsed = new URL(url);
    const id = parsed.hostname.includes('youtu.be') ? parsed.pathname.slice(1).split('/')[0] : parsed.searchParams.get('v') || parsed.pathname.match(/\/(?:embed|shorts)\/([^/?]+)/)?.[1];
    if (id) { source = `https://www.youtube.com/embed/${id}?autoplay=1`; embed = true; }
    else if (parsed.hostname.includes('vimeo.com')) { const videoId = parsed.pathname.match(/\/(?:video\/)?(\d+)/)?.[1]; if (videoId) { source = `https://player.vimeo.com/video/${videoId}?autoplay=1`; embed = true; } }
    else if (parsed.hostname.includes('drive.google.com')) { const fileId = parsed.pathname.match(/\/file\/d\/([^/]+)/)?.[1]; if (fileId) { source = `https://drive.google.com/file/d/${fileId}/preview`; embed = true; } }
  } catch { /* Direct video URL. */ }
  if (!source) return null;
  return <div role="presentation" className="fixed inset-0 z-[70] grid place-items-center bg-[#071426]/90 p-4" onClick={onClose}><section role="dialog" aria-modal="true" aria-label={video.title || video.caption || 'Mattress video'} className="relative w-full max-w-4xl overflow-hidden rounded-md bg-black shadow-2xl" onClick={(event) => event.stopPropagation()}><button type="button" aria-label="Close video" onClick={onClose} className="absolute right-3 top-3 z-10 grid h-10 w-10 place-items-center rounded-full bg-black/70 text-xl text-white">×</button><div className="aspect-video">{embed ? <iframe src={source} title={video.title || 'Mattress video'} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen className="h-full w-full border-0" /> : <video src={source} controls autoPlay playsInline className="h-full w-full" />}</div><p className="px-4 py-3 text-sm font-semibold text-white">{video.title || video.caption || 'Mattress video'}</p></section></div>;
}

export default function MattressShopPublicPage({ place }) {
  const profile = getProfileData(place);
  const specific = place.attributes?.businessProfile?.categorySpecific || {};
  const common = place.attributes?.businessProfile?.common || {};
  const attributes = place.attributes || {};
  const [menuOpen, setMenuOpen] = useState(false);
  const [lightboxImage, setLightboxImage] = useState('');
  const [activeVideo, setActiveVideo] = useState(null);
  const [selectedProduct, setSelectedProduct] = useState(null);

  const gallery = useMemo(() => {
    const source = profile.gallery?.length ? profile.gallery : place.images || [];
    return source.map((image, index) => ({ src: mediaUrl(image), index })).filter((item) => item.src).slice(0, 10);
  }, [place.images, profile.gallery]);
  const categoryNames = firstList(specific.products, specific.productCategories, attributes.productCategories, attributes.products);
  const productItems = firstList(specific.productItems, specific.featuredProducts, attributes.productItems, attributes.featuredProducts).filter((item) => typeof item === 'object' && (item.name || item.title));
  const services = firstList(specific.services, specific.specialtyServices, place.services, profile.services);
  const videoSource = firstList(common.videos, profile.videos, place.videos, place.video, attributes.videos);
  const videos = videoSource.map((video) => typeof video === 'string' ? { url: video } : video).filter((video) => video?.url || video?.src);
  const offers = firstList(specific.offer, specific.offers, attributes.offer, attributes.offers);
  const features = firstList(place.facilities, specific.features, specific.infrastructure, attributes.facilities);

  const name = place.name || common.businessName || 'Mattress Showroom';
  const tagline = profile.tagline || place.tagline || '';
  const about = place.description || profile.about || `${name} is your destination for premium mattresses and sleep solutions, with quality choices for a more comfortable home.`;
  const phone = place.phone || common.phone || profile.phone || '';
  const callUrl = phone ? `tel:${String(phone).replace(/\s+/g, '')}` : '';
  const whatsappValue = place.socialLinks?.whatsapp || profile.socialMedia?.whatsapp || profile.whatsapp || phone;
  const whatsapp = getWhatsAppUrl(whatsappValue);
  const email = place.email || common.email || profile.email || '';
  const website = externalUrl(place.website || common.website || profile.website);
  const location = addressOf(place);
  const mapUrl = location ? `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(location)}` : '';
  const visitUrl = mapUrl || '#contact';
  const logo = profile.logo || place.logo || '';
  const hero = profile.coverImage || place.coverImage || gallery[0]?.src || '';
  const aboutImage = profile.aboutImage || specific.aboutImage || place.aboutImage || gallery[1]?.src || gallery[0]?.src || hero;
  const socials = profile.socialMedia || place.socialLinks || {};
  const hoursSource = firstList(profile.openingHours, place.workingHours);
  const hours = hoursSource.filter((hour) => hour?.day && (hour.open || hour.close || hour.closed));
  const stats = [
    [specific.happyCustomers || specific.customersServed, 'Happy Customers', '♟'],
    [specific.featuredBrands || specific.brandCount || specific.brands?.length, 'Top Brands', '▦'],
    [specific.yearsExperience || specific.yearsInBusiness, 'Years of Experience', '★'],
    [place.rating?.count ? `${Number(place.rating.average || 0).toFixed(1)} / 5` : specific.customerSatisfaction, 'Customer Satisfaction', '♥'],
  ].filter(([value]) => value);
  const savedServices = services.length ? services : mattressCategories.map(([category]) => category);
  const productList = productItems.length ? productItems : categoryNames.filter((item) => typeof item === 'object' && (item.name || item.title));

  return (
    <div className="min-h-screen bg-white text-[#152b45]">
      <header className="sticky top-0 z-40 border-b border-[#e6ebf1] bg-white/95 shadow-sm backdrop-blur"><div className="mx-auto flex min-h-[68px] max-w-[1500px] items-center justify-between gap-4 px-4 sm:px-7"><a href="#home" className="flex min-w-0 items-center gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center overflow-hidden rounded-md border border-[#dfe5ec] bg-white">{logo ? <ImageFrame src={logo} alt={`${name} logo`} /> : <span className="font-display text-lg font-bold text-[#17385f]">{name.slice(0, 1)}</span>}</div><span className="min-w-0"><span className="block truncate font-display text-sm font-extrabold text-[#17385f] sm:text-base">{name}</span><span className="block truncate text-[10px] text-[#6c7886]">{tagline || 'Better Sleep · Better Life'}</span></span></a><nav className="hidden items-center gap-6 text-xs font-semibold lg:flex">{[['Home','#home'],['About','#about'],['Services','#services'],['Gallery','#gallery'],['Contact','#contact']].map(([label,target],index)=><a key={target} href={target} className={`border-b-2 px-1 py-2 ${index===0?'rounded bg-[#c9092c] px-4 py-2 text-white':'border-transparent text-[#293a50] hover:border-[#c9092c] hover:text-[#17385f]'}`}>{label}</a>)}</nav><div className="hidden items-center gap-2 md:flex">{phone&&<a href={callUrl} className="inline-flex items-center gap-2 rounded-md px-3 py-2 text-xs font-bold text-[#183454]"><span className="text-[#c9092c]">☎</span>{phone}</a>}<a href={visitUrl} target={mapUrl?'_blank':undefined} rel="noreferrer" className="rounded-md bg-[#c9092c] px-4 py-2.5 text-xs font-bold text-white">Visit Our Showroom</a></div><button type="button" aria-label="Toggle navigation" aria-expanded={menuOpen} onClick={()=>setMenuOpen((open)=>!open)} className="rounded border border-[#dfe5ec] px-3 py-2 text-lg lg:hidden">☰</button></div>{menuOpen&&<nav className="border-t border-[#e6ebf1] bg-white px-4 py-2 lg:hidden">{[['Home','#home'],['About','#about'],['Services','#services'],['Gallery','#gallery'],['Contact','#contact']].map(([label,target])=><a key={target} href={target} onClick={()=>setMenuOpen(false)} className="block border-b border-[#eef1f4] py-3 text-sm font-semibold last:border-0">{label}</a>)}<div className="flex gap-2 py-3">{phone&&<a href={callUrl} className="flex-1 rounded bg-[#17385f] px-3 py-2.5 text-center text-xs font-bold text-white">Call Now</a>}<a href={visitUrl} target={mapUrl?'_blank':undefined} rel="noreferrer" className="flex-1 rounded bg-[#c9092c] px-3 py-2.5 text-center text-xs font-bold text-white">Visit Showroom</a></div></nav>}</header>

      <main>
        <section id="home" className="relative isolate overflow-hidden bg-[#102746] text-white">{hero&&<div className="absolute inset-0"><ImageFrame src={hero} alt={`${name} mattress showroom`} eager/><div className="absolute inset-0 bg-gradient-to-r from-[#102746]/95 via-[#102746]/78 to-[#102746]/10"/></div>}<div className="relative mx-auto grid min-h-[430px] max-w-[1500px] items-center gap-5 px-5 py-9 sm:min-h-[500px] sm:px-8 lg:grid-cols-[1fr_.36fr]"> <div className="max-w-[690px]"><div className="mb-4 h-1 w-12 bg-[#c9092c]"/><p className="text-[10px] font-extrabold uppercase tracking-[.23em] text-[#f5d978]">SLEEP COMFORT, THOUGHTFULLY CHOSEN</p><h1 className="mt-3 font-display text-4xl font-extrabold leading-[1.02] sm:text-5xl lg:text-[58px]">Premium Mattresses<br/>for a <span className="text-[#f2d34f]">Healthier Tomorrow</span></h1><p className="mt-4 text-sm font-medium text-white/90">Comfort <span className="px-2 text-[#f3d550]">|</span> Quality <span className="px-2 text-[#f3d550]">|</span> Better Sleep</p><div className="mt-5 flex flex-wrap gap-x-4 gap-y-2 text-[10px] font-semibold text-white/90">{[['▰','Wide Range'],['◇','Trusted Brands'],['➜','Free Delivery'],['⚙','Expert Support']].map(([icon,label])=><span key={label} className="inline-flex items-center gap-1.5"><span className="text-sm text-[#f3d550]">{icon}</span>{label}</span>)}</div><div className="mt-6 flex flex-wrap gap-3"><a href="#collections" className="rounded-md bg-[#d10d31] px-5 py-3 text-sm font-bold text-white">Explore Mattresses →</a><a href={visitUrl} target={mapUrl?'_blank':undefined} rel="noreferrer" className="rounded-md bg-white px-5 py-3 text-sm font-bold text-[#17385f]">⌖ Visit Our Showroom</a></div></div><aside className="hidden border-l-2 border-[#df2540] bg-[#102746]/85 px-4 py-4 lg:block"><h2 className="font-display text-2xl font-extrabold leading-tight">Good Sleep<br/><span className="text-[#f3d550]">Better Health</span><br/>Brighter Tomorrow</h2><p className="mt-4 text-xs leading-5 text-white/80">Discover the perfect mattress for your lifestyle</p></aside></div></section>

        <section id="about" className="mx-auto grid max-w-[1500px] items-center gap-6 px-4 py-7 sm:px-7 lg:grid-cols-[.95fr_1.05fr]"><div className="min-h-[230px] overflow-hidden rounded-md bg-[#edf1f5] shadow-sm sm:min-h-[300px]">{aboutImage&&<ImageFrame src={aboutImage} alt={`${name} mattress showroom`} />}</div><div><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[#c9092c]">ABOUT OUR SHOWROOM</p><h2 className="mt-2 font-display text-3xl font-extrabold text-[#17385f]">About Us <span className="text-sm text-[#c9092c]">━━</span></h2><p className="mt-3 text-sm leading-6 text-[#5e6c7b]">{about}</p><a href="#contact" className="mt-4 inline-flex rounded-md bg-[#c9092c] px-4 py-2.5 text-xs font-bold text-white">Read More</a><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{stats.map(([value,label,icon])=><div key={label} className="rounded-md border border-[#e6eaf0] bg-[#fff6f7] px-2 py-3 text-center"><span className="text-lg text-[#c9092c]">{icon}</span><p className="mt-1 text-sm font-extrabold text-[#17385f]">{value}</p><p className="text-[9px] leading-4 text-[#687585]">{label}</p></div>)}</div></div></section>

        <section id="services" className="bg-[#f7f8fa] px-4 py-7 sm:px-7"><div className="mx-auto max-w-[1500px]"><div className="flex items-end justify-between gap-3"><h2 className="font-display text-3xl font-extrabold text-[#17385f]">Our Services <span className="text-sm text-[#c9092c]">━━</span></h2><a href="#collections" className="text-xs font-bold text-[#c9092c]">View All Services →</a></div><div className="mt-4 grid grid-cols-2 gap-2.5 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-7">{mattressCategories.map(([title,detail,icon],index)=>{const saved=services.find((entry)=>normalize(typeof entry==='string'?entry:entry.name||entry.title).includes(normalize(title)));const label=saved?(typeof saved==='string'?saved:saved.name||saved.title):title;const image=typeof saved==='object'?saved.image||saved.photo:'';const photo=image||gallery[index%Math.max(gallery.length,1)]?.src;return <article key={title} className="overflow-hidden rounded-md border border-[#e1e7ee] bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="relative aspect-[4/3] overflow-hidden bg-[#edf2f7]">{photo&&<ImageFrame src={mediaUrl(photo)} alt={label} className="transition duration-300 hover:scale-105"/>}<span className="absolute bottom-2 left-2 grid h-8 w-8 place-items-center rounded bg-white text-lg text-[#c9092c]">{icon}</span></div><div className="p-2.5"><h3 className="text-[10px] font-extrabold leading-4 text-[#17385f]">{label}</h3><p className="mt-1 text-[9px] leading-4 text-[#6d7885]">{typeof saved==='object'&&saved.description?saved.description:detail}</p></div></article>;})}</div></div></section>

        {(productList.length>0||categoryNames.length>0)&&<section id="collections" className="mx-auto max-w-[1500px] px-4 py-7 sm:px-7"><div className="flex items-end justify-between gap-3"><div><h2 className="font-display text-3xl font-extrabold text-[#17385f]">Mattress Collections</h2><p className="mt-1 text-xs text-[#697585]">Find a sleep solution for your comfort and support needs</p></div><a href="#contact" className="text-xs font-bold text-[#c9092c]">Ask About a Mattress →</a></div>{productList.length>0?<div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{productList.slice(0,8).map((item,index)=>{const image=item.image||item.photo||item.url||gallery[index%Math.max(gallery.length,1)]?.src;return <article key={`${item.name||item.title}-${index}`} className="overflow-hidden rounded-md border border-[#e1e7ee] bg-white shadow-sm"><div className="aspect-[4/3] bg-[#edf2f7]">{image&&<ImageFrame src={image} alt={item.name||item.title||'Mattress product'}/>}</div><div className="p-3"><h3 className="text-sm font-bold text-[#17385f]">{item.name||item.title}</h3>{[item.brand,item.type||item.category,item.size,item.firmness,item.material].filter(Boolean).length>0&&<p className="mt-1 text-[10px] leading-4 text-[#77818c]">{[item.brand,item.type||item.category,item.size,item.firmness,item.material].filter(Boolean).join(' · ')}</p>}{item.description&&<p className="mt-2 line-clamp-2 text-xs text-[#66717e]">{item.description}</p>}{(item.price||item.offerPrice)&&<p className="mt-2 text-sm font-bold text-[#c9092c]">{item.offerPrice||item.price}</p>}<div className="mt-3 flex gap-2"><button type="button" onClick={()=>setSelectedProduct(item)} className="flex-1 rounded border border-[#17385f] px-2 py-2 text-[10px] font-bold text-[#17385f]">View Details</button><a href={callUrl||'#contact'} className="rounded bg-[#17385f] px-3 py-2 text-[10px] font-bold text-white">Enquire</a></div></div></article>;})}</div>:<div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{(categoryNames.length?categoryNames:['Memory Foam','Orthopedic','Pocket Spring','Bonnell Spring','Latex','Hybrid','Kids Mattress']).slice(0,8).map((category,index)=><div key={`${category}-${index}`} className="rounded-md border border-[#e1e7ee] bg-[#f9fbfd] p-3 text-xs font-semibold text-[#35516e]">{typeof category==='string'?category:category.name||category.title}</div>)}</div>}</section>}

        {offers.length>0&&<section className="bg-[#fff6f7] px-4 py-6 sm:px-7"><div className="mx-auto max-w-[1500px]"><h2 className="font-display text-2xl font-extrabold text-[#17385f]">Mattress Offers</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{offers.map((offer,index)=><article key={`${offer}-${index}`} className="rounded-md border border-[#f0dadd] bg-white p-4"><h3 className="text-sm font-bold text-[#17385f]">{typeof offer==='string'?offer:offer.title||offer.name||'Current offer'}</h3>{typeof offer==='object'&&offer.description&&<p className="mt-2 text-xs text-[#697585]">{offer.description}</p>}</article>)}</div></div></section>}

        <section id="gallery" className="mx-auto max-w-[1500px] px-4 py-7 sm:px-7"><div className="flex items-end justify-between gap-3"><div><h2 className="font-display text-3xl font-extrabold text-[#17385f]">Our Gallery <span className="text-sm text-[#c9092c]">━━</span></h2><p className="mt-1 text-xs text-[#697585]">Mattresses, bedrooms and showroom displays</p></div><button type="button" onClick={()=>gallery[0]&&setLightboxImage(gallery[0].src)} className="text-xs font-bold text-[#c9092c]">View All Photos →</button></div>{gallery.length?<div className="mt-4 grid grid-cols-2 gap-2.5 sm:grid-cols-3 lg:grid-cols-5">{gallery.map((image)=><button key={`${image.src}-${image.index}`} type="button" onClick={()=>setLightboxImage(image.src)} className="aspect-[4/3] overflow-hidden rounded-md border border-[#e1e7ee] bg-[#edf2f7]"><ImageFrame src={image.src} alt={`${name} gallery image ${image.index+1}`} className="transition duration-300 hover:scale-105"/></button>)}</div>:<p className="mt-4 rounded-md bg-[#f5f7fa] p-5 text-sm text-[#697585]">Showroom photos have not been added yet.</p>}</section>

        {videos.length>0&&<section className="bg-[#f7f8fa] px-4 py-7 sm:px-7"><div className="mx-auto max-w-[1500px]"><div className="flex items-end justify-between gap-3"><div><h2 className="font-display text-3xl font-extrabold text-[#17385f]">Our Videos</h2><p className="mt-1 text-xs text-[#697585]">Buying guides, showroom tours and customer stories</p></div><a href="#videos" className="text-xs font-bold text-[#c9092c]">View All Videos →</a></div><div id="videos" className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{videos.slice(0,6).map((video,index)=>{const image=video.thumbnail||video.image||gallery[index%Math.max(gallery.length,1)]?.src;return <button key={`${video.url||video.src}-${index}`} type="button" onClick={()=>setActiveVideo(video)} className="overflow-hidden rounded-md border border-[#e1e7ee] bg-white text-left shadow-sm"><div className="relative aspect-video bg-[#172b46]">{image&&<ImageFrame src={mediaUrl(image)} alt={video.title||video.caption||videoTitles[index%videoTitles.length]}/>}<span className="absolute inset-0 grid place-items-center bg-black/15"><span className="grid h-12 w-12 place-items-center rounded-full bg-[#c9092c] text-lg text-white">▶</span></span>{video.duration&&<span className="absolute bottom-2 right-2 rounded bg-black/75 px-1.5 py-1 text-[10px] font-bold text-white">{video.duration}</span>}</div><span className="block truncate px-3 py-2 text-xs font-bold text-[#17385f]">{video.title||video.caption||videoTitles[index%videoTitles.length]}</span></button>;})}</div></div></section>}

        <section className="mx-auto max-w-[1500px] px-4 py-7 sm:px-7"><h2 className="font-display text-3xl font-extrabold text-[#17385f]">Our Infrastructure</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{infrastructure.map(([icon,title,detail],index)=>{const match=features.find((item)=>normalize(typeof item==='string'?item:item.name||item.title).includes(normalize(title)));const label=match?(typeof match==='string'?match:match.name||match.title):title;return <article key={title} className="rounded-md border border-[#e1e7ee] bg-white p-3 text-center shadow-sm"><span className="mx-auto grid h-10 w-10 place-items-center rounded-full bg-[#edf3f9] text-xl text-[#1262b4]">{icon}</span><h3 className="mt-2 text-[10px] font-bold text-[#17385f]">{label}</h3><p className="mt-1 text-[9px] leading-4 text-[#6e7b89]">{match?'Available at this showroom':detail}</p></article>;})}</div><div className="mt-5 flex flex-wrap gap-2">{['Trusted Brands','Premium Quality','Orthopedic Support','Expert Guidance','Trial Experience','Free Delivery','Affordable Pricing','Warranty','After Sales Support'].map((item)=><span key={item} className="rounded-full border border-[#dfe6ee] bg-[#f7f9fb] px-3 py-2 text-[10px] font-semibold text-[#41576e]">✓ {item}</span>)}</div></section>

        <section id="reviews" className="bg-[#f7f8fa] px-4 py-7 sm:px-7"><div className="mx-auto max-w-[1500px]"><h2 className="font-display text-3xl font-extrabold text-[#17385f]">Customer Reviews</h2><div className="mt-4 rounded-md border border-[#e1e7ee] bg-white p-4 sm:p-6"><ReviewsSection placeId={place._id}/></div></div></section>
      </main>

      <footer id="contact" className="bg-[#102744] px-4 py-8 text-white sm:px-7"><div className="mx-auto grid max-w-[1500px] gap-6 sm:grid-cols-2 lg:grid-cols-4"><div><h3 className="font-display text-lg font-bold">Our Location</h3><p className="mt-3 text-xs leading-5 text-white/75">{name}<br/>{location||'Address not provided'}</p>{mapUrl&&<a href={mapUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex rounded bg-[#c9092c] px-3 py-2 text-[10px] font-bold text-white">Get Directions</a>}</div><div><h3 className="font-display text-lg font-bold">Contact Details</h3><div className="mt-3 space-y-2 text-xs text-white/75">{phone&&<a href={callUrl} className="block">☎ {phone}</a>}{whatsapp&&<a href={whatsapp} target="_blank" rel="noreferrer" className="block">◉ WhatsApp</a>}{email&&<a href={`mailto:${email}`} className="block">✉ {email}</a>}{website&&<a href={website} target="_blank" rel="noreferrer" className="block">Visit website</a>}</div></div><div><h3 className="font-display text-lg font-bold">Follow Us</h3><div className="mt-3 flex flex-wrap gap-2">{Object.entries(socials).filter(([,value])=>value).map(([network,value])=><a key={network} href={network==='whatsapp'?whatsapp:externalUrl(value)} target="_blank" rel="noreferrer" aria-label={network} className="grid h-9 min-w-9 place-items-center rounded bg-white/10 px-2 text-xs font-bold">{network.slice(0,1)}</a>)}</div></div><div><h3 className="font-display text-lg font-bold">Powered by G-Pages</h3><p className="mt-3 text-xs text-white/70">Create your business website</p><a href="/" className="mt-3 inline-flex rounded bg-[#c9092c] px-3 py-2 text-xs font-bold text-white">← Back to Home</a></div></div></footer>

      <div className="fixed bottom-3 left-1/2 z-40 w-[94%] max-w-md -translate-x-1/2 rounded-full border border-[#dfe6ed] bg-white/95 p-2 shadow-lg backdrop-blur md:hidden"><div className="flex gap-2">{phone&&<a href={callUrl} className="flex-1 rounded-full bg-[#17385f] px-2 py-2.5 text-center text-xs font-bold text-white">Call</a>}<a href={visitUrl} target={mapUrl?'_blank':undefined} rel="noreferrer" className="flex-1 rounded-full bg-[#c9092c] px-2 py-2.5 text-center text-xs font-bold text-white">Showroom</a>{whatsapp&&<a href={whatsapp} target="_blank" rel="noreferrer" className="flex-1 rounded-full bg-[#159454] px-2 py-2.5 text-center text-xs font-bold text-white">WhatsApp</a>}</div></div>
      {lightboxImage&&<div role="presentation" className="fixed inset-0 z-[60] grid place-items-center bg-[#071426]/90 p-4" onClick={()=>setLightboxImage('')}><button type="button" aria-label="Close image" onClick={()=>setLightboxImage('')} className="absolute right-4 top-4 rounded bg-white px-4 py-2 text-sm font-bold text-[#17385f]">Close</button><img src={lightboxImage} alt={`${name} mattress image enlarged`} className="max-h-[90vh] max-w-[94vw] rounded-md object-contain" onClick={(event)=>event.stopPropagation()}/></div>}
      {activeVideo&&<MattressVideoModal video={activeVideo} onClose={()=>setActiveVideo(null)}/>}
      {selectedProduct&&<div role="presentation" className="fixed inset-0 z-[60] grid place-items-center bg-[#071426]/75 p-4" onClick={()=>setSelectedProduct(null)}><section role="dialog" aria-modal="true" aria-label={selectedProduct.name||selectedProduct.title||'Mattress details'} className="w-full max-w-lg rounded-md bg-white p-6 shadow-xl" onClick={(event)=>event.stopPropagation()}><button type="button" aria-label="Close product details" onClick={()=>setSelectedProduct(null)} className="float-right text-xl text-[#17385f]">×</button><h2 className="font-display text-2xl font-bold text-[#17385f]">{selectedProduct.name||selectedProduct.title}</h2><p className="mt-3 text-sm leading-6 text-[#66717e]">{selectedProduct.description||'Contact the showroom for mattress size, comfort and availability details.'}</p><div className="mt-3 space-y-1 text-xs text-[#637182]">{[selectedProduct.brand,selectedProduct.type||selectedProduct.category,selectedProduct.size,selectedProduct.firmness,selectedProduct.material,selectedProduct.warranty].filter(Boolean).map((detail,index)=><p key={`${detail}-${index}`}>{detail}</p>)}</div>{phone&&<a href={callUrl} className="mt-5 inline-flex rounded bg-[#c9092c] px-4 py-2.5 text-sm font-bold text-white">Call to Enquire</a>}</section></div>}
    </div>
  );
}
