import React from 'react';

const inputClass = 'mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-blue-500';

export default function SportsAcademyRegistrationFields({ form, setForm, logoFile, setLogoFile, existingLogo, aboutImageFile, setAboutImageFile, galleryFiles, setGalleryFiles, videoFiles, setVideoFiles }) {
  const profile = form.sportsAcademy || {};
  const update = (field, value) => setForm((current) => ({ ...current, sportsAcademy: { ...(current.sportsAcademy || {}), [field]: value } }));
  const updateProgram = (index, field, value) => update('trainingPrograms', (profile.trainingPrograms || []).map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item));
  const updateCoach = (index, field, value) => update('coaches', (profile.coaches || []).map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item));
  const updateGalleryItem = (kind, index, field, value) => update(kind, (profile[kind] || []).map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item));
  const addGalleryItem = (kind) => update(kind, [...(profile[kind] || []), { title: '', url: '', file: null }]);

  return <div className="col-span-2 space-y-5">
    <section className="rounded-2xl border border-orange-200 bg-gradient-to-r from-orange-50 to-white p-5 sm:p-7"><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-orange-700">Sports Academy business page</p><h2 className="mt-2 text-2xl font-extrabold text-[#12345d]">Build your Sports Academy page</h2><p className="mt-2 text-sm text-slate-600">Add your sports programs, coaches, facilities and media for the public academy page.</p></section>

    <section className="rounded-xl border border-blue-100 bg-white p-5 shadow-sm sm:p-7"><h3 className="text-lg font-extrabold text-[#12345d]">Branding and introduction</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-ink/70">Academy logo<input type="file" accept="image/*" onChange={(event) => setLogoFile(event.target.files?.[0] || null)} className={inputClass}/>{logoFile && <small className="mt-1 block text-blue-700">{logoFile.name}</small>}{!logoFile && existingLogo && <img src={existingLogo} alt="Current academy logo" className="mt-2 h-16 w-16 rounded object-contain"/>}</label><label className="text-sm font-semibold text-ink/70">Tagline<input value={profile.tagline || ''} onChange={(event) => update('tagline', event.target.value)} placeholder="Train · Compete · Excel" className={inputClass}/></label><label className="text-sm font-semibold text-ink/70">About image URL<input value={profile.aboutImage || ''} onChange={(event) => update('aboutImage', event.target.value)} placeholder="https://..." className={inputClass}/><input type="file" accept="image/*" onChange={(event) => setAboutImageFile(event.target.files?.[0] || null)} className={inputClass}/>{aboutImageFile && <small className="mt-1 block text-blue-700">{aboutImageFile.name}</small>}</label><label className="text-sm font-semibold text-ink/70">Intro video URL<input value={profile.videoUrl || ''} onChange={(event) => update('videoUrl', event.target.value)} placeholder="YouTube or public video URL" className={inputClass}/><input type="file" accept="video/*" onChange={(event) => setVideoFiles((files) => [...files, event.target.files?.[0]].filter(Boolean))} className={inputClass}/></label><label className="text-sm font-semibold text-ink/70 sm:col-span-2">About the Academy<textarea rows={4} value={profile.about || ''} onChange={(event) => update('about', event.target.value)} placeholder="Describe your coaching approach and academy environment" className={inputClass}/></label><label className="text-sm font-semibold text-ink/70 sm:col-span-2">Why choose your academy? (one per line)<textarea rows={3} value={(profile.whyChoose || []).map((item) => typeof item === 'string' ? item : item.name || item.title).join('\n')} onChange={(event) => update('whyChoose', event.target.value.split('\n').map((value) => value.trim()).filter(Boolean))} placeholder={'Professional coaches\nModern facilities\nRegular tournaments'} className={inputClass}/></label></div></section>

    <section className="rounded-xl border border-blue-100 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-extrabold text-[#12345d]">Sports programs</h3><p className="mt-1 text-xs text-slate-500">Each program appears as a card on your public page.</p></div><button type="button" onClick={() => update('trainingPrograms', [...(profile.trainingPrograms || []), { name: '', description: '', ageGroup: '', schedule: '', coach: '', image: '' }])} className="rounded-full bg-blue-800 px-4 py-2 text-xs font-bold text-white">+ Add Program</button></div>{(profile.trainingPrograms || []).map((item, index) => <div key={index} className="mt-4 grid gap-3 rounded-xl border border-blue-100 bg-[#f8fbff] p-4 sm:grid-cols-2"><label className="text-xs font-bold">Sport name<input required value={item.name || ''} onChange={(event) => updateProgram(index, 'name', event.target.value)} placeholder="Cricket" className={inputClass}/></label><label className="text-xs font-bold">Age group<input value={item.ageGroup || ''} onChange={(event) => updateProgram(index, 'ageGroup', event.target.value)} placeholder="8–16 years" className={inputClass}/></label><label className="text-xs font-bold">Schedule<input value={item.schedule || ''} onChange={(event) => updateProgram(index, 'schedule', event.target.value)} placeholder="Mon, Wed, Fri" className={inputClass}/></label><label className="text-xs font-bold">Coach<input value={item.coach || ''} onChange={(event) => updateProgram(index, 'coach', event.target.value)} placeholder="Coach name" className={inputClass}/></label><label className="text-xs font-bold sm:col-span-2">Description<textarea rows={2} value={item.description || ''} onChange={(event) => updateProgram(index, 'description', event.target.value)} className={inputClass}/></label><label className="text-xs font-bold sm:col-span-2">Program image URL<input value={item.image || ''} onChange={(event) => updateProgram(index, 'image', event.target.value)} placeholder="https://..." className={inputClass}/></label><button type="button" onClick={() => update('trainingPrograms', profile.trainingPrograms.filter((_, itemIndex) => itemIndex !== index))} className="text-left text-xs font-bold text-red-700 sm:col-span-2">Remove program</button></div>)}</section>

    <section className="rounded-xl border border-blue-100 bg-white p-5 shadow-sm sm:p-7"><h3 className="text-lg font-extrabold text-[#12345d]">Coaches and facilities</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-ink/70">Facilities (one per line)<textarea rows={4} value={(profile.facilities || []).map((item) => typeof item === 'string' ? item : item.name || item.title).join('\n')} onChange={(event) => update('facilities', event.target.value.split('\n').map((value) => value.trim()).filter(Boolean))} placeholder={'Cricket nets\nIndoor stadium\nGym and fitness'} className={inputClass}/></label><label className="text-sm font-semibold text-ink/70">Academy highlights (one per line)<textarea rows={4} value={(profile.highlights || []).join('\n')} onChange={(event) => update('highlights', event.target.value.split('\n').map((value) => value.trim()).filter(Boolean))} placeholder={'Certified coaches\nTournament exposure\nPersonal training plans'} className={inputClass}/></label></div><div className="mt-5 flex items-center justify-between"><h4 className="font-bold text-[#12345d]">Coaches</h4><button type="button" onClick={() => update('coaches', [...(profile.coaches || []), { name: '', specialty: '' }])} className="rounded-full bg-blue-800 px-4 py-2 text-xs font-bold text-white">+ Add Coach</button></div>{(profile.coaches || []).map((item, index) => <div key={index} className="mt-3 grid gap-3 rounded-xl border border-blue-100 bg-[#f8fbff] p-4 sm:grid-cols-2"><label className="text-xs font-bold">Coach name<input value={item.name || ''} onChange={(event) => updateCoach(index, 'name', event.target.value)} className={inputClass}/></label><label className="text-xs font-bold">Specialty<input value={item.specialty || ''} onChange={(event) => updateCoach(index, 'specialty', event.target.value)} placeholder="Cricket coach" className={inputClass}/></label><button type="button" onClick={() => update('coaches', profile.coaches.filter((_, itemIndex) => itemIndex !== index))} className="text-left text-xs font-bold text-red-700 sm:col-span-2">Remove coach</button></div>)}</section>

    <section className="rounded-xl border border-blue-100 bg-white p-5 shadow-sm sm:p-7"><h3 className="text-lg font-extrabold text-[#12345d]">Academy photos and videos</h3><p className="mt-1 text-xs text-slate-500">Upload images and videos manually. Add public video links above.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-ink/70">Photo uploads<input type="file" accept="image/*" multiple onChange={(event) => setGalleryFiles(Array.from(event.target.files || []))} className={inputClass}/>{galleryFiles.length > 0 && <small className="mt-1 block text-blue-700">{galleryFiles.length} photo(s) selected</small>}</label><label className="text-sm font-semibold text-ink/70">Video uploads<input type="file" accept="video/*" multiple onChange={(event) => setVideoFiles(Array.from(event.target.files || []))} className={inputClass}/>{videoFiles.length > 0 && <small className="mt-1 block text-blue-700">{videoFiles.length} video(s) selected</small>}</label></div></section>
  </div>;
}
