import React, { useMemo, useState } from 'react';
import ReviewsSection from '../../../components/ReviewsSection';
import { getProfileData, safeUrl } from '../../../components/public/PublicProfileShared';
import { resolveVideoPlayback } from '../../../utils/video';
import { getWhatsAppUrl } from '../../healthcare-medical/healthcareUtils';

const defaults = {
  services: ['Domestic Tours', 'International Tours', 'Honeymoon Packages', 'Family Tours', 'Adventure Tours', 'Pilgrimage Tours', 'Corporate Tours', 'Customized Tours'],
  amenities: ['Experienced Travel Team', 'Best Tour Packages', 'Customized Trips', 'Hotel Booking', 'Transport Support', '24/7 Customer Support', 'Secure Booking', 'Local Travel Assistance'],
  serviceDescriptions: ['Discover the best of India with carefully planned itineraries.', 'See the world with trusted local partners and clear planning.', 'Thoughtful escapes designed for a special journey together.', 'Comfortable, well-paced trips for all ages.', 'Explore the outdoors with experienced trip leaders.', 'Meaningful visits with reliable travel arrangements.', 'Dependable planning for teams, events, and business travel.', 'A trip shaped around your interests and pace.'],
};
const defaultPhotos = [
  'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=85',
  'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=85',
  'https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=1200&q=85',
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85',
];
const normalizeItems = (value) => {
  if (Array.isArray(value)) return value.map((item) => typeof item === 'string' ? { name: item } : item).filter(Boolean);
  return String(value || '').split(/[\n,]/).map((name) => name.trim()).filter(Boolean).map((name) => ({ name }));
};
const first = (...values) => values.find((value) => value !== undefined && value !== null && value !== '');
const sectionLink = (value) => `#${value.toLowerCase().replace(/[^a-z]+/g, '-')}`;
const actionClass = 'inline-flex items-center justify-center rounded-md px-4 py-2.5 text-sm font-bold transition hover:-translate-y-0.5';

function Image({ src, alt, className = '', eager = false }) {
  return <img src={src || defaultPhotos[0]} alt={alt} loading={eager ? 'eager' : 'lazy'} className={`h-full w-full object-cover ${className}`} />;
}

function SectionTitle({ eyebrow, title, link }) {
  return <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#087f8c]">{eyebrow}</p><h2 className="mt-1 font-display text-3xl font-bold text-[#16364d] sm:text-4xl">{title}</h2></div>{link && <a href={link.href} className="text-sm font-bold text-[#087f8c]">{link.label} <span aria-hidden="true">→</span></a>}</div>;
}

export default function ToursTravelsPublicPage({ place }) {
  const profile = getProfileData(place);
  const specific = place.attributes?.businessProfile?.categorySpecific || place.attributes?.travelDetails || {};
  const name = place.name || 'Tours & Travels';
  const tagline = first(profile.tagline, 'Explore the world. Create beautiful memories.');
  const description = first(profile.about, place.description, 'Discover amazing destinations, customized tour packages and unforgettable travel experiences.');
  const phone = first(place.phone, profile.phone);
  const whatsapp = getWhatsAppUrl(place.socialLinks?.whatsapp || specific.socialLinks?.whatsapp || profile.whatsapp || phone);
  const email = first(place.email, profile.email);
  const address = [place.address, place.location?.area?.name, place.location?.city?.name, place.location?.district?.name, place.location?.state?.name, specific.country].filter(Boolean).join(', ');
  const mapUrl = place.coordinates?.lat && place.coordinates?.lng
    ? `https://www.google.com/maps/search/?api=1&query=${place.coordinates.lat},${place.coordinates.lng}`
    : `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`;
  const phoneUrl = phone ? `tel:${String(phone).replace(/[^+\d]/g, '')}` : '#contact';
  const gallery = useMemo(() => (profile.gallery?.length ? profile.gallery : place.images || []).filter(Boolean).slice(0, 10), [place.images, profile.gallery]);
  const photos = gallery.length ? gallery : defaultPhotos;
  const services = normalizeItems(specific.services || profile.services || place.services);
  const offers = services.length ? services : defaults.services.map((name, index) => ({ name, description: defaults.serviceDescriptions[index] }));
  const packages = normalizeItems(specific.packages || profile.packages || profile.packageDetails);
  const destinations = normalizeItems(specific.destinations || profile.destinations);
  const vehicles = normalizeItems(specific.vehicles || profile.vehicles);
  const videos = (Array.isArray(profile.videos) ? profile.videos : []).slice(0, 10).map((video) => typeof video === 'string' ? { url: video, title: 'Travel experience' } : video);
  const social = { ...(place.socialLinks || {}), ...(specific.socialLinks || {}), ...(profile.socialMedia || {}) };
  const stats = [['10+', 'Years Experience'], ['5000+', 'Happy Travelers'], ['100+', 'Destinations'], ['100%', 'Travel Support']];
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeGallery, setActiveGallery] = useState('All');
  const [lightbox, setLightbox] = useState(null);
  const [activeVideo, setActiveVideo] = useState(null);
  const categories = ['All', 'Destinations', 'Tours', 'Adventure', 'Family Trips', 'Honeymoon', 'International'];
  const visibleGallery = photos.filter((image, index) => activeGallery === 'All' || (specific.galleryCategories?.[index] || specific.galleryCategory || 'Destinations') === activeGallery);
  const videoPlayback = activeVideo ? resolveVideoPlayback(activeVideo) : null;
  const bookingHref = whatsapp || (email ? `mailto:${email}` : '#contact');
  const bookingTarget = whatsapp ? '_blank' : undefined;
  const navigation = [['Home', '#home'], ['About', '#about'], ['Services', '#services'], ['Packages', '#packages'], ['Gallery', '#gallery'], ['Contact', '#contact']];

  return <div className="min-h-screen overflow-x-hidden bg-white font-body text-[#16364d]" style={{ '--tour-teal': '#087f8c', '--tour-blue': '#1456a0', '--tour-orange': '#f17832' }}>
    <header className="sticky top-0 z-40 border-b border-[#e3ecee] bg-white/95 shadow-sm backdrop-blur">
      <div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-4 py-3 sm:px-7">
        <a href="#home" className="flex min-w-0 items-center gap-3"><div className="h-11 w-11 shrink-0 overflow-hidden rounded-lg border border-[#e2ecee] bg-[#f4f8f8]">{profile.logo || place.logo ? <Image src={profile.logo || place.logo} alt={`${name} logo`} /> : <span className="grid h-full place-items-center text-xl text-[#087f8c]">✦</span>}</div><span className="min-w-0"><span className="block truncate font-display text-lg font-bold leading-tight text-[#16364d] sm:text-xl">{name}</span><span className="block truncate text-[11px] text-[#68808c]">{tagline}</span></span></a>
        <nav className="hidden items-center gap-5 text-xs font-semibold lg:flex">{navigation.map(([label, href]) => <a key={label} href={href} className="hover:text-[#087f8c]">{label}</a>)}</nav>
        <div className="hidden items-center gap-2 md:flex">{specific.actions?.callNow !== false && <a href={phoneUrl} className="rounded-md bg-[#1456a0] px-3 py-2 text-xs font-bold text-white">☎ Call Now</a>}{specific.actions?.whatsAppAction !== false && <a href={whatsapp || '#contact'} target={whatsapp ? '_blank' : undefined} rel="noreferrer" className="rounded-md bg-[#168d5a] px-3 py-2 text-xs font-bold text-white">◉ WhatsApp</a>}{specific.actions?.bookNow !== false && <a href="#contact" className="rounded-md bg-[#f17832] px-3 py-2 text-xs font-bold text-white">Book Now</a>}</div>
        <button type="button" onClick={() => setMenuOpen((open) => !open)} className="grid h-10 w-10 place-items-center rounded-md border border-[#dbe6e9] text-lg lg:hidden" aria-expanded={menuOpen} aria-label="Toggle navigation">{menuOpen ? '×' : '☰'}</button>
      </div>
      {menuOpen && <nav className="border-t border-[#e3ecee] bg-white px-5 py-2 lg:hidden">{navigation.map(([label, href]) => <a key={label} href={href} onClick={() => setMenuOpen(false)} className="block border-b border-[#eef2f3] py-3 text-sm font-semibold">{label}</a>)}<div className="flex gap-2 py-3">{specific.actions?.callNow !== false && <a href={phoneUrl} className="rounded-md bg-[#1456a0] px-3 py-2 text-xs font-bold text-white">Call Now</a>}{specific.actions?.whatsAppAction !== false && <a href={whatsapp || '#contact'} className="rounded-md bg-[#168d5a] px-3 py-2 text-xs font-bold text-white">WhatsApp</a>}{specific.actions?.bookNow !== false && <a href="#contact" className="rounded-md bg-[#f17832] px-3 py-2 text-xs font-bold text-white">Book Now</a>}</div></nav>}
    </header>

    <main>
      <section id="home" className="relative isolate bg-[#123950] text-white"><div className="absolute inset-0"><Image src={profile.coverImage || place.coverImage || photos[0]} alt={`${name} destinations`} eager /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(9,35,52,.88),rgba(9,35,52,.5)_55%,rgba(9,35,52,.08))]" /></div><div className="relative mx-auto grid min-h-[500px] max-w-[1500px] items-center px-5 py-14 sm:min-h-[560px] sm:px-10 lg:grid-cols-[1.05fr_.95fr]"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#ffd078]">{name} · Tours &amp; Travels</p><h1 className="mt-4 font-display text-4xl font-bold leading-[1.05] sm:text-6xl">Explore The World<br /><span className="text-[#ffbd43]">Create Beautiful Memories</span></h1><p className="mt-5 max-w-xl text-base leading-7 text-white/85">Discover amazing destinations, customized tour packages and unforgettable travel experiences.</p><div className="mt-7 flex flex-wrap gap-3"><a href="#packages" className={`${actionClass} bg-[#f17832] text-white`}>✈ Explore Packages</a><a href="#contact" className={`${actionClass} bg-white text-[#1456a0]`}>⌖ Plan Your Trip</a></div><div className="mt-8 grid grid-cols-2 gap-x-5 gap-y-4 sm:grid-cols-5">{['Domestic Tours', 'International Tours', 'Customized Packages', 'Hotel Booking', 'Transport Support'].map((item, index) => <div key={item} className="text-xs font-semibold text-white/90"><span className="mb-1 block text-xl text-[#ffd078]">{['⌖', '◎', '✦', '▣', '▰'][index]}</span>{item}</div>)}</div></div><div className="hidden h-[330px] grid-cols-2 grid-rows-2 gap-3 lg:grid"><div className="row-span-2 rotate-[-2deg] overflow-hidden rounded-xl border-4 border-white shadow-xl"><Image src={photos[1 % photos.length]} alt="Tropical destination" /></div><div className="rotate-[2deg] overflow-hidden rounded-xl border-4 border-white shadow-xl"><Image src={photos[2 % photos.length]} alt="Mountain destination" /></div><div className="rotate-[1deg] overflow-hidden rounded-xl border-4 border-white shadow-xl"><Image src={photos[3 % photos.length]} alt="City destination" /></div></div></div></section>

      <section id="about" className="mx-auto grid max-w-7xl gap-8 px-5 py-12 sm:px-8 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><div className="relative h-64 overflow-hidden rounded-lg shadow-lg sm:h-[330px]"><Image src={place.attributes?.aboutImage || place.aboutImage || profile.gallery?.[0] || photos[0]} alt={`${name} travel experience`} /><div className="absolute bottom-4 left-4 max-w-[190px] rotate-[-4deg] bg-white px-4 py-3 font-display text-lg font-bold leading-tight text-[#16364d] shadow-lg">Travel more.<br />Live happier.</div></div><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#087f8c]">Our story</p><h2 className="mt-1 font-display text-3xl font-bold text-[#16364d]">About <span className="text-[#f17832]">Us</span></h2><p className="mt-4 whitespace-pre-line text-sm leading-6 text-[#667d89]">{description}</p><a href="#contact" className="mt-4 inline-flex rounded-md bg-[#f17832] px-4 py-2.5 text-sm font-bold text-white">Read More →</a><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{stats.map(([value, label]) => <div key={label} className="rounded-md border border-[#e3ecee] px-3 py-3 text-center"><p className="font-display text-xl font-bold text-[#087f8c]">{specific.stats?.[label] || value}</p><p className="mt-1 text-[10px] leading-4 text-[#68808c]">{label}</p></div>)}</div></div></section>

      <section id="services" className="bg-[#f5f9fa] px-5 py-12 sm:px-8"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="Plan your way" title="Our Travel Services" link={{ label: 'View All Services', href: '#contact' }} /><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-8">{offers.slice(0, 8).map((item, index) => <article key={`${item.name}-${index}`} className="overflow-hidden rounded-md border border-[#e1eaed] bg-white shadow-sm"><div className="h-24 sm:h-28"><Image src={item.image || photos[(index + 1) % photos.length]} alt={item.name || 'Travel service'} /></div><div className="p-3"><span className="text-lg text-[#087f8c]">{['⌖', '◎', '♡', '⌂', '⚑', '◈', '▣', '✦'][index]}</span><h3 className="mt-1 text-xs font-bold text-[#16364d]">{item.name || 'Travel service'}</h3><p className="mt-1 line-clamp-2 text-[10px] leading-4 text-[#718590]">{item.description || 'Personal support and smooth planning for your journey.'}</p></div></article>)}</div></div></section>

      <section id="packages" className="px-5 py-12 sm:px-8"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="Handpicked escapes" title="Popular Tour Packages" link={{ label: 'View All Packages', href: '#contact' }} /><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(packages.length ? packages : ['Goa', 'Kerala', 'Kashmir', 'Manali', 'Rajasthan', 'Dubai', 'Singapore', 'Bali'].map((destination) => ({ name: `${destination} Package`, destination }))).slice(0, 8).map((item, index) => { const destination = item.destination || item.location || item.name || item.title || 'Explore'; const price = item.offerPrice || item.startingPrice || item.price; return <article key={`${item.name || item.title}-${index}`} className="overflow-hidden rounded-md border border-[#e0e9ec] bg-white shadow-[0_5px_18px_rgba(18,54,77,.08)]"><div className="relative h-36"><Image src={item.image || photos[(index + 1) % photos.length]} alt={`${destination} tour package`} /><span className="absolute bottom-2 left-2 rounded bg-[#16364d]/85 px-2 py-1 text-[10px] font-bold text-white">{destination}</span></div><div className="p-3"><h3 className="font-display text-base font-bold text-[#16364d]">{item.name || item.title || `${destination} Package`}</h3><p className="mt-1 text-[11px] text-[#72858e]">{item.duration || `${item.days || 4} Nights / ${item.nights || 5} Days`}</p>{price && <p className="mt-2 font-display text-lg font-bold text-[#1456a0]">{String(price).match(/[₹$€£]/) ? price : `₹${price}`} <span className="text-[10px] font-normal text-[#718590]">per person</span></p>}<p className="mt-2 line-clamp-2 text-xs leading-5 text-[#718590]">{item.description || (item.highlights || []).join(' · ') || 'Hotels · Sightseeing · Transfers'}</p>{item.includes?.length > 0 && <p className="mt-2 text-[10px] font-semibold text-[#087f8c]">Includes {item.includes.join(' · ')}</p>}<div className="mt-3 flex gap-2"><a href="#contact" className="flex-1 rounded border border-[#1456a0] py-2 text-center text-[10px] font-bold text-[#1456a0]">View Details</a><a href={bookingHref} target={bookingTarget} rel="noreferrer" className="flex-1 rounded bg-[#f17832] py-2 text-center text-[10px] font-bold text-white">Book Now</a></div></div></article>; })}</div></div></section>

      {destinations.length > 0 && <section className="bg-[#16364d] px-5 py-12 text-white sm:px-8"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="Go somewhere wonderful" title="Featured Destinations" link={{ label: 'Plan a trip', href: '#contact' }} /><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{destinations.slice(0, 8).map((item, index) => <article key={`${item.name}-${index}`} className="group relative h-52 overflow-hidden rounded-md"><Image src={item.image || photos[(index + 2) % photos.length]} alt={item.name || 'Destination'} className="transition duration-500 group-hover:scale-105" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#102f46] to-transparent p-4 pt-12"><h3 className="font-display text-xl font-bold">{item.name}</h3><p className="mt-1 text-xs text-white/75">{item.description || item.bestTime || item.country}</p></div></article>)}</div></div></section>}

      {vehicles.length > 0 && <section className="bg-[#f5f9fa] px-5 py-12 sm:px-8"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="Comfort along the way" title="Transport Support" /><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{vehicles.slice(0, 8).map((vehicle, index) => <article key={`${vehicle.name}-${index}`} className="overflow-hidden rounded-md border border-[#e1eaed] bg-white"><div className="h-36"><Image src={vehicle.image || photos[index % photos.length]} alt={vehicle.name || 'Travel vehicle'} /></div><div className="p-4"><h3 className="font-bold">{vehicle.name || vehicle.title}</h3><p className="mt-1 text-xs text-[#718590]">{vehicle.type} · {vehicle.capacity || vehicle.seating || ''}</p><p className="mt-2 text-sm font-semibold text-[#087f8c]">{vehicle.price || ''}</p></div></article>)}</div></div></section>}

      <section id="gallery" className="px-5 py-12 sm:px-8"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="See the world with us" title="Our Travel Gallery" link={{ label: 'View All Photos', href: '#gallery' }} /><div className="mt-5 flex flex-wrap gap-2">{categories.map((category) => <button type="button" key={category} onClick={() => setActiveGallery(category)} className={`rounded-full border px-3 py-1.5 text-[11px] font-semibold ${activeGallery === category ? 'border-[#1456a0] bg-[#1456a0] text-white' : 'border-[#dce7ea] bg-white text-[#526c79]'}`}>{category}</button>)}</div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-5">{visibleGallery.map((image, index) => <button type="button" key={`${image}-${index}`} onClick={() => setLightbox(image)} className={`group relative aspect-[4/3] overflow-hidden rounded-md ${index === 0 ? 'sm:col-span-2 sm:row-span-2 sm:aspect-auto' : ''}`}><Image src={image} alt={`${name} travel gallery ${index + 1}`} className="transition duration-500 group-hover:scale-105" /><span className="absolute inset-0 bg-[#102f46]/0 transition group-hover:bg-[#102f46]/15" /></button>)}</div></div></section>

      {videos.length > 0 && <section id="videos" className="bg-[#f5f9fa] px-5 py-12 sm:px-8"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="Stories from the road" title="Our Travel Videos" link={{ label: 'View All Videos', href: '#videos' }} /><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{videos.slice(0, 4).map((video, index) => <button type="button" key={`${video.url}-${index}`} onClick={() => setActiveVideo(video)} className="group overflow-hidden rounded-md border border-[#e1eaed] bg-white text-left shadow-sm"><div className="relative aspect-video"><Image src={video.thumbnail || photos[(index + 1) % photos.length]} alt={video.title || 'Travel video'} /><span className="absolute inset-0 grid place-items-center bg-[#102f46]/15"><span className="grid h-12 w-12 place-items-center rounded-full border-2 border-white bg-white/90 text-lg text-[#1456a0] transition group-hover:scale-110">▶</span></span>{video.duration && <span className="absolute bottom-2 right-2 rounded bg-black/75 px-2 py-1 text-[10px] text-white">{video.duration}</span>}</div><span className="block p-3 text-sm font-bold text-[#16364d]">{video.title || 'Travel experience'}</span></button>)}</div></div></section>}

      <section className="px-5 py-12 sm:px-8"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="Good journeys, great care" title="Why Travel With Us" /><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{defaults.amenities.map((item, index) => <article key={item} className="flex items-center gap-3 rounded-md border border-[#e2eaed] bg-white p-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#e8f5f3] text-lg text-[#087f8c]">{['♙', '✦', '⌁', '▣', '▰', '◷', '✓', '⌖'][index]}</span><h3 className="text-xs font-bold leading-4">{specific.amenities?.[index] || item}</h3></article>)}</div></div></section>

      {specific.enableReviews !== false && <section className="bg-[#f5f9fa] px-5 py-12 sm:px-8"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="Kind words from travellers" title="Customer Reviews" /><div className="mt-5 rounded-md border border-[#e1eaed] bg-white p-4 sm:p-7"><ReviewsSection placeId={place._id} /></div></div></section>}

      <section id="contact" className="px-5 py-12 sm:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#087f8c]">Let’s make a plan</p><h2 className="mt-2 font-display text-3xl font-bold text-[#16364d] sm:text-4xl">Your next trip starts here.</h2><p className="mt-3 text-sm leading-6 text-[#68808c]">Tell us where you want to go. We’ll help make the journey memorable.</p><div className="mt-5 space-y-3 text-sm text-[#526c79]">{address && <p>⌖ {address}</p>}{phone && <p>☎ <a href={phoneUrl} className="font-semibold">{phone}</a></p>}{whatsapp && <p>◉ <a href={whatsapp} target="_blank" rel="noreferrer" className="font-semibold">WhatsApp</a></p>}{email && <p>✉ <a href={`mailto:${email}`} className="font-semibold">{email}</a></p>}{profile.website && <p>◎ <a href={safeUrl(profile.website)} target="_blank" rel="noreferrer" className="font-semibold">{profile.website}</a></p>}</div><div className="mt-5 flex flex-wrap gap-2"><a href={mapUrl} target="_blank" rel="noreferrer" className={`${actionClass} bg-[#1456a0] text-white`}>Get Directions</a><a href={bookingHref} target={bookingTarget} rel="noreferrer" className={`${actionClass} bg-[#f17832] text-white`}>Plan Your Trip</a></div></div><div className="min-h-[250px] overflow-hidden rounded-md border border-[#dce7ea] bg-[#e8f0f2]"><iframe title={`${name} map`} src={`https://www.google.com/maps?q=${encodeURIComponent(address)}&output=embed`} className="h-full min-h-[250px] w-full border-0" loading="lazy" /></div></div></section>
    </main>

    <footer className="bg-[#102f46] px-5 py-10 text-white sm:px-8"><div className="mx-auto grid max-w-7xl gap-8 sm:grid-cols-2 lg:grid-cols-4"><div><h3 className="font-display text-lg font-bold text-[#ffbd59]">Our Location</h3><p className="mt-3 text-sm leading-6 text-white/65">{address || 'Contact us for our office location.'}</p><a href={mapUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex rounded bg-[#1456a0] px-3 py-2 text-xs font-bold">Get Directions</a></div><div><h3 className="font-display text-lg font-bold text-[#ffbd59]">Contact Details</h3><div className="mt-3 space-y-2 text-sm text-white/65">{phone && <a className="block" href={phoneUrl}>{phone}</a>}{whatsapp && <a className="block" href={whatsapp} target="_blank" rel="noreferrer">WhatsApp</a>}{email && <a className="block" href={`mailto:${email}`}>{email}</a>}{profile.website && <a className="block" href={safeUrl(profile.website)} target="_blank" rel="noreferrer">Website</a>}</div></div><div><h3 className="font-display text-lg font-bold text-[#ffbd59]">Follow Us</h3><div className="mt-3 flex flex-wrap gap-2">{Object.entries(social).filter(([, value]) => value).map(([platform, value]) => <a key={platform} href={safeUrl(value)} target="_blank" rel="noreferrer" className="rounded border border-white/20 px-3 py-2 text-xs capitalize">{platform}</a>)}</div>{!Object.values(social).some(Boolean) && <p className="mt-3 text-sm text-white/55">Social links coming soon.</p>}</div><div><h3 className="font-display text-lg font-bold text-[#ffbd59]">G-Pages</h3><p className="mt-3 text-sm leading-6 text-white/65">Discover local businesses and plan your next experience.</p><a href="/" className="mt-3 inline-flex rounded bg-white px-3 py-2 text-xs font-bold text-[#16364d]">← Back to Home</a></div></div><div className="mx-auto mt-8 max-w-7xl border-t border-white/15 pt-4 text-xs text-white/45">© {new Date().getFullYear()} {name} · Powered by G-Pages</div></footer>

    {lightbox && <div className="fixed inset-0 z-50 grid place-items-center bg-[#071b31]/95 p-4" onClick={() => setLightbox(null)}><button type="button" onClick={() => setLightbox(null)} className="absolute right-4 top-4 grid h-10 w-10 place-items-center rounded-full bg-white text-lg text-[#16364d]" aria-label="Close photo">×</button><img src={lightbox} alt="Enlarged travel gallery" className="max-h-[88vh] max-w-[94vw] rounded-md object-contain" onClick={(event) => event.stopPropagation()} /></div>}
    {activeVideo && videoPlayback && <div className="fixed inset-0 z-50 grid place-items-center bg-[#071b31]/90 p-4" onClick={() => setActiveVideo(null)}><div role="dialog" aria-modal="true" aria-label={activeVideo.title || 'Travel video'} className="w-full max-w-4xl overflow-hidden rounded-md bg-white" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between gap-3 p-3"><h2 className="font-display text-lg font-bold">{activeVideo.title || 'Travel experience'}</h2><button type="button" onClick={() => setActiveVideo(null)} aria-label="Close video" className="grid h-9 w-9 place-items-center rounded-full border">×</button></div>{videoPlayback.embedUrl ? <iframe title={activeVideo.title || 'Travel video'} src={videoPlayback.embedUrl} allow="autoplay; fullscreen; picture-in-picture" allowFullScreen className="aspect-video w-full border-0" /> : <video src={videoPlayback.url} controls autoPlay className="aspect-video w-full bg-black" />}</div></div>}
  </div>;
}
