export default [
  "Header Menu Items",
  "Header CTA Text",
  "Header CTA Link",
  "Hero Small Heading",
  "Hero Main Heading",
  "Hero Description",
  "Hero Primary Button Text",
  "Hero Primary Button Link",
  "Hero Secondary Button Text",
  "Hero Secondary Button Link",
  "Hero Media URL",
  "Hero Media Type",
  "About Section Title",
  "About Description",
  "About Image URL",
  "About Video URL",
  "About Highlights",
  "Rooms",
  "Stay Options",
  "Activities",
  "Facilities",
  "Infrastructure",
  "Highlights",
  "Packages",
  "Resort Philosophy",
  "Gallery Captions",
  "Videos",
  "Reels",
  "Booking Enabled",
  "Stay Enquiry Enabled",
  "WhatsApp Booking Enabled",
  "Phone Booking Enabled",
  "Booking Button Text",
  "Booking Phone",
  "Booking WhatsApp",
  "Booking Email",
  "Instagram URL",
  "Facebook URL",
  "YouTube URL",
  "LinkedIn URL",
  "X / Twitter URL",
  "Enable Reviews",
  "Allow Customer Reviews",
  "Require Admin Approval",
  "Show Star Rating",
  "Enable Like",
  "Enable Share",
  "Enable Comment",
  "Enable Report",
  "SEO Title",
  "SEO Description",
  "SEO Keywords",
  "OG Image URL"
];
