import React, { useMemo, useRef, useState } from 'react';
import ReviewsSection from '../../../components/ReviewsSection';
import FavoriteButton from '../../../components/FavoriteButton';
import api from '../../../services/api';
import { PublicVideoCard } from '../../../components/public/PublicProfileShared';
import { getWebsiteUrl, getWhatsAppUrl } from '../healthcareUtils';
import { LocationMapIcon } from '../HealthcareIcons';

const scrollRow = (ref, direction) => ref.current?.scrollBy({ left: direction * Math.max(280, ref.current.clientWidth * 0.78), behavior: 'smooth' });
const imageOf = (item) => typeof item === 'string' ? item : item?.url || item?.image || item?.photo || '';
const ListSection = ({ id, eyebrow, title, children, className = '' }) => <section id={id} className={`scroll-mt-24 px-4 py-12 sm:px-6 lg:px-8 ${className}`}><div className="mx-auto max-w-7xl"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-rose-700">{eyebrow}</p><h2 className="mt-2 text-2xl font-extrabold tracking-tight text-slate-900 sm:text-3xl">{title}</h2><div className="mt-6">{children}</div></div></section>;

function AppointmentDialog({ name, services, onClose, whatsapp }) {
  const [form, setForm] = useState({ name: '', phone: '', service: '', date: '', message: '' });
  const [error, setError] = useState('');
  const submit = (event) => {
    event.preventDefault();
    if (!whatsapp) { setError('This clinic has not added a WhatsApp number yet. Please call the clinic.'); return; }
    const message = [`Appointment request for ${name}`, `Name: ${form.name}`, `Phone: ${form.phone}`, `Service: ${form.service || 'Not selected'}`, `Preferred date: ${form.date || 'Flexible'}`, `Message: ${form.message || 'No additional message'}`].join('\n');
    window.open(`${whatsapp}${whatsapp.includes('?') ? '&' : '?'}text=${encodeURIComponent(message)}`, '_blank', 'noopener,noreferrer');
    onClose();
  };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div role="dialog" aria-modal="true" aria-labelledby="appointment-title" className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-rose-700">Request a visit</p><h2 id="appointment-title" className="mt-1 text-2xl font-extrabold">Book an appointment</h2></div><button type="button" onClick={onClose} aria-label="Close appointment form" className="rounded-full border px-3 py-1 text-xl">×</button></div><form onSubmit={submit} className="mt-5 space-y-4">{[['name','Your name','text'],['phone','Phone number','tel']].map(([key,label,type])=><label key={key} className="block text-sm font-semibold">{label}<input required type={type} value={form[key]} onChange={(event)=>setForm({...form,[key]:event.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3 outline-none focus:border-rose-400" /></label>)}<label className="block text-sm font-semibold">Service<select value={form.service} onChange={(event)=>setForm({...form,service:event.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-3"><option value="">Select a service</option>{services.map((service,index)=><option key={`${service.caption}-${index}`} value={service.caption}>{service.caption}</option>)}</select></label><label className="block text-sm font-semibold">Preferred date<input required type="date" min={new Date().toISOString().slice(0,10)} value={form.date} onChange={(event)=>setForm({...form,date:event.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3" /></label><label className="block text-sm font-semibold">Write your message<textarea rows={3} value={form.message} onChange={(event)=>setForm({...form,message:event.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3" placeholder="Anything you would like the clinic to know?" /></label>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<button type="submit" className="w-full rounded-xl bg-rose-700 px-4 py-3 font-bold text-white">Request appointment on WhatsApp</button><p className="text-center text-xs text-slate-500">WhatsApp will open with your request ready to send.</p></form></div></div>;
}

export default function SkinCarePublicPage({ place, onShare, onReport, onDelete }) {
  const [appointmentOpen, setAppointmentOpen] = useState(false);
  const [activePhoto, setActivePhoto] = useState(0);
  const [galleryOpen, setGalleryOpen] = useState(false);
  const [listModal, setListModal] = useState(null);
  const [reportOpen, setReportOpen] = useState(false);
  const [reportSent, setReportSent] = useState(false);
  const [reportError, setReportError] = useState('');
  const [menuOpen, setMenuOpen] = useState(false);
  const serviceRow = useRef(null); const doctorRow = useRef(null); const galleryRow = useRef(null); const videoRow = useRef(null); const featureRow = useRef(null);
  const profile = place.attributes?.businessProfile || {}; const common = profile.common || {}; const specific = profile.categorySpecific || {};
  const name = place.name || common.businessName || 'Skin Care Clinic';
  const tagline = place.attributes?.tagline || common.tagline || 'Healthy skin. Expert care. Confidence every day.';
  const cover = place.coverImage || common.coverImage || ''; const logo = place.logo || common.logo || '';
  const phone = place.phone || common.phone || ''; const socials = place.socialLinks || common.socialLinks || {};
  const whatsapp = getWhatsAppUrl(socials.whatsapp || common.whatsapp || phone);
  const address = place.address || '';
  const heroDescription = common.heroDescription || 'Expert dermatology and personalized treatments for healthy, confident skin.';
  const about = specific.aboutDescription || common.about || place.description || `At ${name}, our skin care team combines professional expertise with thoughtful, personalized care.`;
  const aboutImage = specific.aboutImage || cover || '';
  const doctors = (Array.isArray(specific.doctors) ? specific.doctors : []).map((doctor) => typeof doctor === 'string' ? { name: doctor } : doctor).filter((doctor) => doctor?.name);
  const services = (Array.isArray(specific.skinServices) ? specific.skinServices : []).map((service) => typeof service === 'string' ? { caption: service } : service).filter((service) => service?.caption);
  const features = (Array.isArray(specific.keyFeatures) ? specific.keyFeatures : []).filter((feature) => feature?.title);
  const gallery = useMemo(() => (Array.isArray(place.images) && place.images.length ? place.images : common.gallery || []).map(imageOf).filter(Boolean), [place.images, common.gallery]);
  const videos = (Array.isArray(common.videos) ? common.videos : []).map((video) => typeof video === 'string' ? { url: video } : video).filter((video) => video?.url);
  const nav = [['Home','#home'],['About','#about'],['Dermatologists','#dermatologists'],['Services','#services'],['Gallery','#gallery'],['Videos','#videos'],['Reviews','#reviews'],['Contact','#footer']];
  const stepPhoto = (direction) => setActivePhoto((index) => (index + direction + gallery.length) % gallery.length);
  const shareBusiness = () => {
    if (onShare) return onShare();
    if (navigator.share) return navigator.share({ title: name, url: window.location.href });
    return navigator.clipboard?.writeText(window.location.href);
  };
  const reportBusiness = () => onReport ? onReport() : setReportOpen(true);
  const submitReport = async (event) => {
    event.preventDefault();
    setReportError('');
    try {
      await api.post('/reports', { place: place._id, reason: 'incorrect_information', description: 'Reported from the Skin Care business page.' });
      setReportSent(true);
    } catch (error) {
      setReportError(error.response?.data?.message || 'Unable to submit the report. Please sign in and try again.');
    }
  };

  return <div className="min-h-screen bg-white text-slate-900">
    <header className="sticky top-0 z-40 border-b border-rose-100 bg-white/95 shadow-sm backdrop-blur"><div className="relative mx-auto flex h-[72px] max-w-7xl items-center gap-3 px-4 sm:px-6"><a href="#home" className="flex min-w-0 items-center gap-3">{logo ? <img src={logo} alt={`${name} logo`} className="h-11 w-11 rounded-full object-cover"/> : <span className="grid h-11 w-11 place-items-center rounded-full bg-rose-50 text-2xl">✿</span>}<span className="min-w-0"><strong className="block truncate text-sm sm:text-base">{name}</strong><small className="text-xs text-slate-500">Skin Care &amp; Dermatology</small></span></a><nav className="ml-auto hidden items-center gap-5 lg:flex">{nav.map(([label,href])=><a key={label} href={href} className="text-xs font-bold text-slate-600 transition hover:text-rose-700">{label}</a>)}</nav><a href="/" className="ml-auto hidden shrink-0 rounded-full bg-[#12395a] px-4 py-2 text-xs font-bold text-white transition hover:bg-rose-800 sm:inline-flex lg:ml-4">← Back to G-Pages</a><button type="button" onClick={()=>setMenuOpen((open)=>!open)} aria-label="Toggle navigation menu" aria-expanded={menuOpen} className="ml-auto grid h-10 w-10 shrink-0 place-items-center rounded-lg border border-rose-200 text-2xl text-rose-900 sm:hidden">{menuOpen?'×':'☰'}</button>{menuOpen&&<nav aria-label="Skin Care navigation" className="absolute inset-x-0 top-[72px] z-50 border-t border-rose-100 bg-white px-5 py-3 shadow-lg sm:hidden">{nav.map(([label,href])=><a key={label} href={href} onClick={()=>setMenuOpen(false)} className="block border-b border-rose-50 py-3 text-sm font-semibold text-slate-700 last:border-0">{label}</a>)}<a href="/" onClick={()=>setMenuOpen(false)} className="block py-3 text-sm font-bold text-rose-800">← Back to G-Pages</a></nav>}</div></header>
    <main>
      <section id="home" className="relative isolate overflow-hidden bg-[#422638]">{cover && <img src={cover} alt={`${name} clinic`} className="absolute inset-0 -z-20 h-full w-full bg-[#422638] object-contain sm:object-cover"/>}<div className="absolute inset-0 -z-10 bg-[#321a2c]/75 sm:bg-gradient-to-r sm:from-[#321a2c]/95 sm:via-[#633448]/75 sm:to-[#633448]/20"/><div className="mx-auto grid min-h-[440px] max-w-7xl items-center gap-8 px-5 py-12 sm:px-8 lg:grid-cols-[1.15fr_.85fr]"><div className="max-w-2xl text-white"><p className="inline-flex rounded-full border border-white/30 bg-white/10 px-4 py-2 text-xs font-bold uppercase tracking-[.16em] text-rose-100">Dermatology · Skin wellness</p><h1 className="mt-5 text-4xl font-black leading-tight sm:text-6xl">{tagline}</h1><p className="mt-5 max-w-xl text-sm leading-7 text-white/85 sm:text-base">{heroDescription}</p><div className="mt-7 flex flex-wrap gap-3"><button type="button" onClick={()=>document.getElementById('dermatologists')?.scrollIntoView({behavior:'smooth'})} className="rounded-xl bg-white px-6 py-3.5 text-sm font-extrabold text-rose-900">Our specialists</button><button type="button" onClick={()=>setAppointmentOpen(true)} className="rounded-xl bg-rose-600 px-6 py-3.5 text-sm font-extrabold text-white shadow-lg hover:bg-rose-500">Book appointment</button></div><div className="mt-4 flex items-center gap-2"><FavoriteButton placeId={place._id} iconOnly/><button type="button" onClick={shareBusiness} aria-label="Share this business" title="Share" className="grid h-10 w-10 place-items-center rounded-full border border-white/50 bg-white/10 text-white hover:bg-white/20"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className="h-5 w-5" aria-hidden="true"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.7 10.7 6.6-4.4m-6.6 7 6.6 4.4"/></svg></button><button type="button" onClick={reportBusiness} aria-label="Report this business" title="Report" className="grid h-10 w-10 place-items-center rounded-full border border-white/50 bg-white/10 text-white hover:bg-white/20"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className="h-5 w-5" aria-hidden="true"><path d="M4 21V5m0 0c5-4 10 4 16 0v11c-6 4-11-4-16 0"/></svg></button></div></div><div className="hidden justify-end lg:flex">{logo ? <img src={logo} alt="" className="h-40 w-40 rounded-full border-4 border-white/70 bg-white object-cover shadow-2xl"/> : <div className="grid h-40 w-40 place-items-center rounded-full border border-white/50 bg-white/10 text-7xl text-white">✿</div>}</div></div></section>
      <section className="border-b border-rose-100 bg-rose-50"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-rose-200 sm:grid-cols-4">{[['✦','Qualified dermatologists','Experienced skin specialists'],['♡','Personalized care','Plans shaped around your needs'],['✧','Modern treatments','Professional skin care services'],['map','Visit our clinic',address]].map(([icon,title,detail])=><div key={title} className="flex items-center gap-3 px-4 py-5 sm:px-6"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-white text-xl text-rose-700 shadow-sm">{icon === 'map' ? <LocationMapIcon className="h-5 w-5" /> : icon}</span><span><strong className="block text-xs sm:text-sm">{title}</strong>{detail && <small className="mt-1 block text-[10px] leading-4 text-slate-500 sm:text-xs">{detail}</small>}</span></div>)}</div></section>
      <ListSection id="about" eyebrow="A little about us" title="Care that puts your skin first" className="bg-white"><div className="grid items-center gap-8 lg:grid-cols-2">{aboutImage ? <img src={aboutImage} alt={`${name} skin care clinic`} className="h-72 w-full rounded-3xl object-cover shadow-lg sm:h-96"/> : <div className="grid h-72 place-items-center rounded-3xl bg-gradient-to-br from-rose-100 to-amber-50 text-7xl">✿</div>}<div><p className="max-w-prose whitespace-pre-line break-words text-sm leading-8 text-slate-600 sm:text-base [overflow-wrap:anywhere]">{about}</p>{address && <p className="mt-5 flex gap-2 text-sm font-semibold text-rose-800"><LocationMapIcon className="h-5 w-5" />{address}</p>}<button type="button" onClick={()=>setAppointmentOpen(true)} className="mt-6 rounded-xl bg-rose-700 px-5 py-3 text-sm font-bold text-white">Talk to our clinic</button></div></div></ListSection>
      <ListSection id="dermatologists" eyebrow="Meet your care team" title="Our dermatologists" className="bg-rose-50/70"><div className="mb-4 flex justify-end gap-2"><button type="button" aria-label="Scroll dermatologists left" onClick={()=>scrollRow(doctorRow,-1)} className="rounded-full border border-rose-200 bg-white px-4 py-2">‹</button><button type="button" aria-label="Scroll dermatologists right" onClick={()=>scrollRow(doctorRow,1)} className="rounded-full border border-rose-200 bg-white px-4 py-2">›</button></div><div ref={doctorRow} className="hide-scrollbar flex snap-x gap-5 overflow-x-auto scroll-smooth pb-4">{(doctors.length?doctors:[{name:'Our Dermatology Team',qualification:'Qualified skin care professionals',speciality:'Personalized dermatology care',description:'Meet our team to learn about the right care for your skin.'}]).map((doctor,index)=><article key={`${doctor.name}-${index}`} className="flex w-[88%] shrink-0 snap-start flex-col overflow-hidden rounded-3xl border border-rose-100 bg-white shadow-sm sm:w-[70%] md:flex-row"><div className="h-72 bg-rose-100 sm:h-80 md:h-auto md:w-64 md:shrink-0">{imageOf(doctor) ? <img src={imageOf(doctor)} alt={doctor.name} className="h-full w-full object-contain object-top sm:object-cover"/> : <div className="grid h-full min-h-64 place-items-center text-7xl text-rose-300">♙</div>}</div><div className="flex flex-1 flex-col p-6"><p className="text-xs font-bold uppercase tracking-widest text-rose-700">Dermatologist</p><h3 className="mt-2 text-2xl font-extrabold">{doctor.name}</h3><p className="mt-2 text-sm font-bold text-rose-800">{doctor.qualification || doctor.experience || 'Skin care specialist'}</p><p className="mt-1 text-sm text-slate-600">{doctor.speciality || doctor.specialization || 'Dermatology'}</p>{doctor.consultationTimings && <p className="mt-3 flex items-center gap-2 text-sm font-semibold text-rose-800"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className="h-4 w-4 shrink-0"><circle cx="12" cy="12" r="9"/><path strokeLinecap="round" d="M12 7v5l3 2"/></svg><span>Consultation: {doctor.consultationTimings}</span></p>}<p className="mt-4 flex-1 text-sm leading-6 text-slate-600">{doctor.description || 'Providing thoughtful, professional care for your skin health.'}</p><button type="button" onClick={()=>setAppointmentOpen(true)} className="mt-5 self-start rounded-xl bg-rose-700 px-5 py-3 text-sm font-bold text-white">Book consultation</button></div></article>)}</div></ListSection>
      <ListSection id="services" eyebrow="Treatments for your needs" title="Our skin care services" className="bg-white"><div className="mb-4 flex items-center justify-end gap-2"><button type="button" onClick={()=>setListModal('services')} className="mr-auto text-sm font-bold text-rose-800">View all services →</button><button type="button" aria-label="Scroll services left" onClick={()=>scrollRow(serviceRow,-1)} className="rounded-full border border-rose-200 px-4 py-2">‹</button><button type="button" aria-label="Scroll services right" onClick={()=>scrollRow(serviceRow,1)} className="rounded-full border border-rose-200 px-4 py-2">›</button></div><div ref={serviceRow} className="hide-scrollbar flex snap-x gap-4 overflow-x-auto scroll-smooth pb-4">{(services.length?services:[{caption:'Personalized skin consultation',description:'Connect with our clinic to discuss your skin care needs.'}]).map((service,index)=><article key={`${service.caption}-${index}`} className="w-[78%] shrink-0 snap-start overflow-hidden rounded-3xl border border-rose-100 bg-white shadow-sm sm:w-[45%] lg:w-[30%]">{imageOf(service)?<img src={imageOf(service)} alt={service.caption} className="h-48 w-full object-cover"/>:<div className="grid h-48 place-items-center bg-gradient-to-br from-rose-100 to-amber-50 text-5xl text-rose-400">✧</div>}<div className="p-5"><h3 className="font-extrabold">{service.caption}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-slate-600">{service.description || 'Ask our care team about this service and the right next step for you.'}</p><button type="button" onClick={()=>setAppointmentOpen(true)} className="mt-4 text-sm font-bold text-rose-800">Book this service →</button></div></article>)}</div></ListSection>
      <ListSection id="why-us" eyebrow="Thoughtful care, every visit" title="Why choose us?" className="bg-rose-50/70"><p className="-mt-3 text-sm text-slate-600">Professional care with a patient-first approach.</p><div className="mb-4 mt-5 flex items-center justify-end gap-2"><button type="button" onClick={()=>setListModal('features')} className="mr-auto text-sm font-bold text-rose-800">View all →</button><button type="button" aria-label="Scroll features left" onClick={()=>scrollRow(featureRow,-1)} className="rounded-full border border-rose-200 bg-white px-4 py-2">‹</button><button type="button" aria-label="Scroll features right" onClick={()=>scrollRow(featureRow,1)} className="rounded-full border border-rose-200 bg-white px-4 py-2">›</button></div><div ref={featureRow} className="hide-scrollbar flex snap-x gap-4 overflow-x-auto scroll-smooth pb-4">{(features.length?features:[{icon:'♡',title:'Professional care',description:'Care from trained skin care professionals.'},{icon:'✦',title:'Patient-first approach',description:'We listen carefully and explain your options.'},{icon:'✧',title:'Personalized plans',description:'Recommendations tailored to your skin needs.'}]).map((feature,index)=><article key={`${feature.title}-${index}`} className="w-[78%] shrink-0 snap-start rounded-3xl border border-rose-100 bg-white p-6 shadow-sm sm:w-[45%] lg:w-[30%]"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-rose-100 text-2xl text-rose-800">{feature.icon || '✦'}</span><h3 className="mt-4 font-extrabold">{feature.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{feature.description}</p></article>)}</div></ListSection>
      {gallery.length>0 && <ListSection id="gallery" eyebrow="Inside our clinic" title="Photo gallery" className="bg-white"><div className="flex items-center justify-between"><p className="text-sm text-slate-500">A look at our space and skin care services.</p><div className="flex gap-2"><button type="button" aria-label="Previous photo" onClick={()=>scrollRow(galleryRow,-1)} className="rounded-full border border-rose-200 px-4 py-2">‹</button><button type="button" aria-label="Next photo" onClick={()=>scrollRow(galleryRow,1)} className="rounded-full border border-rose-200 px-4 py-2">›</button></div></div><div ref={galleryRow} className="hide-scrollbar mt-4 flex snap-x gap-3 overflow-x-auto scroll-smooth pb-3">{gallery.map((image,index)=><button key={`${image}-${index}`} type="button" onClick={()=>{setActivePhoto(index);setGalleryOpen(true)}} className="w-[78%] shrink-0 snap-start overflow-hidden rounded-2xl sm:w-[42%] lg:w-[25%]"><img src={image} alt={`${name} gallery ${index+1}`} className="h-52 w-full object-cover transition hover:scale-105"/></button>)}</div><div className="mt-2 text-right"><button type="button" onClick={()=>{setActivePhoto(0);setGalleryOpen(true)}} className="text-sm font-bold text-rose-800">View all photos →</button></div></ListSection>}
      {videos.length>0 && <ListSection id="videos" eyebrow="Get to know us" title="Clinic videos" className="bg-rose-50/70"><div className="mb-4 flex justify-end gap-2"><button type="button" aria-label="Scroll videos left" onClick={()=>scrollRow(videoRow,-1)} className="rounded-full border border-rose-200 bg-white px-4 py-2">‹</button><button type="button" aria-label="Scroll videos right" onClick={()=>scrollRow(videoRow,1)} className="rounded-full border border-rose-200 bg-white px-4 py-2">›</button></div><div ref={videoRow} className="hide-scrollbar flex snap-x gap-4 overflow-x-auto scroll-smooth pb-4">{videos.map((video,index)=><div key={`${video.url}-${index}`} className="w-[90%] shrink-0 snap-start sm:w-[65%] lg:w-[48%]"><PublicVideoCard video={video}/></div>)}</div></ListSection>}
      <ListSection id="reviews" eyebrow="Patient experiences" title="Reviews" className="bg-white"><ReviewsSection placeId={place._id}/></ListSection>
      <ListSection id="contact" eyebrow="We are here to help" title={`Contact ${name}`} className="bg-rose-50/70"><div className="grid gap-6 rounded-3xl bg-white p-6 shadow-sm md:grid-cols-2"><div><p className="text-sm leading-7 text-slate-600">{address || 'Contact our clinic for directions and visiting details.'}</p>{phone && <a href={`tel:${phone}`} className="mt-4 flex items-center gap-2 font-bold text-rose-800"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className="h-5 w-5"><path strokeLinecap="round" strokeLinejoin="round" d="M4 5.5A1.5 1.5 0 0 1 5.5 4h2.2a1.5 1.5 0 0 1 1.46 1.16l.56 2.43a1.5 1.5 0 0 1-.75 1.65l-1.4.8a14.1 14.1 0 0 0 6.39 6.39l.8-1.4a1.5 1.5 0 0 1 1.65-.75l2.43.56A1.5 1.5 0 0 1 20 16.3v2.2a1.5 1.5 0 0 1-1.5 1.5H18C10.27 20 4 13.73 4 6v-.5Z"/></svg><span>Call</span></a>}{place.email && <a href={`mailto:${place.email}`} className="mt-3 flex items-center gap-2 text-sm font-semibold text-slate-700"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className="h-5 w-5"><rect x="3" y="5" width="18" height="14" rx="2"/><path strokeLinecap="round" strokeLinejoin="round" d="m4 7 8 6 8-6"/></svg><span>{place.email}</span></a>}{whatsapp && <button type="button" onClick={()=>setAppointmentOpen(true)} className="mt-5 rounded-xl bg-emerald-700 px-5 py-3 text-sm font-bold text-white">Message us on WhatsApp</button>}</div>{address && <iframe title={`${name} location`} src={`https://www.google.com/maps?q=${encodeURIComponent(address)}&output=embed`} className="h-64 w-full rounded-2xl border-0" loading="lazy"/>}</div></ListSection>
    </main>
    <footer id="footer" className="scroll-mt-24 bg-[#321a2c] px-4 py-9 text-white sm:px-6" data-mobile-footer-layout="columns">
      <div className="mx-auto grid max-w-7xl grid-cols-3 gap-3 border-b border-white/15 pb-8 sm:grid-cols-2 sm:gap-8 lg:grid-cols-4">
        <div className="col-span-3 sm:col-span-2 lg:col-span-1">
          <div className="flex items-center gap-3">{logo ? <img src={logo} alt={`${name} logo`} className="h-12 w-12 rounded-full object-cover"/> : <span className="grid h-12 w-12 place-items-center rounded-full bg-white/10 text-2xl">&#x273F;</span>}<strong className="text-lg">{name}</strong></div>

        </div>
        <div className="min-w-0">
          <h3 className="text-sm font-bold">Contact</h3>
          <div className="mt-3 grid gap-3 break-words text-xs text-white/75 sm:text-sm">
            {phone && <a href={`tel:${phone}`} className="flex items-center gap-2 hover:text-white"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className="h-5 w-5 shrink-0"><path strokeLinecap="round" strokeLinejoin="round" d="M4 5.5A1.5 1.5 0 0 1 5.5 4h2.2a1.5 1.5 0 0 1 1.46 1.16l.56 2.43a1.5 1.5 0 0 1-.75 1.65l-1.4.8a14.1 14.1 0 0 0 6.39 6.39l.8-1.4a1.5 1.5 0 0 1 1.65-.75l2.43.56A1.5 1.5 0 0 1 20 16.3v2.2a1.5 1.5 0 0 1-1.5 1.5H18C10.27 20 4 13.73 4 6v-.5Z"/></svg><span>Call</span></a>}
            {whatsapp && <a href={whatsapp} target="_blank" rel="noreferrer" className="flex items-center gap-2 hover:text-white"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className="h-5 w-5 shrink-0"><path strokeLinecap="round" strokeLinejoin="round" d="M20 11.5a8 8 0 0 1-11.9 6.96L4 20l1.55-4.1A8 8 0 1 1 20 11.5Z"/><path strokeLinecap="round" strokeLinejoin="round" d="M9 8.5c.3-.5.55-.5.85-.5.2 0 .4 0 .55.4l.65 1.5c.1.25.1.45-.1.65l-.5.6c.7 1.2 1.4 1.9 2.6 2.5l.55-.55c.2-.2.4-.25.65-.1l1.45.7c.35.15.4.3.35.55-.1.5-.5 1.1-1 1.3-.5.25-1.15.3-2.1-.05-1-.4-2.15-1.1-3.25-2.2-1.05-1.05-1.75-2.3-2.05-3.2-.3-.9-.2-1.55.2-2.1Z"/></svg><span>WhatsApp</span></a>}
            {address && <a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`} target="_blank" rel="noreferrer" className="flex items-start gap-2 hover:text-white"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className="mt-0.5 h-5 w-5 shrink-0"><path strokeLinecap="round" strokeLinejoin="round" d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2.3"/></svg><span>{address}</span></a>}
          </div>
        </div>
        <div className="min-w-0">
          <h3 className="text-sm font-bold">Follow Us</h3>
          <div className="mt-3 grid gap-3 text-xs text-white/75 sm:text-sm">
            {[
              ['instagram', 'Instagram', socials.instagram],
              ['facebook', 'Facebook', socials.facebook],
              ['website', 'Website', getWebsiteUrl(place.website || common.website)],
            ].filter(([, , url]) => url).map(([key, label, url]) => <a key={key} href={url} target="_blank" rel="noreferrer" className="flex items-center gap-2 hover:text-white"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className="h-5 w-5 shrink-0">{key==='website'?<><circle cx="12" cy="12" r="9"/><path strokeLinecap="round" d="M3 12h18M12 3a14 14 0 0 1 0 18M12 3a14 14 0 0 0 0 18"/></>:key==='instagram'?<><rect x="3.5" y="3.5" width="17" height="17" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.8" r=".8" fill="currentColor" stroke="none"/></>:<path fill="currentColor" stroke="none" d="M13.4 21v-8h2.7l.4-3.1h-3.1v-2c0-.9.3-1.5 1.6-1.5h1.7V3.6c-.3 0-1.3-.1-2.5-.1-2.5 0-4.2 1.5-4.2 4.3v2.1H7.2V13H10v8h3.4Z"/>}</svg><span>{label}</span></a>)}
          </div>
        </div>
        <div className="min-w-0"><button type="button" onClick={()=>setAppointmentOpen(true)} className="w-full rounded-xl bg-rose-600 px-2 py-3 text-xs font-bold text-white transition hover:bg-rose-500 sm:w-auto sm:px-5 sm:text-sm">Book appointment</button></div>
      </div>
      <div className="mx-auto mt-5 max-w-7xl text-center text-xs text-white/60">� {new Date().getFullYear()} {name}. All rights reserved.{onShare&&<button type="button" onClick={shareBusiness} className="ml-4">Share</button>}{onReport&&<button type="button" onClick={reportBusiness} className="ml-3">Report listing</button>}{onDelete&&<button type="button" onClick={onDelete} className="ml-3">Delete listing</button>}</div>
    </footer>
    {listModal&&<div role="dialog" aria-modal="true" aria-label={listModal==='services'?'All skin care services':'All clinic features'} className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/70 p-4 sm:p-8"><div className="mx-auto max-w-5xl rounded-3xl bg-white p-5 sm:p-8"><div className="flex items-center justify-between gap-4"><h2 className="text-2xl font-extrabold">{listModal==='services'?'All skin care services':'Why patients choose us'}</h2><button type="button" onClick={()=>setListModal(null)} className="rounded-full border px-4 py-2 font-bold">Close ×</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{(listModal==='services'?(services.length?services:[{caption:'Personalized skin consultation',description:'Connect with our clinic to discuss your skin care needs.'}]):(features.length?features:[{icon:'♡',title:'Professional care',description:'Care from trained skin care professionals.'},{icon:'✦',title:'Patient-first approach',description:'We listen carefully and explain your options.'},{icon:'✧',title:'Personalized plans',description:'Recommendations tailored to your skin needs.'}])).map((item,index)=><article key={`${item.caption||item.title}-${index}`} className="overflow-hidden rounded-2xl border border-rose-100 bg-rose-50/50">{listModal==='services'&&imageOf(item)&&<img src={imageOf(item)} alt={item.caption} className="h-40 w-full object-cover"/>}<div className="p-4">{listModal==='features'&&<span className="text-2xl text-rose-700">{item.icon||'✦'}</span>}<h3 className="mt-1 font-bold">{item.caption||item.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{item.description}</p></div></article>)}</div></div></div>}
    {galleryOpen&&gallery.length>0&&<div role="dialog" aria-modal="true" aria-label="Photo gallery" className="fixed inset-0 z-50 grid place-items-center bg-slate-950/95 p-4"><button type="button" onClick={()=>setGalleryOpen(false)} className="absolute right-5 top-5 rounded-full bg-white px-4 py-2 font-bold">Close ×</button><button type="button" aria-label="Previous photo" onClick={()=>stepPhoto(-1)} className="absolute left-3 rounded-full bg-white/90 px-4 py-3 text-2xl sm:left-8">‹</button><div className="max-w-6xl text-center"><img src={gallery[activePhoto]} alt={`${name} gallery photo ${activePhoto+1}`} className="max-h-[78vh] max-w-full rounded-2xl object-contain"/><p className="mt-3 text-sm text-white">{activePhoto+1} / {gallery.length}</p></div><button type="button" aria-label="Next photo" onClick={()=>stepPhoto(1)} className="absolute right-3 rounded-full bg-white/90 px-4 py-3 text-2xl sm:right-8">›</button></div>}
    {appointmentOpen&&<AppointmentDialog name={name} services={services} onClose={()=>setAppointmentOpen(false)} whatsapp={whatsapp}/>}
    {reportOpen&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4" onMouseDown={(event)=>event.target===event.currentTarget&&setReportOpen(false)}><div role="dialog" aria-modal="true" aria-labelledby="report-title" className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 id="report-title" className="text-xl font-extrabold">Report this business</h2><button type="button" onClick={()=>setReportOpen(false)} aria-label="Close report dialog" className="rounded-full border px-3 py-1">Close</button></div>{reportSent?<div className="mt-5"><p className="text-sm text-slate-700">Thank you. Your report has been submitted.</p><button type="button" onClick={()=>{setReportOpen(false);setReportSent(false)}} className="mt-4 rounded-xl bg-rose-700 px-5 py-3 text-sm font-bold text-white">Done</button></div>:<form onSubmit={submitReport} className="mt-5"><p className="text-sm leading-6 text-slate-600">Tell us if this business listing has incorrect information.</p>{reportError&&<p role="alert" className="mt-3 text-sm text-red-700">{reportError}</p>}<div className="mt-5 flex justify-end gap-3"><button type="button" onClick={()=>setReportOpen(false)} className="rounded-xl border px-4 py-2 text-sm font-semibold">Cancel</button><button type="submit" className="rounded-xl bg-rose-700 px-4 py-2 text-sm font-bold text-white">Submit report</button></div></form>}</div></div>}
  </div>;
}
