import React, { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../../services/api';
import BusinessMediaUploader from '../../components/business/BusinessMediaUploader';
import BusinessVideoUploader from '../../components/business/BusinessVideoUploader';
import LocationCascadeFields from '../../components/LocationCascadeFields';

const inputClass = 'mt-1 w-full rounded-xl border border-[#e7dcd7] bg-white px-3 py-2.5 text-sm outline-none focus:border-[#a83f32]';
const days = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];
const emptyHours = Object.fromEntries(days.map((day) => [day, { open: '', close: '', closed: false }]));
const split = (value) => Array.isArray(value) ? value : String(value || '').split(/[\n,]/).map((item) => item.trim()).filter(Boolean);
const asText = (value) => Array.isArray(value) ? value.map((item) => typeof item === 'string' ? item : item.name || '').filter(Boolean).join('\n') : value || '';
const profileOf = (place) => place.attributes?.businessProfile || {};
const legacyOf = (place) => place.attributes?.restaurantProfile || {};

const configs = {
  restaurant: { title: 'Restaurant Information', fields: [['cuisineType', 'Cuisine Type'], ['foodType', 'Food Type'], ['priceRange', 'Price Range'], ['establishedYear', 'Established Year'], ['aboutRestaurant', 'About Restaurant']], facilities: ['Dine-in', 'Takeaway', 'Delivery', 'Online Ordering', 'Table Reservation', 'Party Hall', 'Birthday Parties', 'Catering', 'Parking', 'AC', 'Wi-Fi', 'Family Dining', 'Outdoor Dining', 'Private Dining', 'Kids Area', 'Live Kitchen'], services: ['Restaurant Services'], itemTitle: 'Daily Menu', itemName: 'Dish Name', offerTitle: 'Special Offers', businessType: 'restaurant' },
  'coffee-shop': { title: 'Coffee Shop Information', fields: [['coffeeTypes', 'Coffee Types'], ['beverages', 'Beverages'], ['tea', 'Tea'], ['snacks', 'Snacks'], ['desserts', 'Desserts'], ['signatureDrinks', 'Signature Drinks']], facilities: ['Wi-Fi', 'Charging', 'AC', 'Parking', 'Pet Friendly', 'Work/Study Friendly'], seating: ['Indoor Seating', 'Outdoor Seating', 'Private Seating'], services: ['Takeaway', 'Delivery', 'Online Ordering'], itemTitle: 'Coffee Menu', itemName: 'Item Name', offerTitle: 'Daily Specials', businessType: 'coffee-shop' },
  bakery: { title: 'Sweet Shop & Bakery Information', fields: [['shopType', 'Shop Type'], ['sweets', 'Sweets'], ['cakes', 'Cakes'], ['bakeryItems', 'Bakery Items'], ['pastries', 'Pastries'], ['snacks', 'Snacks'], ['specialItems', 'Special Items'], ['seasonalProducts', 'Seasonal Products']], services: ['Online Orders', 'Delivery', 'Takeaway', 'Custom Orders'], itemTitle: 'Products', itemName: 'Product Name', offerTitle: 'Daily Specials', businessType: 'bakery' },
  catering: { title: 'Catering Services Information', fields: [['cateringServices', 'Catering Services'], ['cuisineTypes', 'Cuisine Types'], ['eventTypes', 'Event Types'], ['serviceArea', 'Service Areas'], ['guestCapacityMin', 'Minimum Guests'], ['guestCapacityMax', 'Maximum Guests']], services: ['Wedding Catering', 'Corporate Catering', 'Party Catering', 'Outdoor/Event Catering', 'Buffet', 'Live Counters', 'Traditional Catering'], itemTitle: 'Catering Menu', itemName: 'Menu Name', offerTitle: 'Special Offers', businessType: 'catering' },
  'food-processing': { title: 'Food Processing Information', fields: [['industryType', 'Industry Type'], ['products', 'Products'], ['productCategories', 'Product Categories'], ['processingTypes', 'Processing Types'], ['manufacturingInformation', 'Manufacturing Information'], ['productionCapacity', 'Production Capacity'], ['manufacturingFacilities', 'Manufacturing Facilities'], ['processingFacilities', 'Processing Facilities'], ['packagingFacilities', 'Packaging Facilities'], ['storageFacilities', 'Storage Facilities'], ['qualityControlFacilities', 'Quality Control Facilities'], ['certifications', 'Certifications'], ['qualityStandards', 'Quality Standards'], ['safetyStandards', 'Safety Standards'], ['complianceInformation', 'Compliance Information'], ['distribution', 'Distribution'], ['industriesServed', 'Industries Served'], ['serviceAreas', 'Service Areas']], services: ['Wholesale', 'Distribution', 'Private Label', 'Bulk Orders'], itemTitle: 'Products', itemName: 'Product Name', offerTitle: null, businessType: 'food-processing' },
};

function TextField({ label, value, onChange, multiline = false }) {
  return <label className="block text-sm font-medium text-[#4b3d3b]">{label}{multiline ? <textarea rows={3} value={value || ''} onChange={(event) => onChange(event.target.value)} className={inputClass} /> : <input value={value || ''} onChange={(event) => onChange(event.target.value)} className={inputClass} />}</label>;
}

function CheckList({ title, options, values, onChange }) {
  return <div><h3 className="text-sm font-semibold text-[#4b3d3b]">{title}</h3><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{options.map((option) => <label key={option} className="flex items-center gap-2 rounded-lg border border-[#ebded8] bg-[#fffaf8] px-3 py-2 text-sm"><input type="checkbox" checked={values.includes(option)} onChange={() => onChange(values.includes(option) ? values.filter((item) => item !== option) : [...values, option])} />{option}</label>)}</div></div>;
}

function ItemEditor({ title, nameLabel, items, onChange }) {
  const blank = { name: '', category: '', description: '', price: '', dietary: '', image: '' };
  const updateItem = (index, field, value) => onChange(items.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item));
  return <section className="rounded-[24px] border border-[#ebded8] bg-white p-5 sm:p-7"><div className="flex items-center justify-between gap-3"><h2 className="font-display text-2xl font-semibold">{title}</h2><button type="button" onClick={() => onChange([...items, { ...blank }])} className="rounded-lg bg-[#a83f32] px-3 py-2 text-sm font-semibold text-white">+ Add {nameLabel}</button></div>{items.length === 0 && <p className="mt-4 text-sm text-[#776763]">No items added yet.</p>}<div className="mt-5 space-y-4">{items.map((item, index) => <div key={`${item.name}-${index}`} className="rounded-xl border border-[#ebded8] bg-[#fffaf8] p-4"><div className="grid gap-3 md:grid-cols-2"><TextField label={nameLabel} value={item.name} onChange={(value) => updateItem(index, 'name', value)} /><TextField label="Category" value={item.category} onChange={(value) => updateItem(index, 'category', value)} /><TextField label="Description" value={item.description} onChange={(value) => updateItem(index, 'description', value)} multiline /><TextField label="Price / Per Plate" value={item.price} onChange={(value) => updateItem(index, 'price', value)} /><TextField label="Veg / Non-Veg / Both" value={item.dietary} onChange={(value) => updateItem(index, 'dietary', value)} /><BusinessMediaUploader label={`${nameLabel} Image`} value={item.image} onChange={(value) => updateItem(index, 'image', value)} previewClassName="h-28" /></div><button type="button" onClick={() => onChange(items.filter((_, itemIndex) => itemIndex !== index))} className="mt-3 text-sm font-semibold text-red-600">Remove</button></div>)}</div></section>;
}

function OfferEditor({ title, offers, onChange }) {
  const update = (index, field, value) => onChange(offers.map((offer, offerIndex) => offerIndex === index ? { ...offer, [field]: value } : offer));
  return <section className="rounded-[24px] border border-[#ebded8] bg-white p-5 sm:p-7"><div className="flex items-center justify-between gap-3"><h2 className="font-display text-2xl font-semibold">{title}</h2><button type="button" onClick={() => onChange([...offers, { title: '', description: '', validity: '', discount: '', image: '' }])} className="rounded-lg bg-[#a83f32] px-3 py-2 text-sm font-semibold text-white">+ Add Offer</button></div>{offers.map((offer, index) => <div key={`${offer.title}-${index}`} className="mt-4 rounded-xl border border-[#ebded8] bg-[#fffaf8] p-4"><div className="grid gap-3 md:grid-cols-2"><TextField label="Offer Title" value={offer.title} onChange={(value) => update(index, 'title', value)} /><TextField label="Validity" value={offer.validity} onChange={(value) => update(index, 'validity', value)} /><TextField label="Offer Description" value={offer.description} onChange={(value) => update(index, 'description', value)} multiline /><TextField label="Price / Discount" value={offer.discount} onChange={(value) => update(index, 'discount', value)} /><BusinessMediaUploader label="Offer Image" value={offer.image} onChange={(value) => update(index, 'image', value)} previewClassName="h-28" /></div><button type="button" onClick={() => onChange(offers.filter((_, offerIndex) => offerIndex !== index))} className="mt-3 text-sm font-semibold text-red-600">Remove</button></div>)}</section>;
}

export default function FoodBusinessEditor({ place, businessType, create = false, onBack }) {
  const navigate = useNavigate();
  const config = configs[businessType];
  const profile = profileOf(place || {});
  const legacy = legacyOf(place || {});
  const common = profile.common || legacy.common || {};
  const specific = profile.categorySpecific || legacy.categorySpecific || {};
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const [location, setLocation] = useState({ state: place?.location?.state?._id || '', district: place?.location?.district?._id || '', city: place?.location?.city?._id || '', area: place?.location?.area?._id || '' });
  const [form, setForm] = useState(() => ({
    name: place?.name || '', description: place?.description || common.about || '', phone: place?.phone || common.phone || '', whatsapp: place?.socialLinks?.whatsapp || common.socialMedia?.whatsapp || '', email: place?.email || common.email || '', website: place?.website || common.website || '', logo: place?.logo || common.logo || '', coverImage: place?.coverImage || common.coverImage || '', gallery: place?.images || common.gallery || [], videos: Array.isArray(common.videos) ? common.videos : [], address: place?.address || common.address || '', pincode: common.pincode || '', hours: Array.isArray(place?.workingHours) ? place.workingHours.reduce((all, item) => ({ ...all, [item.day]: item }), { ...emptyHours }) : { ...emptyHours }, social: { ...(place?.socialLinks || {}), ...(common.socialMedia || {}) }, facilities: split(specific.infrastructure || specific.facilities), services: split(specific.services), specific: Object.fromEntries(config.fields.map(([key]) => [key, Array.isArray(specific[key]) ? specific[key].join('\n') : specific[key] || ''])), items: Array.isArray(specific.menuItems) ? specific.menuItems : (Array.isArray(specific.productsList) ? specific.productsList : []), offers: Array.isArray(specific.offers) ? specific.offers : (Array.isArray(specific.specialOffersList) ? specific.specialOffersList : []), specialOffers: specific.specialOffers || '' }));
  const setField = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  const setSpecific = (field, value) => setForm((current) => ({ ...current, specific: { ...current.specific, [field]: value } }));
  const save = async (event) => {
    event.preventDefault(); setSaving(true); setError(''); setMessage('');
    const categorySpecific = { ...specific, ...Object.fromEntries(Object.entries(form.specific).map(([key, value]) => [key, split(value)])), services: form.services, infrastructure: form.facilities, menuItems: form.items, offers: form.offers, specialOffers: form.specialOffers };
    try {
      const payload = { name: form.name, category: place.category?._id || place.category, subcategory: place.subcategory?._id || place.subcategory || undefined, address: form.address || place.address, description: form.description, phone: form.phone || undefined, email: form.email || undefined, website: form.website || undefined, logo: form.logo || undefined, coverImage: form.coverImage || undefined, images: form.gallery.slice(0, 10), services: form.services, facilities: form.facilities, socialLinks: { ...form.social, whatsapp: form.whatsapp || undefined }, workingHours: days.map((day) => ({ day, ...(form.hours[day] || {}) })), location, attributes: { ...(place?.attributes || {}), businessProfile: { ...profile, businessType: config.businessType, common: { ...common, businessName: form.name, about: form.description, logo: form.logo, coverImage: form.coverImage, gallery: form.gallery.slice(0, 10), videos: form.videos, socialMedia: { ...form.social, whatsapp: form.whatsapp }, openingHours: days.map((day) => ({ day, ...(form.hours[day] || {}) })) }, categorySpecific } } };
      if (create) await api.post('/places', payload);
      else await api.put(`/places/${place._id}`, payload);
      setMessage(create ? 'Business submitted and sent for approval.' : 'Business updated successfully.');
      if (create) setTimeout(() => navigate('/business/dashboard'), 1000);
    } catch (saveError) { setError(saveError.response?.data?.message || saveError.message || 'Unable to save this business.'); } finally { setSaving(false); }
  };
  const itemTitle = config.itemTitle;
  const pageTitle = `${create ? 'Add' : 'Edit'} ${businessType === 'restaurant' ? 'Restaurant' : businessType === 'coffee-shop' ? 'Coffee Shop' : businessType === 'bakery' ? 'Sweet Shop & Bakery' : businessType === 'catering' ? 'Catering Service' : 'Food Processing Business'}`;
  const title = pageTitle;
  return <div className="min-h-screen bg-[#f4efed] px-5 py-10 text-[#2d2323] sm:px-8"><div className="mx-auto max-w-5xl"><button type="button" onClick={() => navigate('/business/dashboard')} className="text-sm font-semibold text-[#a83f32]">← Back to Dashboard</button><h1 className="mt-4 font-display text-4xl font-semibold">{title}</h1>{error && <p className="mt-4 rounded-xl bg-[#fff1f0] p-3 text-sm text-[#a83f32]">{error}</p>}{message && <p className="mt-4 rounded-xl bg-[#edf9f1] p-3 text-sm text-[#2f5a3f]">{message}</p>}<form onSubmit={save} className="mt-8 space-y-6">
    <section className="rounded-[24px] border border-[#ebded8] bg-white p-5 sm:p-7"><h2 className="font-display text-2xl font-semibold">Business Information</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><TextField label="Business Name" value={form.name} onChange={(value) => setField('name', value)} /><TextField label="Business Description / About" value={form.description} onChange={(value) => setField('description', value)} multiline /><TextField label="Phone" value={form.phone} onChange={(value) => setField('phone', value)} /><TextField label="WhatsApp" value={form.whatsapp} onChange={(value) => setField('whatsapp', value)} /><TextField label="Email" value={form.email} onChange={(value) => setField('email', value)} /><TextField label="Website" value={form.website} onChange={(value) => setField('website', value)} /><BusinessMediaUploader label="Business Logo" value={form.logo} onChange={(value) => setField('logo', value)} placeId={place._id} previewClassName="h-32" /><BusinessMediaUploader label="Cover / Banner" value={form.coverImage} onChange={(value) => setField('coverImage', value)} placeId={place._id} previewClassName="h-40" /></div></section>
    <section className="rounded-[24px] border border-[#ebded8] bg-white p-5 sm:p-7"><h2 className="font-display text-2xl font-semibold">Location</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><TextField label="Address" value={form.address || place.address} onChange={(value) => setField('address', value)} /><TextField label="Pincode" value={form.pincode} onChange={(value) => setField('pincode', value)} /><div className="col-span-2 grid gap-4 md:grid-cols-2"><LocationCascadeFields value={location} onChange={setLocation} /></div></div></section>
    <section className="rounded-[24px] border border-[#ebded8] bg-white p-5 sm:p-7"><h2 className="font-display text-2xl font-semibold">Business Hours</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{days.map((day) => <div key={day} className="rounded-xl border border-[#ebded8] p-3"><div className="mb-2 flex justify-between text-sm font-semibold capitalize"><span>{day}</span><label className="font-normal"><input type="checkbox" checked={Boolean(form.hours[day]?.closed)} onChange={(event) => setField('hours', { ...form.hours, [day]: { ...(form.hours[day] || {}), closed: event.target.checked } })} /> Closed</label></div><div className="grid grid-cols-2 gap-2"><input type="time" value={form.hours[day]?.open || ''} onChange={(event) => setField('hours', { ...form.hours, [day]: { ...(form.hours[day] || {}), open: event.target.value } })} className={inputClass} /><input type="time" value={form.hours[day]?.close || ''} onChange={(event) => setField('hours', { ...form.hours, [day]: { ...(form.hours[day] || {}), close: event.target.value } })} className={inputClass} /></div></div>)}</div></section>
    <section className="rounded-[24px] border border-[#ebded8] bg-white p-5 sm:p-7"><h2 className="font-display text-2xl font-semibold">Social Media</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{['instagram', 'facebook', 'youtube', 'linkedin', 'twitter'].map((key) => <TextField key={key} label={key} value={form.social[key]} onChange={(value) => setField('social', { ...form.social, [key]: value })} />)}</div></section>
    <section className="rounded-[24px] border border-[#ebded8] bg-white p-5 sm:p-7"><h2 className="font-display text-2xl font-semibold">{title}</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{config.fields.map(([key, label]) => <TextField key={key} label={label} value={form.specific[key]} onChange={(value) => setSpecific(key, value)} multiline />)}</div>{config.facilities && <div className="mt-6"><CheckList title="Café Facilities" options={config.facilities} values={form.facilities} onChange={(values) => setField('facilities', values)} /></div>}{config.seating && <div className="mt-6"><CheckList title="Seating Options" options={config.seating} values={form.facilities} onChange={(values) => setField('facilities', values)} /></div>}{config.services && <div className="mt-6"><CheckList title="Services" options={config.services} values={form.services} onChange={(values) => setField('services', values)} /></div>}</section>
    {itemTitle && <ItemEditor title={itemTitle} nameLabel={config.itemName} items={form.items} onChange={(items) => setField('items', items)} />}
    {config.offerTitle && <OfferEditor title={config.offerTitle} offers={form.offers} onChange={(offers) => setField('offers', offers)} />}
    <section className="rounded-[24px] border border-[#ebded8] bg-white p-5 sm:p-7"><BusinessMediaUploader label="Gallery" helpText="Maximum 10 images." value={form.gallery} onChange={(value) => setField('gallery', value)} placeId={place._id} multiple max={10} previewClassName="h-28" /></section>
    <section className="rounded-[24px] border border-[#ebded8] bg-white p-5 sm:p-7"><h2 className="font-display text-2xl font-semibold">Video Gallery</h2><div className="mt-5"><BusinessVideoUploader label="Videos" value={form.videos} onChange={(value) => setField('videos', value)} placeId={place._id} /></div></section>
    <div className="flex justify-end gap-3"><button type="button" onClick={() => navigate('/business/dashboard')} className="rounded-xl border border-[#e7dcd7] bg-white px-4 py-2.5 text-sm font-semibold">Cancel</button><button type="submit" disabled={saving} className="rounded-xl bg-[#a83f32] px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{saving ? 'Saving...' : 'Save changes'}</button></div>
  </form></div></div>;
}
