import React, { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../../services/api';
import BusinessMediaUploader from '../../components/business/BusinessMediaUploader';
import LocationCascadeFields from '../../components/LocationCascadeFields';

const inputClass = 'mt-1 w-full rounded-xl border border-[#ead9df] bg-white px-3 py-2.5 text-sm outline-none focus:border-[#941f43]';
const days = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];
const emptyHours = Object.fromEntries(days.map((day) => [day, { open: '', close: '', closed: false }]));
const split = (value) => Array.isArray(value) ? value : String(value || '').split(/[\n,]/).map((item) => item.trim()).filter(Boolean);
const weddingNames = ['Marriage Bureaus', 'Function Halls', 'Event Organizers', 'Catering Services', 'Flower Decoration', 'Fashion Designers', 'Beauty Parlours', 'Saloon & Spa'];
const typeNames = { 'Marriage Bureaus': 'marriage-bureau', 'Function Halls': 'function-hall', 'Event Organizers': 'event-organizer', 'Catering Services': 'catering-service', 'Flower Decoration': 'flower-decoration', 'Fashion Designers': 'fashion-designer', 'Beauty Parlours': 'beauty-parlour', 'Saloon & Spa': 'saloon-spa' };
const configs = {
  'marriage-bureau': { title: 'Marriage Bureau', fields: [['yearsExperience', 'Years of Experience'], ['serviceArea', 'Service Area']], checks: ['Matrimonial Registration', 'Profile Matching', 'Horoscope Matching', 'Family Consultation', 'Personalized Matchmaking', 'Online Matrimony', 'Offline Matrimony', 'NRI Matrimony', 'Community Matrimony', 'Second Marriage', 'Wedding Assistance'], extras: ['Membership Available', 'Enable Success Stories'] },
  'function-hall': { title: 'Function Hall', fields: [['venueType', 'Venue Type'], ['minCapacity', 'Minimum Capacity'], ['maxCapacity', 'Maximum Capacity'], ['cateringAvailable', 'Catering Available'], ['externalCatering', 'External Catering Allowed'], ['decorationAvailable', 'Decoration Available'], ['bookingRequired', 'Advance Booking Required'], ['startingPrice', 'Starting Price'], ['hallRentalPrice', 'Hall Rental Price'], ['packagePrice', 'Package Price']], checks: ['Air Conditioning', 'Parking', 'Generator', 'Power Backup', 'Stage', 'Bridal Room', 'Groom Room', 'Dining Hall', 'Kitchen', 'Sound System', 'Lighting', 'Decoration', 'WiFi', 'Lift', 'Security', 'CCTV'], lists: ['halls'] },
  'event-organizer': { title: 'Event Organizer', fields: [['yearsExperience', 'Years of Experience'], ['eventsCompleted', 'Events Completed']], checks: ['Weddings', 'Engagements', 'Receptions', 'Birthdays', 'Anniversaries', 'Corporate Events', 'Baby Showers', 'Naming Ceremonies', 'Religious Events', 'Private Events', 'Event Planning', 'Wedding Planning', 'Venue Management', 'Decoration', 'Catering Coordination', 'Photography Coordination', 'Entertainment', 'Guest Management', 'Invitation Management', 'Vendor Management', 'Transportation', 'Stage Design'], lists: ['packages', 'portfolio'] },
  'catering-service': { title: 'Catering Service', fields: [['yearsExperience', 'Years of Experience'], ['serviceArea', 'Service Area']], checks: ['South Indian', 'North Indian', 'Andhra', 'Telangana', 'Tamil', 'Kerala', 'Chinese', 'Continental', 'Traditional', 'Desserts', 'Snacks', 'Vegetarian', 'Non-Vegetarian', 'Jain', 'Vegan', 'Breakfast', 'Lunch', 'Dinner', 'Buffet', 'Full Meals', 'Corporate Catering', 'Wedding Catering', 'Function Catering', 'Outdoor Catering', 'Live Counters', 'Waiter Service', 'Decoration Support'], lists: ['menuItems', 'packages'] },
  'flower-decoration': { title: 'Flower Decoration', fields: [['yearsExperience', 'Years of Experience'], ['decorationStyle', 'Decoration Style']], checks: ['Wedding Decoration', 'Stage Decoration', 'Mandap Decoration', 'Reception Decoration', 'Entrance Decoration', 'Floral Backdrop', 'Table Decoration', 'Car Decoration', 'Bridal Room Decoration', 'Flower Arrangements', 'Roses', 'Jasmine', 'Marigold', 'Lotus', 'Orchids', 'Artificial Flowers', 'Mixed Flowers'], lists: ['packages'] },
  'fashion-designer': { title: 'Fashion Designer', fields: [['yearsExperience', 'Years of Experience'], ['specialization', 'Designer Specialization']], checks: ['Bridal Wear', 'Groom Wear', 'Sarees', 'Lehengas', 'Sherwanis', 'Suits', 'Reception Wear', 'Engagement Wear', 'Party Wear', 'Traditional Wear', 'Custom Design', 'Stitching', 'Alterations', 'Bridal Styling', 'Groom Styling', 'Custom Measurements', 'Rental Available'], lists: ['collections'] },
  'beauty-parlour': { title: 'Beauty Parlour', fields: [['yearsExperience', 'Years of Experience']], checks: ['Bridal Makeup', 'Party Makeup', 'Engagement Makeup', 'Hair Styling', 'Hair Cut', 'Hair Color', 'Facial', 'Cleanup', 'Waxing', 'Threading', 'Manicure', 'Pedicure', 'Mehendi', 'Pre-Bridal Services', 'Draping'], lists: ['packages'] },
  'saloon-spa': { title: 'Saloon & Spa', fields: [['yearsExperience', 'Years of Experience'], ['membershipDescription', 'Membership Description'], ['membershipPrice', 'Membership Price']], checks: ['Hair Cut', 'Hair Styling', 'Hair Color', 'Hair Spa', 'Beard Styling', 'Grooming', 'Facial', 'Cleanup', 'Waxing', 'Threading', 'Manicure', 'Pedicure', 'Body Massage', 'Head Massage', 'Aromatherapy', 'Relaxation Therapy', 'Spa Treatments', 'Bridal Package', 'Groom Package', 'Couple Package'], lists: [] },
};

function Field({ label, value, onChange, multiline = false, required = false }) { return <label className="block text-sm font-medium text-[#5a3742]">{label}{multiline ? <textarea required={required} rows={3} value={value || ''} onChange={(event) => onChange(event.target.value)} className={inputClass} /> : <input required={required} value={value || ''} onChange={(event) => onChange(event.target.value)} className={inputClass} />}</label>; }
function Checks({ values, options, onChange }) { return <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{options.map((item) => <label key={item} className="flex items-center gap-2 rounded-lg border border-[#ead9df] bg-[#fff8fa] px-3 py-2 text-sm"><input type="checkbox" checked={values.includes(item)} onChange={() => onChange(values.includes(item) ? values.filter((value) => value !== item) : [...values, item])} />{item}</label>)}</div>; }
function DynamicList({ title, items, onChange, imageLabel = 'Image' }) { const blank = { name: '', description: '', category: '', price: '', image: '' }; const update = (index, key, value) => onChange(items.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item)); return <section><div className="flex items-center justify-between gap-3"><h3 className="font-display text-xl font-semibold text-[#4b1227]">{title}</h3><button type="button" onClick={() => onChange([...items, { ...blank }])} className="rounded-lg bg-[#941f43] px-3 py-2 text-sm font-semibold text-white">+ Add</button></div>{items.length === 0 && <p className="mt-3 text-sm text-[#8c6b75]">No items added yet.</p>}{items.map((item, index) => <div key={`${item.name}-${index}`} className="mt-4 rounded-xl border border-[#ead9df] bg-[#fff8fa] p-4"><div className="grid gap-3 md:grid-cols-2"><Field label="Name" value={item.name} onChange={(value) => update(index, 'name', value)} /><Field label="Category" value={item.category} onChange={(value) => update(index, 'category', value)} /><Field label="Description" value={item.description} onChange={(value) => update(index, 'description', value)} multiline /><Field label="Price" value={item.price} onChange={(value) => update(index, 'price', value)} /><BusinessMediaUploader label={imageLabel} value={item.image} onChange={(value) => update(index, 'image', value)} previewClassName="h-28" /></div><button type="button" onClick={() => onChange(items.filter((_, itemIndex) => itemIndex !== index))} className="mt-3 text-sm font-semibold text-red-700">Delete</button></div>)}</section>; }

export default function WeddingBusinessForm({ place = null, businessType, categoryId, subcategoryId, onBack }) {
  const navigate = useNavigate(); const config = configs[businessType]; const isEdit = Boolean(place?._id); const profile = place?.attributes?.businessProfile || {}; const legacy = place?.attributes?.restaurantProfile || {}; const common = profile.common || legacy.common || {}; const specific = profile.categorySpecific || legacy.categorySpecific || {};
  const [step, setStep] = useState(1); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [location, setLocation] = useState({ state: place?.location?.state?._id || '', district: place?.location?.district?._id || '', city: place?.location?.city?._id || '', area: place?.location?.area?._id || '' });
  const [form, setForm] = useState({ name: place?.name || '', tagline: common.tagline || '', description: place?.description || common.about || '', phone: place?.phone || common.phone || '', alternatePhone: common.alternatePhone || '', whatsapp: place?.socialLinks?.whatsapp || common.socialMedia?.whatsapp || '', email: place?.email || common.email || '', website: place?.website || common.website || '', logo: place?.logo || common.logo || '', coverImage: place?.coverImage || common.coverImage || '', gallery: place?.images || common.gallery || [], hours: Array.isArray(place?.workingHours) ? place.workingHours.reduce((all, item) => ({ ...all, [item.day]: item }), { ...emptyHours }) : { ...emptyHours }, social: { ...(place?.socialLinks || {}), ...(common.socialMedia || {}) }, fields: Object.fromEntries(config.fields.map(([key]) => [key, Array.isArray(specific[key]) ? specific[key].join('\n') : specific[key] || ''])), checks: split(specific.services || specific.selectedOptions), packages: Array.isArray(specific.packages) ? specific.packages : [], portfolio: Array.isArray(specific.portfolio) ? specific.portfolio : [], menuItems: Array.isArray(specific.menuItems) ? specific.menuItems : [], collections: Array.isArray(specific.collections) ? specific.collections : [] });
  const setField = (key, value) => setForm((current) => ({ ...current, [key]: value })); const setNested = (key, value) => setForm((current) => ({ ...current, fields: { ...current.fields, [key]: value } }));
  const save = async (event) => { event.preventDefault(); if (!form.name.trim() || !form.phone.trim() || !form.description.trim() || !location.state || !location.city) { setError('Business name, phone, description, state and city are required.'); setStep(1); return; } setSaving(true); setError(''); setMessage(''); const categorySpecific = { ...specific, ...Object.fromEntries(Object.entries(form.fields).map(([key, value]) => [key, split(value)])), services: form.checks, selectedOptions: form.checks, packages: form.packages, portfolio: form.portfolio, menuItems: form.menuItems, collections: form.collections }; const payload = { name: form.name, category: categoryId || place?.category?._id || place?.category, subcategory: subcategoryId || place?.subcategory?._id || place?.subcategory || undefined, address: form.address || place?.address, description: form.description, phone: form.phone, email: form.email || undefined, website: form.website || undefined, logo: form.logo || undefined, coverImage: form.coverImage || undefined, images: form.gallery.slice(0, 10), services: form.checks, facilities: [], socialLinks: { ...form.social, whatsapp: form.whatsapp || undefined }, workingHours: days.map((day) => ({ day, ...(form.hours[day] || {}) })), location, attributes: { ...(place?.attributes || {}), businessProfile: { ...profile, businessType, common: { ...common, businessName: form.name, tagline: form.tagline, about: form.description, logo: form.logo, coverImage: form.coverImage, gallery: form.gallery.slice(0, 10), alternatePhone: form.alternatePhone, socialMedia: { ...form.social, whatsapp: form.whatsapp }, openingHours: days.map((day) => ({ day, ...(form.hours[day] || {}) })) }, categorySpecific } } }; try { if (isEdit) await api.put(`/places/${place._id}`, payload); else await api.post('/places', payload); setMessage(isEdit ? 'Wedding business updated successfully.' : 'Wedding business submitted for approval.'); if (!isEdit) setTimeout(() => navigate('/business/dashboard'), 1000); } catch (saveError) { setError(saveError.response?.data?.message || saveError.message || 'Unable to save this business.'); } finally { setSaving(false); } };
  const title = `${isEdit ? 'Edit' : 'Add'} ${config.title}`; const steps = ['Business', 'Contact', 'Details', 'Services', 'Packages', 'Gallery', 'Social', 'Preview'];
  return <div className="min-h-screen bg-[#fff8fa] px-5 py-10 text-[#351b25] sm:px-8"><div className="mx-auto max-w-5xl"><button type="button" onClick={onBack || (() => navigate('/business/dashboard'))} className="text-sm font-semibold text-[#941f43]">← Back</button><h1 className="mt-4 font-display text-4xl font-bold text-[#4b1227]">{title}</h1><div className="mt-5 flex flex-wrap gap-2">{steps.map((item, index) => <button key={item} type="button" onClick={() => setStep(index + 1)} className={`rounded-full px-3 py-1.5 text-xs font-bold ${step === index + 1 ? 'bg-[#941f43] text-white' : 'bg-[#f7e9ee] text-[#701d38]'}`}>{index + 1} {item}</button>)}</div>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message && <p className="mt-4 rounded-xl bg-green-50 p-3 text-sm text-green-700">{message}</p>}<form onSubmit={save} className="mt-6 space-y-6">
    {step === 1 && <section className="rounded-[24px] border border-[#ead9df] bg-white p-5 shadow-sm sm:p-7"><h2 className="font-display text-2xl font-semibold">Business Information</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Business Name" value={form.name} onChange={(value) => setField('name', value)} required /><Field label="Short Tagline" value={form.tagline} onChange={(value) => setField('tagline', value)} /><Field label="Business Description" value={form.description} onChange={(value) => setField('description', value)} multiline required /><BusinessMediaUploader label="Business Logo" value={form.logo} onChange={(value) => setField('logo', value)} placeId={place?._id} previewClassName="h-32" /><BusinessMediaUploader label="Cover Image" value={form.coverImage} onChange={(value) => setField('coverImage', value)} placeId={place?._id} previewClassName="h-40" /></div></section>}
    {step === 2 && <section className="rounded-[24px] border border-[#ead9df] bg-white p-5 shadow-sm sm:p-7"><h2 className="font-display text-2xl font-semibold">Contact & Location</h2><div className="grid gap-4 md:grid-cols-2"><Field label="Phone Number" value={form.phone} onChange={(value) => setField('phone', value)} required /><Field label="Alternate Phone" value={form.alternatePhone} onChange={(value) => setField('alternatePhone', value)} /><Field label="WhatsApp" value={form.whatsapp} onChange={(value) => setField('whatsapp', value)} /><Field label="Email" value={form.email} onChange={(value) => setField('email', value)} /><Field label="Website" value={form.website} onChange={(value) => setField('website', value)} /><Field label="Address" value={form.address || place?.address} onChange={(value) => setField('address', value)} required /><div className="col-span-2"><LocationCascadeFields value={location} onChange={setLocation} /></div></div></section>}
    {step === 3 && <section className="rounded-[24px] border border-[#ead9df] bg-white p-5 shadow-sm sm:p-7"><h2 className="font-display text-2xl font-semibold">{config.title} Details</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{config.fields.map(([key, label]) => <Field key={key} label={label} value={form.fields[key]} onChange={(value) => setNested(key, value)} multiline={label.toLowerCase().includes('about') || label.toLowerCase().includes('description')} />)}</div>{config.checks && <div className="mt-6"><h3 className="font-semibold">Services & Options</h3><div className="mt-3"><Checks values={form.checks} options={config.checks} onChange={(values) => setField('checks', values)} /></div></div>}</section>}
    {step === 4 && <section className="rounded-[24px] border border-[#ead9df] bg-white p-5 shadow-sm sm:p-7"><h2 className="font-display text-2xl font-semibold">Services</h2><Checks values={form.checks} options={config.checks || []} onChange={(values) => setField('checks', values)} /></section>}
    {step === 5 && <section className="rounded-[24px] border border-[#ead9df] bg-white p-5 shadow-sm sm:p-7 space-y-8"><DynamicList title="Packages" items={form.packages} onChange={(items) => setField('packages', items)} />{businessType === 'catering-service' && <DynamicList title="Menu" items={form.menuItems} onChange={(items) => setField('menuItems', items)} />}{businessType === 'event-organizer' && <DynamicList title="Portfolio" items={form.portfolio} onChange={(items) => setField('portfolio', items)} />}{businessType === 'fashion-designer' && <DynamicList title="Collections" items={form.collections} onChange={(items) => setField('collections', items)} />}</section>}
    {step === 6 && <section className="rounded-[24px] border border-[#ead9df] bg-white p-5 shadow-sm sm:p-7"><BusinessMediaUploader label="Wedding Gallery" helpText="Add up to 10 images." value={form.gallery} onChange={(value) => setField('gallery', value)} placeId={place?._id} multiple max={10} previewClassName="h-32" /></section>}
    {step === 7 && <section className="rounded-[24px] border border-[#ead9df] bg-white p-5 shadow-sm sm:p-7"><h2 className="font-display text-2xl font-semibold">Social Media & Business Hours</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{['facebook', 'instagram', 'youtube', 'linkedin'].map((key) => <Field key={key} label={key} value={form.social[key]} onChange={(value) => setField('social', { ...form.social, [key]: value })} />)}</div><div className="mt-6 grid gap-3 md:grid-cols-2">{days.map((day) => <div key={day} className="rounded-xl border border-[#ead9df] p-3"><div className="flex justify-between text-sm font-semibold capitalize"><span>{day}</span><label className="font-normal"><input type="checkbox" checked={Boolean(form.hours[day]?.closed)} onChange={(event) => setField('hours', { ...form.hours, [day]: { ...(form.hours[day] || {}), closed: event.target.checked } })} /> Closed</label></div><div className="mt-2 grid grid-cols-2 gap-2"><input type="time" value={form.hours[day]?.open || ''} onChange={(event) => setField('hours', { ...form.hours, [day]: { ...(form.hours[day] || {}), open: event.target.value } })} className={inputClass} /><input type="time" value={form.hours[day]?.close || ''} onChange={(event) => setField('hours', { ...form.hours, [day]: { ...(form.hours[day] || {}), close: event.target.value } })} className={inputClass} /></div></div>)}</div></section>}
    {step === 8 && <section className="rounded-[24px] border border-[#ead9df] bg-white p-5 shadow-sm sm:p-7"><h2 className="font-display text-2xl font-semibold">Preview Website</h2><p className="mt-3 text-sm text-[#8c6b75]">Your saved data will appear on the business-owned wedding website after submission.</p><div className="mt-5 rounded-xl bg-[#4b1227] p-6 text-white"><p className="text-xs uppercase tracking-[0.2em] text-[#f4dca9]">{config.title}</p><h3 className="mt-2 font-display text-3xl font-bold">{form.name || 'Your business name'}</h3><p className="mt-3 text-sm text-white/75">{form.description}</p></div></section>}
    <div className="flex flex-wrap justify-between gap-3"><button type="button" onClick={() => step > 1 ? setStep(step - 1) : (onBack ? onBack() : navigate('/business/dashboard'))} className="rounded-xl border border-[#ead9df] bg-white px-4 py-2.5 text-sm font-semibold">Previous</button><div className="flex gap-2">{step < 8 && <button type="button" onClick={() => setStep(step + 1)} className="rounded-xl bg-[#941f43] px-5 py-2.5 text-sm font-semibold text-white">Next</button>}{step === 8 && <><button type="button" onClick={() => save({ preventDefault() {} })} className="rounded-xl border border-[#941f43] px-4 py-2.5 text-sm font-semibold text-[#941f43]">Save Draft</button><button type="submit" className="rounded-xl bg-[#941f43] px-5 py-2.5 text-sm font-semibold text-white" disabled={saving}>{saving ? 'Submitting...' : 'Submit'}</button></>}</div></div>
  </form></div></div>;
}
