import React from 'react';

const inputClass = 'mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-blue-500';

export default function AcademyRegistrationFields({ form, setForm, logoFile, setLogoFile, existingLogo, aboutImageFile, setAboutImageFile, introVideoFile, setIntroVideoFile, videoThumbnailFile, setVideoThumbnailFile }) {
  const academy = form.academy || {};
  const update = (field, value) => setForm((current) => ({ ...current, academy: { ...(current.academy || {}), [field]: value } }));
  const updateCourse = (index, field, value) => update('courses', (academy.courses || []).map((course, i) => i === index ? { ...course, [field]: value } : course));
  const updateTestimonial = (index, field, value) => update('testimonials', (academy.testimonials || []).map((item, i) => i === index ? { ...item, [field]: value } : item));
  const updateGalleryItem = (kind, index, field, value) => update(kind, (academy[kind] || []).map((item, i) => i === index ? { ...item, [field]: value } : item));
  const addGalleryItem = (kind) => update(kind, [...(academy[kind] || []), { title: '', url: '', file: null }]);
  const removeGalleryItem = (kind, index) => update(kind, (academy[kind] || []).filter((_, i) => i !== index));

  return <div className="col-span-2 space-y-5">
    <section className="rounded-2xl border border-blue-200 bg-gradient-to-r from-[#edf7ff] to-white p-5 sm:p-7"><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-blue-700">Academy business page</p><h2 className="mt-2 text-2xl font-extrabold text-[#12345d]">Build your Academy page</h2><p className="mt-2 text-sm text-slate-600">Add the courses, achievements and student stories that visitors will see on your public Academy page. Use the listing’s main Cover image, Logo and Gallery fields above for page photos.</p></section>
    <section className="rounded-xl border border-blue-100 bg-white p-5 shadow-sm sm:p-7"><h3 className="text-lg font-extrabold text-[#12345d]">Academy branding &amp; about</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-ink/70">Academy logo upload<input type="file" accept="image/*" onChange={(e) => setLogoFile(e.target.files?.[0] || null)} className={inputClass}/>{logoFile && <small className="mt-1 block text-blue-700">{logoFile.name}</small>}{!logoFile && existingLogo && <img src={existingLogo} alt="Current academy logo" className="mt-2 h-16 w-16 rounded object-contain"/>}</label><label className="text-sm font-semibold text-ink/70">Tagline<input value={academy.tagline || ''} onChange={(e) => update('tagline', e.target.value)} placeholder="Learn · Practice · Achieve" className={inputClass}/></label><label className="text-sm font-semibold text-ink/70">About image URL<input value={academy.aboutImage || ''} onChange={(e) => update('aboutImage', e.target.value)} placeholder="https://..." className={inputClass}/><input type="file" accept="image/*" onChange={(e) => setAboutImageFile(e.target.files?.[0] || null)} className={inputClass}/>{aboutImageFile && <small className="mt-1 block text-blue-700">{aboutImageFile.name}</small>}</label><label className="text-sm font-semibold text-ink/70 sm:col-span-2">About the Academy<textarea rows={4} value={academy.about || ''} onChange={(e) => update('about', e.target.value)} placeholder="Tell learners what makes your academy special" className={inputClass}/></label><label className="text-sm font-semibold text-ink/70">Intro video URL<input value={academy.videoUrl || ''} onChange={(e) => update('videoUrl', e.target.value)} placeholder="YouTube or video URL" className={inputClass}/><input type="file" accept="video/*" onChange={(e) => setIntroVideoFile(e.target.files?.[0] || null)} className={inputClass}/>{introVideoFile && <small className="mt-1 block text-blue-700">{introVideoFile.name}</small>}</label><label className="text-sm font-semibold text-ink/70">Video thumbnail URL<input value={academy.videoThumbnail || ''} onChange={(e) => update('videoThumbnail', e.target.value)} placeholder="https://..." className={inputClass}/><input type="file" accept="image/*" onChange={(e) => setVideoThumbnailFile(e.target.files?.[0] || null)} className={inputClass}/>{videoThumbnailFile && <small className="mt-1 block text-blue-700">{videoThumbnailFile.name}</small>}</label></div></section>
    <section className="rounded-xl border border-blue-100 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-extrabold text-[#12345d]">Popular courses</h3><p className="mt-1 text-xs text-slate-500">These appear as clickable course cards on the Academy page.</p></div><button type="button" onClick={() => update('courses', [...(academy.courses || []), { name: '', description: '', duration: '', fee: '', image: '' }])} className="rounded-full bg-blue-800 px-4 py-2 text-xs font-bold text-white">+ Add Course</button></div>{(academy.courses || []).length === 0 && <p className="mt-4 rounded-lg bg-blue-50 p-3 text-xs text-slate-600">Add at least one course. If left empty, sample courses appear on the page.</p>}{(academy.courses || []).map((course, index) => <div key={index} className="mt-4 grid gap-3 rounded-xl border border-blue-100 bg-[#f8fbff] p-4 sm:grid-cols-2"><label className="text-xs font-bold">Course name<input required value={course.name || ''} onChange={(e) => updateCourse(index, 'name', e.target.value)} className={inputClass}/></label><label className="text-xs font-bold">Duration<input value={course.duration || ''} onChange={(e) => updateCourse(index, 'duration', e.target.value)} placeholder="6 Months" className={inputClass}/></label><label className="text-xs font-bold sm:col-span-2">Description<textarea rows={2} value={course.description || ''} onChange={(e) => updateCourse(index, 'description', e.target.value)} className={inputClass}/></label><label className="text-xs font-bold">Fee<input value={course.fee || ''} onChange={(e) => updateCourse(index, 'fee', e.target.value)} className={inputClass}/></label><label className="text-xs font-bold">Course image URL<input value={course.image || ''} onChange={(e) => updateCourse(index, 'image', e.target.value)} placeholder="https://..." className={inputClass}/><span className="mt-2 block text-[10px] font-medium text-slate-500">Or upload an image file</span><input type="file" accept="image/*" onChange={(e) => updateCourse(index, 'file', e.target.files?.[0] || null)} className={inputClass}/>{course.file && <small className="mt-1 block text-blue-700">{course.file.name}</small>}</label><button type="button" onClick={() => update('courses', academy.courses.filter((_, i) => i !== index))} className="text-left text-xs font-bold text-red-700 sm:col-span-2">Remove course</button></div>)}</section>
    <section className="rounded-xl border border-blue-100 bg-white p-5 shadow-sm sm:p-7"><h3 className="text-lg font-extrabold text-[#12345d]">Academy achievements</h3><div className="mt-4 grid gap-4 sm:grid-cols-2">{[['students','Happy students','5,000+'],['programCount','Courses and programs','50+'],['placementRate','Placement rate','95%'],['years','Years of excellence','10+']].map(([field,label,placeholder])=><label key={field} className="text-sm font-semibold text-ink/70">{label}<input value={academy[field] || ''} onChange={(e) => update(field, e.target.value)} placeholder={placeholder} className={inputClass}/></label>)}<label className="text-sm font-semibold text-ink/70 sm:col-span-2">Academy highlights (one per line)<textarea rows={3} value={(academy.highlights || []).join('\n')} onChange={(e) => update('highlights', e.target.value.split('\n').map((value) => value.trim()).filter(Boolean))} placeholder={'Expert Faculty\nHands-on Training\nPlacement Support'} className={inputClass}/></label><label className="text-sm font-semibold text-ink/70 sm:col-span-2">Why choose this Academy (one per line)<textarea rows={3} value={(academy.features || []).join('\n')} onChange={(e) => update('features', e.target.value.split('\n').map((value) => value.trim()).filter(Boolean))} placeholder={'Industry-Focused Curriculum\nFlexible Batches\nExperienced Faculty'} className={inputClass}/></label></div></section>
    <section className="rounded-xl border border-blue-100 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center justify-between gap-3"><div><h3 className="text-lg font-extrabold text-[#12345d]">Student testimonials</h3><p className="mt-1 text-xs text-slate-500">Share learner feedback to feature on your Academy page.</p></div><button type="button" onClick={() => update('testimonials', [...(academy.testimonials || []), { name: '', quote: '' }])} className="rounded-full bg-blue-800 px-4 py-2 text-xs font-bold text-white">+ Add Testimonial</button></div>{(academy.testimonials || []).map((item, index) => <div key={index} className="mt-4 grid gap-3 rounded-xl border border-blue-100 bg-[#f8fbff] p-4 sm:grid-cols-2"><label className="text-xs font-bold">Student name<input value={item.name || ''} onChange={(e) => updateTestimonial(index, 'name', e.target.value)} className={inputClass}/></label><label className="text-xs font-bold sm:col-span-2">Student story<textarea rows={3} value={item.quote || ''} onChange={(e) => updateTestimonial(index, 'quote', e.target.value)} className={inputClass}/></label><button type="button" onClick={() => update('testimonials', academy.testimonials.filter((_, i) => i !== index))} className="text-left text-xs font-bold text-red-700 sm:col-span-2">Remove testimonial</button></div>)}</section>
    {[
      ['galleryPhotos', 'Academy photo gallery', 'Add Photo', 'image/*'],
      ['galleryVideos', 'Academy video gallery', 'Add Video', 'video/*'],
    ].map(([kind, title, addLabel, accept]) => <section key={kind} className="rounded-xl border border-blue-100 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-extrabold text-[#12345d]">{title}</h3><p className="mt-1 text-xs text-slate-500">Each item can have a title and either an uploaded file or a URL.</p></div><button type="button" onClick={() => addGalleryItem(kind)} className="rounded-full bg-blue-800 px-4 py-2 text-xs font-bold text-white">+ {addLabel}</button></div>{(academy[kind] || []).map((item, index) => <div key={index} className="mt-4 grid gap-3 rounded-xl border border-blue-100 bg-[#f8fbff] p-4 sm:grid-cols-2"><label className="text-xs font-bold">{kind === 'galleryPhotos' ? 'Photo' : 'Video'} title<input value={item.title || ''} onChange={(e) => updateGalleryItem(kind, index, 'title', e.target.value)} placeholder={`Enter ${kind === 'galleryPhotos' ? 'photo' : 'video'} title`} className={inputClass}/></label><label className="text-xs font-bold">Upload {kind === 'galleryPhotos' ? 'photo' : 'video'}<input type="file" accept={accept} onChange={(e) => updateGalleryItem(kind, index, 'file', e.target.files?.[0] || null)} className={inputClass}/>{item.file && <small className="mt-1 block text-blue-700">{item.file.name}</small>}</label><label className="text-xs font-bold sm:col-span-2">{kind === 'galleryPhotos' ? 'Photo' : 'Video'} URL (optional)<input type="text" value={item.url || ''} onChange={(e) => updateGalleryItem(kind, index, 'url', e.target.value)} placeholder="https://... or www.example.com/..." className={inputClass}/><small className="mt-1 block font-normal text-slate-500">For photos, use a direct image link or a public Google Drive image link.</small></label><button type="button" onClick={() => removeGalleryItem(kind, index)} className="text-left text-xs font-bold text-red-700 sm:col-span-2">Remove {kind === 'galleryPhotos' ? 'photo' : 'video'}</button></div>)}</section>)}
  </div>;
}
