import React from 'react';

const facilityOptions = ['Library', 'Computer Lab', 'Science Lab', 'Digital Classrooms', 'Auditorium', 'Seminar Hall', 'Hostel', 'Canteen', 'Transportation', 'Wi-Fi', 'Parking', 'Sports Ground', 'Gym', 'Medical Facility', 'CCTV Security', 'Drinking Water'];
const collegeTypes = ['Intermediate College', 'Degree College', 'Engineering College', 'Medical College', 'Pharmacy College', 'Management College', 'Law College', 'Polytechnic', 'Arts & Science College', 'Other'];

function Section({ number, title, children }) {
  return <section className="rounded-xl border border-[#cbdde9] bg-white p-5 shadow-sm sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#1769a8]">{number}</p><h2 className="mt-1 font-display text-xl font-semibold text-[#17324d]">{title}</h2><div className="mt-4 grid grid-cols-2 gap-4">{children}</div></section>;
}

export default function CollegeRegistrationFields({ form, setForm, inputClass, faculty, setFaculty, achievements, setAchievements, principalImageFile, setPrincipalImageFile, logoFile, setLogoFile, footerLogoFile, setFooterLogoFile, galleryFiles, setGalleryFiles, schoolVideos, setSchoolVideos }) {
  const update = (field) => (event) => setForm((current) => ({ ...current, [field]: event.target.value }));
  const setList = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  const collegeType = form.collegeType || '';
  const isIntermediate = collegeType === 'Intermediate College';
  const programs = form.collegePrograms || [];
  const groups = form.collegeGroups || [];
  const changeItem = (field, index, key, value) => setList(field, (form[field] || []).map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item));
  const addItem = (field, item) => setList(field, [...(form[field] || []), item]);
  const removeItem = (field, index) => setList(field, (form[field] || []).filter((_, itemIndex) => itemIndex !== index));
  const toggleFacility = (facility) => setList('collegeFacilities', (form.collegeFacilities || []).includes(facility) ? form.collegeFacilities.filter((item) => item !== facility) : [...(form.collegeFacilities || []), facility]);
  const updateFaculty = (index, field, value) => setFaculty((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item));

  return <div className="col-span-2 space-y-5">
    <div className="rounded-xl border border-[#1769a8]/25 bg-[#eef7ff] p-5 sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#1769a8]">College registration</p><h2 className="mt-2 font-display text-2xl font-semibold text-[#17324d]">College &amp; institute profile</h2><p className="mt-2 text-sm text-[#587087]">Complete these sections to create the public college page automatically.</p></div>
    <Section number="0. Header & footer branding" title="College logos"><label>Header logo *<input required type="file" accept="image/*" onChange={(e) => setLogoFile(e.target.files?.[0] || null)} className={inputClass} />{logoFile && <span className="mt-1 block text-xs text-[#1769a8]">{logoFile.name} selected</span>}</label><label>Footer logo<input type="file" accept="image/*" onChange={(e) => setFooterLogoFile(e.target.files?.[0] || null)} className={inputClass} />{footerLogoFile && <span className="mt-1 block text-xs text-[#1769a8]">{footerLogoFile.name} selected</span>}</label><p className="col-span-2 text-xs text-[#587087]">The header logo appears at the top of the public college page. The optional footer logo is saved for footer branding.</p></Section>
    <Section number="1. Basic college information" title="College identity"><label className="col-span-2 sm:col-span-1">College type *<select required value={collegeType} onChange={update('collegeType')} className={inputClass}><option value="">Select college type</option>{collegeTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label className="col-span-2 sm:col-span-1">Ownership *<select required value={form.ownership || ''} onChange={update('ownership')} className={inputClass}><option value="">Select ownership</option>{['Private', 'Government', 'Aided'].map((item) => <option key={item}>{item}</option>)}</select></label><label>Established year<input value={form.establishedYear || ''} onChange={update('establishedYear')} placeholder="YYYY" className={inputClass} /></label><label>College code<input value={form.collegeCode || ''} onChange={update('collegeCode')} className={inputClass} /></label><label className="col-span-2">Tagline<input value={form.tagline || ''} onChange={update('tagline')} placeholder="Learn, lead, succeed" className={inputClass} /></label></Section>
    <Section number="2. Board, affiliation & accreditation" title={isIntermediate ? 'Board information' : 'Affiliation & accreditation'}>{isIntermediate ? <><label>Board *<select required value={form.board || ''} onChange={update('board')} className={inputClass}><option value="">Select board</option>{['BIEAP', 'TSBIE', 'CBSE', 'Other'].map((item) => <option key={item}>{item}</option>)}</select></label><label>Affiliation number<input value={form.affiliationNumber || ''} onChange={update('affiliationNumber')} className={inputClass} /></label></> : <><label>University affiliation *<input required value={form.universityAffiliation || ''} onChange={update('universityAffiliation')} className={inputClass} /></label><label>Affiliation number<input value={form.affiliationNumber || ''} onChange={update('affiliationNumber')} className={inputClass} /></label><label>NAAC grade<input value={form.naacGrade || ''} onChange={update('naacGrade')} placeholder="A+" className={inputClass} /></label><label>AICTE / NBA approval<select value={form.approvalStatus || ''} onChange={update('approvalStatus')} className={inputClass}><option value="">Select</option><option>Yes</option><option>No</option></select></label></>}<label className="col-span-2">Recognition details<textarea value={form.recognitionDetails || ''} onChange={update('recognitionDetails')} rows={2} className={inputClass} /></label></Section>
    <Section number="3. Courses & programs" title={isIntermediate ? 'Intermediate groups' : 'Courses / programs'}><div className="col-span-2 flex justify-end"><button type="button" onClick={() => addItem(isIntermediate ? 'collegeGroups' : 'collegePrograms', isIntermediate ? { name: '', duration: '2 Years', medium: 'English', subjects: '', fee: '' } : { name: '', duration: '', type: 'UG', eligibility: '', fee: '', description: '' })} className="rounded-full bg-[#1769a8] px-4 py-2 text-xs font-bold text-white">+ Add {isIntermediate ? 'Group' : 'Course'}</button></div>{(isIntermediate ? groups : programs).map((item, index) => <div key={index} className="col-span-2 grid grid-cols-2 gap-3 rounded-lg border border-[#d9e9f6] p-4"><label>{isIntermediate ? 'Group name *' : 'Course name *'}<input required value={item.name} onChange={(e) => changeItem(isIntermediate ? 'collegeGroups' : 'collegePrograms', index, 'name', e.target.value)} placeholder={isIntermediate ? 'MPC / BiPC / MEC' : 'B.Tech Computer Science'} className={inputClass} /></label><label>Duration<input value={item.duration} onChange={(e) => changeItem(isIntermediate ? 'collegeGroups' : 'collegePrograms', index, 'duration', e.target.value)} className={inputClass} /></label><label>{isIntermediate ? 'Medium' : 'Course type'}<input value={isIntermediate ? item.medium : item.type} onChange={(e) => changeItem(isIntermediate ? 'collegeGroups' : 'collegePrograms', index, isIntermediate ? 'medium' : 'type', e.target.value)} className={inputClass} /></label><label>Fee<input value={item.fee} onChange={(e) => changeItem(isIntermediate ? 'collegeGroups' : 'collegePrograms', index, 'fee', e.target.value)} placeholder="₹" className={inputClass} /></label><label className="col-span-2">{isIntermediate ? 'Subjects' : 'Eligibility / description'}<textarea value={isIntermediate ? item.subjects : `${item.eligibility || ''}${item.description ? `\n${item.description}` : ''}`} onChange={(e) => changeItem(isIntermediate ? 'collegeGroups' : 'collegePrograms', index, isIntermediate ? 'subjects' : 'description', e.target.value)} rows={2} className={inputClass} /></label><button type="button" onClick={() => removeItem(isIntermediate ? 'collegeGroups' : 'collegePrograms', index)} className="col-span-2 text-left text-xs font-bold text-vermilion">Remove</button></div>)}</Section>
    <Section number="4. Admissions" title="Admission information"><label>Admission status<select value={form.admissionStatus || 'open'} onChange={update('admissionStatus')} className={inputClass}><option value="open">Open</option><option value="closed">Closed</option></select></label><label>Entrance exam<input value={form.entranceExam || ''} onChange={update('entranceExam')} className={inputClass} /></label><label>Application starts<input type="date" value={form.applicationStartDate || ''} onChange={update('applicationStartDate')} className={inputClass} /></label><label>Application last date<input type="date" value={form.applicationLastDate || ''} onChange={update('applicationLastDate')} className={inputClass} /></label><label>Admission contact<input value={form.enquiryPhone || ''} onChange={update('enquiryPhone')} className={inputClass} /></label><label>Admission email<input type="email" value={form.admissionEmail || ''} onChange={update('admissionEmail')} className={inputClass} /></label><label className="col-span-2">Admission process & eligibility<textarea value={form.admissionProcess || ''} onChange={update('admissionProcess')} rows={3} className={inputClass} /></label></Section>
    <Section number="5. Campus facilities" title="Select facilities"><div className="col-span-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{facilityOptions.map((facility) => <label key={facility} className="flex items-center gap-2 rounded border border-[#d9e9f6] p-2 text-sm"><input type="checkbox" checked={(form.collegeFacilities || []).includes(facility)} onChange={() => toggleFacility(facility)} />{facility}</label>)}</div><label className="col-span-2">Other facility<input value={form.customFacility || ''} onChange={update('customFacility')} className={inputClass} /></label></Section>
    <Section number="6. Faculty & principal" title="People behind the college"><div className="col-span-2 flex justify-end"><button type="button" onClick={() => setFaculty((items) => [...items, { name: '', designation: '', department: '', qualification: '', experience: '', bio: '', photoFiles: [] }])} className="rounded-full bg-[#1769a8] px-4 py-2 text-xs font-bold text-white">+ Add Faculty</button></div>{faculty.map((item, index) => <div key={index} className="col-span-2 grid grid-cols-2 gap-3 rounded-lg border border-[#d9e9f6] p-4"><label>Name *<input required value={item.name} onChange={(e) => updateFaculty(index, 'name', e.target.value)} className={inputClass} /></label><label>Designation<input value={item.designation} onChange={(e) => updateFaculty(index, 'designation', e.target.value)} className={inputClass} /></label><label>Department<input value={item.department} onChange={(e) => updateFaculty(index, 'department', e.target.value)} className={inputClass} /></label><label>Qualification<input value={item.qualification} onChange={(e) => updateFaculty(index, 'qualification', e.target.value)} className={inputClass} /></label><label>Experience<input value={item.experience} onChange={(e) => updateFaculty(index, 'experience', e.target.value)} className={inputClass} /></label><label>Photo<input type="file" accept="image/*" onChange={(e) => updateFaculty(index, 'photoFiles', Array.from(e.target.files || []))} className={inputClass} /></label><button type="button" onClick={() => setFaculty((items) => items.filter((_, itemIndex) => itemIndex !== index))} className="col-span-2 text-left text-xs font-bold text-vermilion">Remove faculty</button></div>)}<label>Principal / director name<input value={form.principalName || ''} onChange={update('principalName')} className={inputClass} /></label><label>Designation<input value={form.principalDesignation || 'Principal'} onChange={update('principalDesignation')} className={inputClass} /></label><label>Qualification<input value={form.principalQualification || ''} onChange={update('principalQualification')} className={inputClass} /></label><label>Profile photo<input type="file" accept="image/*" onChange={(e) => setPrincipalImageFile(e.target.files?.[0] || null)} className={inputClass} /></label><label className="col-span-2">Principal message<textarea value={form.principalMessage || ''} onChange={update('principalMessage')} rows={3} className={inputClass} /></label></Section>
    <Section number="7. Placements & achievements" title="Outcomes and recognition"><label>Placements available?<select value={form.placementAvailable || ''} onChange={update('placementAvailable')} className={inputClass}><option value="">Select</option><option>Yes</option><option>No</option></select></label><label>Placement officer<input value={form.placementOfficer || ''} onChange={update('placementOfficer')} className={inputClass} /></label><label>Average package<input value={form.averagePackage || ''} onChange={update('averagePackage')} className={inputClass} /></label><label>Highest package<input value={form.highestPackage || ''} onChange={update('highestPackage')} className={inputClass} /></label><label className="col-span-2">Top recruiting companies<input value={form.recruitingCompanies || ''} onChange={update('recruitingCompanies')} placeholder="Company names, comma separated" className={inputClass} /></label><div className="col-span-2 flex justify-end"><button type="button" onClick={() => setAchievements((items) => [...items, { title: '', year: '', description: '' }])} className="rounded-full bg-[#a47b2c] px-4 py-2 text-xs font-bold text-white">+ Add Achievement</button></div>{achievements.map((item, index) => <div key={index} className="col-span-2 grid grid-cols-2 gap-3 rounded-lg border border-[#f0d8b0] p-4"><label>Title<input value={item.title} onChange={(e) => setAchievements((items) => items.map((value, itemIndex) => itemIndex === index ? { ...value, title: e.target.value } : value))} className={inputClass} /></label><label>Year<input value={item.year} onChange={(e) => setAchievements((items) => items.map((value, itemIndex) => itemIndex === index ? { ...value, year: e.target.value } : value))} className={inputClass} /></label><label className="col-span-2">Description<textarea value={item.description} onChange={(e) => setAchievements((items) => items.map((value, itemIndex) => itemIndex === index ? { ...value, description: e.target.value } : value))} className={inputClass} /></label></div>)}</Section>
    <Section number="8. College gallery" title="Multiple photos"><label className="col-span-2">Select multiple campus photos<input type="file" accept="image/*" multiple onChange={(e) => setGalleryFiles(Array.from(e.target.files || []))} className={inputClass} /></label>{galleryFiles.length > 0 && <div className="col-span-2 grid grid-cols-2 gap-3 sm:grid-cols-4">{galleryFiles.map((file, index) => <div key={`${file.name}-${index}`} className="rounded border border-[#d9e9f6] p-2"><img src={URL.createObjectURL(file)} alt={file.name} className="h-20 w-full rounded object-cover" /><p className="mt-1 truncate text-xs">{file.name}</p><button type="button" onClick={() => setGalleryFiles((files) => files.filter((_, fileIndex) => fileIndex !== index))} className="mt-1 text-xs font-bold text-vermilion">Remove</button></div>)}</div>}</Section>
    <Section number="9. College videos" title="YouTube, upload, or video URL"><div className="col-span-2 flex justify-end"><button type="button" onClick={() => setSchoolVideos((items) => [...items, { title: '', type: 'youtube', url: '', file: null }])} className="rounded-full bg-[#1769a8] px-4 py-2 text-xs font-bold text-white">+ Add Video</button></div>{schoolVideos.map((item, index) => <div key={index} className="col-span-2 grid grid-cols-2 gap-3 rounded-lg border border-[#d9e9f6] p-4"><label>Video title<input value={item.title} onChange={(e) => setSchoolVideos((items) => items.map((value, itemIndex) => itemIndex === index ? { ...value, title: e.target.value } : value))} className={inputClass} /></label><label>Video source<select value={item.type} onChange={(e) => setSchoolVideos((items) => items.map((value, itemIndex) => itemIndex === index ? { ...value, type: e.target.value, url: '', file: null } : value))} className={inputClass}><option value="youtube">YouTube URL</option><option value="upload">Upload video</option><option value="url">Other video URL</option></select></label>{item.type === 'upload' ? <label className="col-span-2">Choose video file<input type="file" accept="video/*" onChange={(e) => setSchoolVideos((items) => items.map((value, itemIndex) => itemIndex === index ? { ...value, file: e.target.files?.[0] || null } : value))} className={inputClass} /></label> : <label className="col-span-2">{item.type === 'youtube' ? 'YouTube URL' : 'Video URL'}<input type="url" value={item.url} onChange={(e) => setSchoolVideos((items) => items.map((value, itemIndex) => itemIndex === index ? { ...value, url: e.target.value } : value))} placeholder={item.type === 'youtube' ? 'https://youtube.com/watch?v=...' : 'https://example.com/video.mp4'} className={inputClass} /></label>}<button type="button" onClick={() => setSchoolVideos((items) => items.filter((_, itemIndex) => itemIndex !== index))} className="col-span-2 text-left text-xs font-bold text-vermilion">Remove video</button></div>)}</Section>
  </div>;
}
