import React from 'react';

const services = ['Residential Solar', 'Commercial Solar', 'Industrial Solar', 'Solar Pump Systems', 'Solar Water Heater', 'Solar Installation', 'Solar Maintenance / AMC', 'On-Grid Solar', 'Off-Grid Solar', 'Hybrid Solar'];
const projectTypes = ['Residential', 'Commercial', 'Industrial', 'Agriculture'];
const galleryTypes = ['Residential', 'Commercial', 'Industrial', 'Solar Panels', 'Installation', 'Completed Projects'];

const emptyService = () => ({ name: '', description: '', price: '', benefits: '', files: [], video: null, custom: false });
const emptyProject = () => ({ name: '', type: 'Residential', location: '', capacity: '', date: '', description: '', files: [], video: null });
const emptyVideo = () => ({ title: '', url: '', description: '', thumbnail: null });
const emptyProduct = () => ({ panel: '', inverter: '', battery: '', pump: '', warranty: '', file: null });
const emptyCertificate = () => ({ name: '', organization: '', year: '', file: null });
const emptyReview = () => ({ name: '', rating: '5', review: '', photo: null });
const emptyFaq = () => ({ question: '', answer: '' });

function Field({ label, value, onChange, type = 'text', placeholder, ...props }) {
  const handleChange = (event) => onChange(type === 'file' ? (props.multiple ? Array.from(event.target.files || []) : event.target.files?.[0] || null) : event.target.value);
  return <label className="text-sm text-ink/70">{label}<input type={type} value={type === 'file' ? undefined : (value || '')} onChange={handleChange} placeholder={placeholder} className="mt-1 w-full rounded border border-line bg-white px-3 py-2.5 outline-none focus:border-ink/40" {...props} /></label>;
}

function TextField({ label, value, onChange, placeholder }) {
  return <label className="text-sm text-ink/70">{label}<textarea rows={3} value={value || ''} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-1 w-full rounded border border-line bg-white px-3 py-2.5 outline-none focus:border-ink/40" /></label>;
}

function Section({ number, title, children, action }) {
  return <section className="rounded-[1.25rem] border border-[#b9e6df] bg-white/95 p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#168b9a]">{number}. Solar business</p><h2 className="mt-1 font-display text-xl font-semibold text-[#17324d]">{title}</h2></div>{action}</div><div className="mt-5 grid grid-cols-2 gap-4">{children}</div></section>;
}

export default function SolarRegistrationFields({ data, setData, inputClass }) {
  const update = (field, value) => setData((current) => ({ ...current, [field]: value }));
  const updateItem = (field, index, key, value) => setData((current) => ({ ...current, [field]: current[field].map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item) }));
  const updateFeature = (index, value) => setData((current) => ({ ...current, features: current.features.map((item, itemIndex) => itemIndex === index ? value : item) }));
  const addItem = (field, item) => setData((current) => ({ ...current, [field]: [...current[field], item()] }));
  const removeItem = (field, index) => setData((current) => ({ ...current, [field]: current[field].filter((_, itemIndex) => itemIndex !== index) }));
  const file = (field, index, key, files) => updateItem(field, index, key, files);
  const toggleService = (name) => setData((current) => {
    const exists = current.services.some((item) => item.name === name);
    return { ...current, services: exists ? current.services.filter((item) => item.name !== name) : [...current.services, { ...emptyService(), name }] };
  });
  const addCustomService = () => setData((current) => ({ ...current, services: [...current.services, { ...emptyService(), custom: true }] }));
  const button = (label, onClick) => <button type="button" onClick={onClick} className="rounded-full bg-[#168b9a] px-4 py-2 text-xs font-bold text-white">+ {label}</button>;

  return <div className="col-span-2 space-y-5">
    <div className="rounded-[1.25rem] border border-[#b9e6df] bg-[#effcf9] p-5 sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#168b9a]">Solar Owner Portal</p><h2 className="mt-2 font-display text-2xl font-semibold text-[#17324d]">Build your Solar business page</h2><p className="mt-2 text-sm text-ink/60">This specialized form creates the Solar page layout with services, projects, gallery, videos, brands, reviews and quote contact sections.</p></div>

    <Section number="1" title="Business Details"><Field label="Solar company name" value={data.companyName} onChange={(value) => update('companyName', value)} /><Field label="Tagline" value={data.tagline} onChange={(value) => update('tagline', value)} placeholder="Clean energy, brighter tomorrow" /><Field label="Year established" value={data.yearEstablished} onChange={(value) => update('yearEstablished', value)} /><Field label="Years of experience" value={data.experience} onChange={(value) => update('experience', value)} /><TextField label="Business description" value={data.about} onChange={(value) => update('about', value)} /><Field label="Logo" type="file" onChange={(value) => update('logoFile', value)} /></Section>

    <Section number="2" title="Contact Details"><Field label="Mobile number" value={data.mobile} onChange={(value) => update('mobile', value)} /><Field label="WhatsApp number" value={data.whatsapp} onChange={(value) => update('whatsapp', value)} /><Field label="Email" type="email" value={data.email} onChange={(value) => update('email', value)} /><Field label="Website" value={data.website} onChange={(value) => update('website', value)} /><TextField label="Working hours" value={data.workingHours} onChange={(value) => update('workingHours', value)} placeholder="Mon-Sat, 9 AM - 6 PM" /></Section>

    <Section number="3" title="Solar Services" action={button('Add custom service', addCustomService)}>
      <div className="col-span-2 rounded-lg border border-[#cfe6e5] bg-[#f5fbff] p-4">
        <p className="mb-3 text-sm font-medium text-ink/70">Select the services your business provides</p>
        <div className="grid gap-2 sm:grid-cols-2">{services.map((name) => <label key={name} className="flex items-center gap-2 rounded bg-white px-3 py-2 text-sm text-ink/75"><input type="checkbox" checked={data.services.some((item) => item.name === name)} onChange={() => toggleService(name)} />{name}</label>)}</div>
      </div>
      <div className="col-span-2 grid gap-3">{data.services.map((item, index) => <div key={index} className="grid grid-cols-2 gap-3 rounded-lg border border-[#cfe6e5] bg-[#f5fbff] p-4">{item.custom ? <Field label="Custom service name" value={item.name} onChange={(value) => updateItem('services', index, 'name', value)} placeholder="Enter your service" /> : <p className="col-span-2 text-sm font-semibold text-[#17324d]">{item.name}</p>}<TextField label="Description" value={item.description} onChange={(value) => updateItem('services', index, 'description', value)} /><Field label="Starting price / range" value={item.price} onChange={(value) => updateItem('services', index, 'price', value)} /><TextField label="Benefits" value={item.benefits} onChange={(value) => updateItem('services', index, 'benefits', value)} /><Field label="Main / multiple images" type="file" accept="image/*" multiple onChange={(value) => file('services', index, 'files', value)} /><Field label="Service video" type="file" accept="video/*" onChange={(value) => updateItem('services', index, 'video', value)} /><button type="button" onClick={() => removeItem('services', index)} className="col-span-2 text-left text-xs font-bold text-vermilion">Remove service</button></div>)}</div>
    </Section>

    <Section number="4" title="Solar Projects" action={button('Add Project', () => addItem('projects', emptyProject))}><div className="col-span-2 grid gap-3">{data.projects.map((item, index) => <div key={index} className="grid grid-cols-2 gap-3 rounded-lg border border-[#f0d8b0] bg-[#fffaf2] p-4"><Field label="Project name" value={item.name} onChange={(value) => updateItem('projects', index, 'name', value)} /><label className="text-sm text-ink/70">Project type<select value={item.type} onChange={(event) => updateItem('projects', index, 'type', event.target.value)} className="mt-1 w-full rounded border border-line bg-white px-3 py-2.5">{projectTypes.map((type) => <option key={type}>{type}</option>)}</select></label><Field label="Location" value={item.location} onChange={(value) => updateItem('projects', index, 'location', value)} /><Field label="Capacity (kW)" value={item.capacity} onChange={(value) => updateItem('projects', index, 'capacity', value)} /><Field label="Installation date" type="date" value={item.date} onChange={(value) => updateItem('projects', index, 'date', value)} /><TextField label="Project description" value={item.description} onChange={(value) => updateItem('projects', index, 'description', value)} /><Field label="Project images" type="file" multiple onChange={(value) => file('projects', index, 'files', value)} /><Field label="Project video" type="file" onChange={(value) => updateItem('projects', index, 'video', value)} /><button type="button" onClick={() => removeItem('projects', index)} className="col-span-2 text-left text-xs font-bold text-vermilion">Remove project</button></div>)}</div></Section>

    <Section number="5" title="Solar Gallery" action={button('Add Image', () => addItem('galleryItems', () => ({ service: '', file: null })))}><div className="col-span-2 grid gap-3">{data.galleryItems.map((item, index) => <div key={index} className="grid grid-cols-2 gap-3 rounded-lg border border-[#cfe6e5] bg-[#f5fbff] p-4"><label className="text-sm text-ink/70">Select service<select value={item.service} onChange={(event) => updateItem('galleryItems', index, 'service', event.target.value)} className="mt-1 w-full rounded border border-line bg-white px-3 py-2.5"><option value="">General gallery</option>{services.map((service) => <option key={service}>{service}</option>)}</select></label><Field label="Upload image" type="file" accept="image/*" onChange={(value) => updateItem('galleryItems', index, 'file', value)} /><button type="button" onClick={() => removeItem('galleryItems', index)} className="col-span-2 text-left text-xs font-bold text-vermilion">Remove image</button></div>)}</div>{data.galleryItems.length === 0 && <p className="col-span-2 text-sm text-ink/55">Click Add Image to choose a service and upload its photo.</p>}</Section>

    <Section number="6" title="Solar Videos" action={button('Add Video', () => addItem('videos', emptyVideo))}><div className="col-span-2 grid gap-3">{data.videos.map((item, index) => <div key={index} className="grid grid-cols-2 gap-3 rounded-lg border border-[#d8c9f3] bg-[#faf8ff] p-4"><Field label="Video title" value={item.title} onChange={(value) => updateItem('videos', index, 'title', value)} /><Field label="YouTube / video URL" value={item.url} onChange={(value) => updateItem('videos', index, 'url', value)} /><TextField label="Description" value={item.description} onChange={(value) => updateItem('videos', index, 'description', value)} /><Field label="Thumbnail" type="file" onChange={(value) => updateItem('videos', index, 'thumbnail', value)} /><button type="button" onClick={() => removeItem('videos', index)} className="col-span-2 text-left text-xs font-bold text-vermilion">Remove video</button></div>)}</div></Section>

    <Section number="7" title="Why Choose Us" action={button('Add Feature', () => update('features', [...data.features, '']))}><div className="col-span-2 grid gap-3 sm:grid-cols-2">{data.features.map((feature, index) => <div key={index} className="flex gap-2"><input value={feature} onChange={(event) => updateFeature(index, event.target.value)} className="w-full rounded border border-line bg-white px-3 py-2.5" /><button type="button" onClick={() => removeItem('features', index)} className="text-vermilion">×</button></div>)}</div></Section>

    <Section number="8" title="Products / Brands"><Field label="Solar panel brand" value={data.brands.panel} onChange={(value) => update('brands', { ...data.brands, panel: value })} /><Field label="Inverter brand" value={data.brands.inverter} onChange={(value) => update('brands', { ...data.brands, inverter: value })} /><Field label="Battery brand" value={data.brands.battery} onChange={(value) => update('brands', { ...data.brands, battery: value })} /><Field label="Solar pump brand" value={data.brands.pump} onChange={(value) => update('brands', { ...data.brands, pump: value })} /><Field label="Warranty" value={data.brands.warranty} onChange={(value) => update('brands', { ...data.brands, warranty: value })} /><Field label="Product image" type="file" onChange={(value) => update('brands', { ...data.brands, file: value })} /></Section>

    <Section number="9" title="Certifications" action={button('Add Certificate', () => addItem('certifications', emptyCertificate))}><div className="col-span-2 grid gap-3">{data.certifications.map((item, index) => <div key={index} className="grid grid-cols-2 gap-3 rounded-lg border border-line bg-[#f8fbfd] p-4"><Field label="Certificate name" value={item.name} onChange={(value) => updateItem('certifications', index, 'name', value)} /><Field label="Issuing organization" value={item.organization} onChange={(value) => updateItem('certifications', index, 'organization', value)} /><Field label="Year" value={item.year} onChange={(value) => updateItem('certifications', index, 'year', value)} /><Field label="Certificate image" type="file" onChange={(value) => updateItem('certifications', index, 'file', value)} /><button type="button" onClick={() => removeItem('certifications', index)} className="col-span-2 text-left text-xs font-bold text-vermilion">Remove certificate</button></div>)}</div></Section>

    <Section number="10" title="Customer Reviews" action={button('Add Review', () => addItem('reviews', emptyReview))}><div className="col-span-2 grid gap-3">{data.reviews.map((item, index) => <div key={index} className="grid grid-cols-2 gap-3 rounded-lg border border-line bg-white p-4"><Field label="Customer name" value={item.name} onChange={(value) => updateItem('reviews', index, 'name', value)} /><Field label="Rating" type="number" min="1" max="5" value={item.rating} onChange={(value) => updateItem('reviews', index, 'rating', value)} /><TextField label="Review" value={item.review} onChange={(value) => updateItem('reviews', index, 'review', value)} /><Field label="Customer photo" type="file" onChange={(value) => updateItem('reviews', index, 'photo', value)} /><button type="button" onClick={() => removeItem('reviews', index)} className="col-span-2 text-left text-xs font-bold text-vermilion">Remove review</button></div>)}</div></Section>

    <Section number="11" title="FAQ" action={button('Add FAQ', () => addItem('faqs', emptyFaq))}><div className="col-span-2 grid gap-3">{data.faqs.map((item, index) => <div key={index} className="grid gap-3 rounded-lg border border-line bg-white p-4"><Field label="Question" value={item.question} onChange={(value) => updateItem('faqs', index, 'question', value)} /><TextField label="Answer" value={item.answer} onChange={(value) => updateItem('faqs', index, 'answer', value)} /><button type="button" onClick={() => removeItem('faqs', index)} className="text-left text-xs font-bold text-vermilion">Remove FAQ</button></div>)}</div></Section>

    <Section number="12" title="Enquiry / Free Quote"><Field label="Customer name field" value={data.quote.nameLabel} onChange={(value) => update('quote', { ...data.quote, nameLabel: value })} placeholder="Your name" /><Field label="Customer mobile field" value={data.quote.mobileLabel} onChange={(value) => update('quote', { ...data.quote, mobileLabel: value })} placeholder="Mobile number" /><Field label="Customer WhatsApp field" value={data.quote.whatsappLabel} onChange={(value) => update('quote', { ...data.quote, whatsappLabel: value })} placeholder="WhatsApp number" /><Field label="Customer location field" value={data.quote.locationLabel} onChange={(value) => update('quote', { ...data.quote, locationLabel: value })} placeholder="Installation location" /><Field label="Solar type field" value={data.quote.solarType} onChange={(value) => update('quote', { ...data.quote, solarType: value })} placeholder="On-grid / Off-grid / Hybrid" /><Field label="Required capacity" value={data.quote.capacity} onChange={(value) => update('quote', { ...data.quote, capacity: value })} placeholder="5 kW" /><Field label="Electricity bill" value={data.quote.bill} onChange={(value) => update('quote', { ...data.quote, bill: value })} placeholder="Monthly bill" /><TextField label="Quote message" value={data.quote.message} onChange={(value) => update('quote', { ...data.quote, message: value })} /></Section>

    <Section number="13" title="Social Media & SEO"><Field label="Instagram" value={data.social.instagram} onChange={(value) => update('social', { ...data.social, instagram: value })} /><Field label="Facebook" value={data.social.facebook} onChange={(value) => update('social', { ...data.social, facebook: value })} /><Field label="YouTube" value={data.social.youtube} onChange={(value) => update('social', { ...data.social, youtube: value })} /><Field label="LinkedIn" value={data.social.linkedin} onChange={(value) => update('social', { ...data.social, linkedin: value })} /><Field label="Page title" value={data.seo.title} onChange={(value) => update('seo', { ...data.seo, title: value })} /><TextField label="Meta description" value={data.seo.description} onChange={(value) => update('seo', { ...data.seo, description: value })} /><Field label="Keywords" value={data.seo.keywords} onChange={(value) => update('seo', { ...data.seo, keywords: value })} /><Field label="URL slug" value={data.seo.slug} onChange={(value) => update('seo', { ...data.seo, slug: value })} /></Section>
  </div>;
}

export const createSolarDetails = () => ({ companyName: '', tagline: '', yearEstablished: '', experience: '', about: '', mobile: '', whatsapp: '', email: '', website: '', workingHours: '', services: [], projects: [], galleryItems: [], videos: [], features: [], brands: emptyProduct(), certifications: [], reviews: [], faqs: [], quote: { nameLabel: 'Your name', mobileLabel: 'Mobile number', whatsappLabel: 'WhatsApp number', locationLabel: 'Installation location', solarType: '', capacity: '', bill: '', message: '' }, social: { instagram: '', facebook: '', youtube: '', linkedin: '' }, seo: { title: '', description: '', keywords: '', slug: '' }, logoFile: null });
