import React from 'react';
import ReviewsSection from './ReviewsSection';

const fallbackFacts = [
  ['Board', 'CBSE'], ['Established', '2010'], ['Classes', 'Nursery - Class 10'],
  ['Gender', 'Co-education'], ['Medium', 'English'], ['Type', 'Private'],
  ['Ratio', '25:1'], ['Rating', '4.6 / 5'],
];

function ActionButton({ href, children, tone = 'blue' }) {
  const tones = {
    blue: 'bg-[#086bc5] text-white hover:bg-[#07579f]',
    green: 'bg-[#16a765] text-white hover:bg-[#128b54]',
    light: 'border border-white/70 bg-[#173c61]/45 text-white hover:bg-white/15',
    yellow: 'bg-[#ffbd12] text-[#17324d] hover:bg-[#e5a800]',
  };
  return <a href={href} className={`inline-flex items-center justify-center rounded-full px-4 py-2 text-xs font-bold shadow-sm transition ${tones[tone]}`}>{children}</a>;
}

function SectionHeading({ eyebrow, title, action }) {
  const sectionIds = { 'About Our School': 'about', Academics: 'academics', 'Campus & Infrastructure': 'facilities', 'Photo Gallery': 'gallery', 'Contact & Location': 'contact' };
  const actionTargets = { 'View Curriculum': '#academics', 'View All Faculty': '#faculty', 'View All Photos': '#gallery' };
  return <div id={sectionIds[title]} className="flex items-end justify-between gap-3 border-b border-[#dce8f2] pb-2"><div><p className="text-[9px] font-bold uppercase tracking-[0.18em] text-[#1769a8]">{eyebrow}</p><h2 className="mt-1 text-xl font-bold text-[#17324d]">{title}</h2></div>{action && <a href={actionTargets[action] || '#top'} className="text-[9px] font-semibold text-[#1769a8] underline-offset-2 hover:underline">{action} ↗</a>}</div>;
}

function SchoolLogo({ src }) {
  if (src) return <img src={src} alt="School logo" className="h-10 w-11 shrink-0 object-contain" />;
  return <span className="relative inline-flex h-10 w-11 shrink-0 items-end justify-center" aria-hidden="true"><span className="absolute left-1/2 top-0 -translate-x-1/2 text-lg leading-none text-[#f5b916]">✦</span><span className="absolute bottom-1 left-1 h-5 w-5 -skew-y-6 border-b-2 border-l-2 border-[#0c497d]" /><span className="absolute bottom-1 right-1 h-5 w-5 skew-y-6 border-b-2 border-r-2 border-[#0c497d]" /><span className="absolute bottom-0 left-1/2 h-1 w-9 -translate-x-1/2 rounded-full bg-[#0c497d]" /></span>;
}

export default function SunriseSchoolPage({ place, mapsUrl, socialLinks, academics, onShare, onReport }) {
  const cover = place.coverImage || place.images?.[0];
  const images = place.images || [];
  const aboutImage = academics.aboutImage || images[1] || cover;
  const videos = Array.isArray(place.video) ? place.video : place.video ? [place.video] : [];
  const achievements = academics.achievements?.length ? academics.achievements : ['Best CBSE School Award - 2025', 'District Level Sports Champions - 2025', '100% Board Results - 2024'];
  const events = academics.events?.length ? academics.events : ['Annual Day Celebration', 'Science Exhibition', 'Parent Teacher Meeting'];
  const principal = academics.principal || {};
  const facts = fallbackFacts.map(([label, fallback]) => [label, {
    Board: academics.board, Established: academics.establishedYear, Classes: academics.classes,
    Gender: academics.gender, Medium: academics.medium, Type: academics.type,
    Ratio: academics.studentTeacherRatio, Rating: place.rating?.average ? `${place.rating.average} / 5` : null,
  }[label] || fallback]);
  const facilities = academics.schoolFacilities?.length ? academics.schoolFacilities : (place.facilities?.length ? place.facilities : ['School Bus', 'Medical Facility', 'Library', 'CCTV', 'Computer Lab', 'Smart Classes', 'Science Lab', 'Cafeteria', 'Sports', 'Security']);
  const infrastructure = academics.infrastructure || [];
  const faculty = academics.faculty?.length ? academics.faculty : ['Mrs. Anitha Reddy', 'Mr. Suresh Kumar', 'Priya Sharma', 'Ramesh Babu'];
  const whatsapp = socialLinks.whatsapp ? (socialLinks.whatsapp.startsWith('http') ? socialLinks.whatsapp : `https://wa.me/${socialLinks.whatsapp.replace(/\D/g, '')}`) : null;

  return <div className="school-site bg-[#f7fbff] text-[#17324d]">
    <header className="sticky top-0 z-30 border-b border-[#dce8f2] bg-white/95 shadow-sm backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-8"><a href="#top" className="flex items-center gap-2"><SchoolLogo src={place.logo} /><span><strong className="block text-sm text-[#12395a]">{place.name || 'Sunrise Public School'}</strong><small className="text-[9px] text-[#587087]">Learn · Grow · Succeed</small></span></a><nav className="hidden items-center gap-5 text-[10px] font-semibold text-[#31536d] lg:flex"><a href="#top">Home</a><a href="#about">About</a><a href="#academics">Academics</a><a href="#facilities">Facilities</a><a href="#gallery">Gallery</a><a href="#reviews">Reviews</a><a href="#contact">Contact</a></nav><a href={`tel:${place.phone || ''}`} className="rounded-full bg-[#12395a] px-4 py-2 text-[10px] font-bold text-white">Call Now</a></div></header>
    <section id="top" className="relative min-h-[330px] overflow-hidden bg-[#12395a] sm:min-h-[390px]">
      {cover && <img src={cover} alt={`${place.name} campus`} className="absolute inset-0 h-full w-full object-cover" />}
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(6,32,58,.94),rgba(6,43,76,.64)_48%,rgba(6,43,76,.12))]" />
      <div className="relative mx-auto flex min-h-[330px] max-w-7xl flex-col justify-center px-5 py-10 sm:min-h-[390px] sm:px-8">
        <p className="text-xs font-bold uppercase tracking-[0.18em] text-[#ffd45a]">Welcome to</p>
        <h1 className="mt-2 max-w-xl text-4xl font-extrabold leading-tight text-white sm:text-6xl">{place.name || 'Sunrise Public School'}</h1>
        <p className="mt-3 max-w-lg text-sm leading-relaxed text-white/85">{place.description || 'Building bright futures through quality education, strong values and holistic development.'}</p>
        <div className="mt-5 flex flex-wrap gap-2"><ActionButton href={`tel:${place.phone || ''}`}>☎ Call Now</ActionButton>{whatsapp && <ActionButton href={whatsapp} tone="green">◉ WhatsApp</ActionButton>}<ActionButton href={mapsUrl} tone="light">⌖ Get Directions</ActionButton>{place.website && <ActionButton href={place.website.startsWith('http') ? place.website : `https://${place.website}`} tone="light">↗ Visit Website</ActionButton>}</div>
      </div>
    </section>

    <main className="mx-auto max-w-7xl px-4 py-4 sm:px-8 sm:py-6">
      <section className="grid grid-cols-2 overflow-hidden rounded border border-[#d9e9f6] bg-white shadow-sm sm:grid-cols-4 lg:grid-cols-8">{facts.map(([label, value]) => <div key={label} className="border-b border-r border-[#e5eff7] px-3 py-3 text-center last:border-r-0 sm:border-b-0"><div className="text-base font-extrabold text-[#1769a8]">{value}</div><div className="mt-1 text-[9px] font-semibold text-[#5f7890]">{label}</div></div>)}</section>

      <section className="mt-5 grid gap-5 lg:grid-cols-[1.12fr_.88fr]">
        <div className="rounded border border-[#d9e9f6] bg-white p-4 sm:p-6"><SectionHeading eyebrow="A legacy of excellence" title="About Our School" /><div className="mt-4 grid gap-4 sm:grid-cols-[1fr_250px]"><div><p className="text-xs leading-relaxed text-[#587087]">{place.description || 'Sunrise Public School is a leading CBSE school committed to providing high-quality education and nurturing young minds. Our goal is to create confident, responsible and successful individuals who contribute positively to society.'}</p><button type="button" onClick={onShare} className="mt-4 rounded bg-[#12395a] px-4 py-2 text-[10px] font-bold text-white">Read More</button></div>{aboutImage && <img src={aboutImage} alt="School campus" className="h-32 w-full rounded object-cover" />}</div></div>
        <div className="rounded border border-[#d9e9f6] bg-white p-4 sm:p-6"><SectionHeading eyebrow="What guides us" title="Our Vision & Mission" /><div className="mt-4 space-y-4 text-xs leading-relaxed text-[#587087]"><div><strong className="text-[#17324d]">◉ Our Vision</strong><p className="mt-1">{academics.vision || 'To be a centre of excellence in education and character building.'}</p></div><div><strong className="text-[#17324d]">◉ Our Mission</strong><p className="mt-1">{academics.mission || 'To provide a safe, supportive and innovative learning environment for every child.'}</p></div></div></div>
      </section>

      <section className="mt-5 grid gap-5 lg:grid-cols-[1fr_1fr]"><div className="rounded border border-[#d9e9f6] bg-[#f3f9fe] p-4 sm:p-6"><SectionHeading eyebrow="Strong foundation for a brighter future" title="Academics" action="View Curriculum" /><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{(academics.classes || 'Nursery, Class 1–5, Class 6–8, Class 9–10').split(',').map((item) => <div key={item} className="rounded border border-[#d9e9f6] bg-white p-3 text-center text-[10px] font-bold text-[#31536d]">▣<br /><span className="mt-2 inline-block">{item.trim()}</span></div>)}</div>{academics.curriculum && <p className="mt-4 text-xs text-[#587087]">{academics.curriculum}</p>}</div><div id="faculty" className="rounded border border-[#d9e9f6] bg-[#f3f9fe] p-4 sm:p-6"><SectionHeading eyebrow="Experienced. Dedicated. Caring." title="Our Faculty" action="View All Faculty" /><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{faculty.map((member, index) => { const details = typeof member === 'object' ? member : { name: member }; const photo = details.photo || details.image || academics.facultyImages?.[index]; return <div key={`${details.name}-${index}`} className="rounded border border-[#d9e9f6] bg-white p-2 text-center text-[9px] font-bold text-[#31536d]">{photo ? <img src={photo} alt={details.name} className="mx-auto mb-2 h-12 w-12 rounded-full object-cover" /> : <div className="mx-auto mb-2 flex h-12 w-12 items-center justify-center rounded-full bg-[#e6edf2] text-lg">{index % 2 ? '👨' : '👩'}</div>}{details.name}<br /><span className="font-normal text-[#7890a3]">{details.designation || 'Faculty'}</span></div>; })}</div></div></section>

      <section className="mt-5 rounded border border-[#d9e9f6] bg-white p-4 sm:p-6"><SectionHeading eyebrow="Modern facilities for a better learning experience" title="Campus & Infrastructure" /><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{facilities.slice(0, 10).map((item, index) => { const details = typeof item === 'object' ? item : { name: item }; const photo = details.image || details.photo || academics.facilityImages?.[index] || images[index % Math.max(images.length, 1)]; return <div key={`${details.name}-${index}`} className="rounded border border-[#d9e9f6] bg-[#f5faff] p-3 text-[10px] font-bold text-[#31536d]">{photo ? <img src={photo} alt={details.name} className="mb-2 h-24 w-full rounded object-cover" /> : <div className="mb-2 flex h-12 items-center justify-center rounded bg-[#dcecf6] text-2xl">{details.icon || '▦'}</div>}<p>{details.name}</p>{details.description && <p className="mt-1 font-normal leading-relaxed text-[#587087]">{details.description}</p>}</div>; })}</div></section>
      {infrastructure.length > 0 && <section className="mt-5 rounded border border-[#d9e9f6] bg-white p-4 sm:p-6"><SectionHeading eyebrow="Spaces built for learning" title="Infrastructure" /><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{infrastructure.map((item, index) => { const details = typeof item === 'object' ? item : { name: item }; const photo = details.image || details.photo || academics.infrastructureImages?.[index]; return <div key={`${details.name}-${index}`} className="overflow-hidden rounded border border-[#d9e9f6] bg-[#f5faff] text-xs text-[#31536d]">{photo && <img src={photo} alt={details.name} className="h-28 w-full object-cover" />}<div className="p-3"><p className="font-bold">{details.name}</p>{details.description && <p className="mt-1 text-[#587087]">{details.description}</p>}</div></div>; })}</div></section>}

      <section className="mt-5 grid gap-5 lg:grid-cols-[1fr_1fr]"><div className="rounded border border-[#d9e9f6] bg-white p-4 sm:p-6"><SectionHeading eyebrow="Moments that inspire" title="Photo Gallery" action="View All Photos" /><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{images.slice(0, 8).map((image, index) => <img key={`${image}-${index}`} src={image} alt={`${place.name} gallery ${index + 1}`} className="h-20 w-full rounded object-cover" />)}</div>{!images.length && <p className="mt-4 text-xs text-[#7890a3]">Campus photos will be added soon.</p>}</div><div className="rounded border border-[#d9e9f6] bg-white p-4 sm:p-6"><SectionHeading eyebrow="Plan your next step" title="Admissions & Fee Information" /><div className="mt-4 space-y-2 text-xs leading-relaxed text-[#587087]"><p><strong className="text-[#17324d]">Process:</strong> {academics.admissionProcess || 'Submit the enquiry form and visit the school office.'}</p><p><strong className="text-[#17324d]">Eligibility:</strong> {academics.eligibility || 'As per CBSE norms and age criteria.'}</p><p><strong className="text-[#17324d]">Fees:</strong> {academics.feeInformation || 'Fee structure available on enquiry.'}</p></div><a href={`tel:${place.phone || ''}`} className="mt-4 inline-flex rounded-full bg-[#ffbd12] px-5 py-2 text-xs font-bold text-[#17324d]">Enquire for Admission</a></div></section>

      <section id="reviews" className="mt-5 rounded border border-[#d9e9f6] bg-white p-4 sm:p-6"><ReviewsSection placeId={place._id} /></section>
      <section className="mt-5 grid gap-5 lg:grid-cols-3"><div className="rounded border border-[#f3dfae] bg-[#fffaf0] p-4 sm:p-6"><SectionHeading eyebrow="Proud moments" title="Achievements" />{achievements.map((item, index) => { const details = typeof item === 'object' ? item : { title: item }; return <div key={`${details.title || details.name}-${index}`} className="mt-3 text-xs text-[#587087]">{details.image && <img src={details.image} alt="" className="mb-2 h-20 w-full rounded object-cover" />}🏆 {details.title || details.name}{details.description && <p className="mt-1">{details.description}</p>}</div>; })}</div><div className="rounded border border-[#cfe6e5] bg-[#f1fbf8] p-4 sm:p-6"><SectionHeading eyebrow="Life on campus" title="Events" />{events.map((item, index) => { const details = typeof item === 'object' ? item : { name: item }; const photo = details.image || academics.eventImages?.[index]; return <div key={`${details.name || details.title}-${index}`} className="mt-3 text-xs text-[#587087]">{photo && <img src={photo} alt="" className="mb-2 h-20 w-full rounded object-cover" />}📅 {details.name || details.title}{details.date && <span className="ml-1">· {details.date}</span>}{details.description && <p className="mt-1">{details.description}</p>}</div>; })}</div><div className="rounded border border-[#d9e9f6] bg-[#f3f9fe] p-4 sm:p-6"><SectionHeading eyebrow="Principal" title="School Leadership" />{academics.principalImage && <img src={academics.principalImage} alt="Principal" className="mb-3 h-20 w-20 rounded-full object-cover" />}<h3 className="text-lg font-bold text-[#17324d]">{principal.name || 'School Principal'}</h3><p className="mt-1 text-xs font-semibold text-[#1769a8]">{principal.designation || 'Principal'}{principal.experience ? ` · ${principal.experience}` : ''}</p>{principal.qualification && <p className="mt-1 text-xs text-[#587087]">{principal.qualification}</p>}<p className="mt-3 text-xs leading-relaxed text-[#587087]">{academics.principalMessage || principal.message || 'Our principal leads with care, purpose, and a commitment to every learner.'}</p></div></section>
      {videos.length > 0 && <section className="mt-5 rounded border border-[#d9e9f6] bg-white p-4 sm:p-6"><SectionHeading eyebrow="See our school in action" title="Videos" /><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{videos.map((video, index) => <video key={`${video}-${index}`} src={video} controls className="h-40 w-full rounded bg-[#062b4d] object-cover" />)}</div></section>}
      <section className="mt-5 grid gap-5 lg:grid-cols-[1fr_1fr]"><div className="rounded border border-[#d9e9f6] bg-white p-4 sm:p-6"><SectionHeading eyebrow="Get in touch" title="Contact & Location" /><div className="mt-4 space-y-2 text-xs text-[#587087]"><p>⌖ {place.address}</p>{place.phone && <a href={`tel:${place.phone}`} className="block">☎ {place.phone}</a>}{place.email && <a href={`mailto:${place.email}`} className="block">✉ {place.email}</a>}</div><button type="button" onClick={onReport} className="mt-4 text-[10px] font-bold text-[#1769a8]">Report incorrect information</button></div><div className="overflow-hidden rounded border border-[#d9e9f6] bg-white"><iframe title={`Map showing ${place.name}`} src={`https://www.google.com/maps?q=${encodeURIComponent(place.address)}&output=embed`} className="h-56 w-full border-0" loading="lazy" /></div></section>
    </main>
    <footer className="bg-[#062b4d] px-4 py-5 text-white sm:px-8"><div className="mx-auto grid max-w-7xl grid-cols-1 items-center gap-4 text-center sm:grid-cols-3 sm:text-left"><div><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-white/60">Follow Us</p><div className="mt-2 flex justify-center gap-2 sm:justify-start"><a href={socialLinks.facebook || '#contact'} className="flex h-6 w-6 items-center justify-center rounded-full bg-[#1769a8] text-[9px] font-bold">f</a><a href={socialLinks.instagram || '#contact'} className="flex h-6 w-6 items-center justify-center rounded-full bg-[#e34c69] text-[9px] font-bold">◎</a><a href={socialLinks.linkedin || '#contact'} className="flex h-6 w-6 items-center justify-center rounded-full bg-[#168b9a] text-[9px] font-bold">in</a></div></div><div className="flex flex-col items-center"><SchoolLogo src={place.logo} /><strong className="-mt-1 text-xs">{place.name || 'Sunrise Public School'}</strong><small className="text-[9px] text-white/60">Learn · Grow · Succeed</small></div><p className="text-[9px] text-white/50 sm:text-right">© {new Date().getFullYear()} {place.name || 'Sunrise Public School'}. All rights reserved.</p></div></footer>
  </div>;
}
