import React from 'react';

const types = ['Private University', 'Public University', 'Deemed University', 'Autonomous Institution', 'Other'];
const defaultFacilities = ['Hostel', 'Library', 'Sports', 'Wi-Fi', 'Cafeteria', 'Auditorium', 'Laboratory', 'Transportation', 'Gym', 'Medical Facility'];

function Section({ number, title, children }) {
  return <section className="rounded-xl border border-[#c9ddf1] bg-white p-5 shadow-sm sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#1769a8]">{number}</p><h2 className="mt-1 font-display text-xl font-semibold text-[#12395a]">{title}</h2><div className="mt-4 grid grid-cols-2 gap-4">{children}</div></section>;
}

function Field({ label, field, form, setForm, inputClass, ...props }) {
  return <label className="col-span-2 text-sm text-ink/70 sm:col-span-1">{label}<input value={form[field] || ''} onChange={(e) => setForm.length > 1 ? setForm(field, e.target.value) : setForm((current) => ({ ...current, [field]: e.target.value }))} className={inputClass} {...props} /></label>;
}

export default function UniversityRegistrationFields({ form, setForm, inputClass, logoFile, setLogoFile, coverFile, setCoverFile, aboutImageFile, setAboutImageFile, galleryFiles, setGalleryFiles, schoolVideos, setSchoolVideos }) {
  const update = (field) => (e) => setForm((current) => ({ ...current, [field]: e.target.value }));
  const university = form.university || {};
  const setUniversity = (field, value) => setForm((current) => ({ ...current, university: { ...(current.university || {}), [field]: value } }));
  const highlights = university.highlights || [];
  const programs = university.programs || [];
  const facilities = university.facilities || [];
  const stats = university.stats || [];
  const toggle = (field, value) => setUniversity(field, (university[field] || []).includes(value) ? university[field].filter((item) => item !== value) : [...(university[field] || []), value]);
  const add = (field, item) => setUniversity(field, [...(university[field] || []), item]);
  const change = (field, index, key, value) => setUniversity(field, (university[field] || []).map((item, itemIndex) => itemIndex === index ? (key ? { ...item, [key]: value } : value) : item));
  const remove = (field, index) => setUniversity(field, (university[field] || []).filter((_, itemIndex) => itemIndex !== index));
  const updateVideo = (index, field, value) => setSchoolVideos((items) => items.map((entry, entryIndex) => entryIndex === index ? { ...entry, [field]: value } : entry));

  return <div className="col-span-2 space-y-5">
    <div className="rounded-xl border border-[#1769a8]/25 bg-[#eef7ff] p-5 sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#1769a8]">University business page</p><h2 className="mt-2 font-display text-2xl font-semibold text-[#12395a]">Create the university website shown in the preview</h2><p className="mt-2 text-sm text-[#587087]">Complete any sections you need. Empty optional sections stay hidden on the public page.</p></div>
    <Section number="1. Basic university details" title="University identity"><label className="col-span-2 text-sm text-ink/70 sm:col-span-1">University logo *<input required type="file" accept="image/*" onChange={(e) => setLogoFile(e.target.files?.[0] || null)} className={inputClass} /></label><Field label="University name *" field="name" form={form} setForm={setForm} inputClass={inputClass} required placeholder="Green Valley University" /><Field label="Tagline" field="tagline" form={form} setForm={setForm} inputClass={inputClass} placeholder="Learn | Grow | Build Your Future" /><label className="col-span-2 text-sm text-ink/70 sm:col-span-1">University type *<select required value={university.type || ''} onChange={(e) => setUniversity('type', e.target.value)} className={inputClass}><option value="">Select type</option>{types.map((type) => <option key={type}>{type}</option>)}</select></label><Field label="Established year" field="establishedYear" form={form} setForm={setForm} inputClass={inputClass} type="number" placeholder="2001" /><label className="col-span-2 text-sm text-ink/70">Short description<textarea value={form.description} onChange={update('description')} rows={4} className={inputClass} /></label></Section>
    <Section number="2. Hero / cover section" title="Campus hero"><label className="col-span-2 text-sm text-ink/70">Cover image *<input required type="file" accept="image/*" onChange={(e) => setCoverFile(e.target.files?.[0] || null)} className={inputClass} /></label><Field label="Welcome text" field="heroWelcome" form={form} setForm={setForm} inputClass={inputClass} placeholder="WELCOME TO" /><Field label="Hero heading" field="heroHeading" form={form} setForm={setForm} inputClass={inputClass} /><Field label="Hero subheading" field="heroSubheading" form={form} setForm={setForm} inputClass={inputClass} placeholder="Where Knowledge Meets Opportunity" /><Field label="Primary button text" field="primaryButtonText" form={form} setForm={setForm} inputClass={inputClass} placeholder="Apply Now" /><Field label="Primary button link" field="primaryButtonLink" form={form} setForm={setForm} inputClass={inputClass} placeholder="https://..." /><Field label="Secondary button text" field="secondaryButtonText" form={form} setForm={setForm} inputClass={inputClass} placeholder="Watch Campus Tour" /><Field label="Secondary button link" field="secondaryButtonLink" form={form} setForm={setForm} inputClass={inputClass} placeholder="https://..." /></Section>
    <Section number="3. University statistics" title="Stats"><div className="col-span-2 flex justify-end"><button type="button" onClick={() => add('stats', { number: '', label: '' })} className="rounded-full bg-[#147eff] px-4 py-2 text-xs font-bold text-white">+ Add Statistic</button></div>{stats.map((item, index) => <div key={index} className="col-span-2 grid grid-cols-2 gap-3 rounded-lg border border-[#d8e7fa] p-4"><Field label="Number" field="number" form={item} setForm={(_, value) => change('stats', index, 'number', value)} inputClass={inputClass} /><Field label="Label" field="label" form={item} setForm={(_, value) => change('stats', index, 'label', value)} inputClass={inputClass} /><button type="button" onClick={() => remove('stats', index)} className="col-span-2 text-left text-xs font-bold text-vermilion">Remove statistic</button></div>)}</Section>
    <Section number="4. About university" title="About section"><Field label="About title" field="aboutTitle" form={university} setForm={(_, value) => setUniversity('aboutTitle', value)} inputClass={inputClass} placeholder="About Green Valley University" /><label className="col-span-2 text-sm text-ink/70 sm:col-span-1">About image<input type="file" accept="image/*" onChange={(e) => setAboutImageFile(e.target.files?.[0] || null)} className={inputClass} /></label><label className="col-span-2 text-sm text-ink/70">About description<textarea value={university.aboutDescription || form.description || ''} onChange={(e) => setUniversity('aboutDescription', e.target.value)} rows={4} className={inputClass} /></label><div className="col-span-2"><p className="text-sm font-semibold text-ink/70">Key highlights</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{highlights.map((item, index) => <div key={index} className="flex gap-2"><input value={item} onChange={(e) => change('highlights', index, null, e.target.value)} className={inputClass} /><button type="button" onClick={() => remove('highlights', index)} className="px-2 text-vermilion">×</button></div>)}</div><button type="button" onClick={() => add('highlights', '')} className="mt-2 text-xs font-bold text-[#147eff]">+ Add Highlight</button></div><Field label="Button text" field="aboutButtonText" form={university} setForm={(_, value) => setUniversity('aboutButtonText', value)} inputClass={inputClass} placeholder="Know More" /><Field label="Button link" field="aboutButtonLink" form={university} setForm={(_, value) => setUniversity('aboutButtonLink', value)} inputClass={inputClass} /></Section>
    <Section number="5. Programs / courses" title="Programs"><div className="col-span-2 flex justify-end"><button type="button" onClick={() => add('programs', { name: '', description: '', link: '', category: '' })} className="rounded-full bg-[#147eff] px-4 py-2 text-xs font-bold text-white">+ Add Program</button></div>{programs.map((item, index) => <div key={index} className="col-span-2 grid grid-cols-2 gap-3 rounded-lg border border-[#d8e7fa] p-4"><Field label="Program name *" field="name" form={item} setForm={(_, value) => change('programs', index, 'name', value)} inputClass={inputClass} required /><Field label="Category" field="category" form={item} setForm={(_, value) => change('programs', index, 'category', value)} inputClass={inputClass} /><label className="col-span-2 text-sm text-ink/70">Short description<textarea value={item.description || ''} onChange={(e) => change('programs', index, 'description', e.target.value)} rows={2} className={inputClass} /></label><Field label="Details link" field="link" form={item} setForm={(_, value) => change('programs', index, 'link', value)} inputClass={inputClass} /><button type="button" onClick={() => remove('programs', index)} className="col-span-2 text-left text-xs font-bold text-vermilion">Remove program</button></div>)}</Section>
    <Section number="6. University information" title="Contact details"><Field label="University type" field="type" form={university} setForm={(_, value) => setUniversity('type', value)} inputClass={inputClass} /><Field label="City / location" field="city" form={university} setForm={(_, value) => setUniversity('city', value)} inputClass={inputClass} /><Field label="State" field="state" form={university} setForm={(_, value) => setUniversity('state', value)} inputClass={inputClass} /><Field label="Country" field="country" form={university} setForm={(_, value) => setUniversity('country', value)} inputClass={inputClass} /><label className="col-span-2 text-sm text-ink/70">Full address<input value={form.address} onChange={update('address')} className={inputClass} /></label><Field label="Website URL" field="website" form={form} setForm={setForm} inputClass={inputClass} /><Field label="Contact number" field="phone" form={form} setForm={setForm} inputClass={inputClass} /><Field label="Email ID" field="email" form={form} setForm={setForm} inputClass={inputClass} /></Section>
    <Section number="7. Facilities & campus life" title="Facilities"><div className="col-span-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{defaultFacilities.map((item) => <label key={item} className="flex items-center gap-2 rounded border border-[#d8e7fa] p-2 text-sm"><input type="checkbox" checked={facilities.includes(item)} onChange={() => toggle('facilities', item)} />{item}</label>)}</div><Field label="Campus life title" field="campusTitle" form={university} setForm={(_, value) => setUniversity('campusTitle', value)} inputClass={inputClass} placeholder="More Than Just a University" /><label className="col-span-2 text-sm text-ink/70">Campus life description<textarea value={university.campusDescription || ''} onChange={(e) => setUniversity('campusDescription', e.target.value)} rows={3} className={inputClass} /></label><label className="col-span-2 text-sm text-ink/70">Campus images<input type="file" accept="image/*" multiple onChange={(e) => setGalleryFiles(Array.from(e.target.files || []))} className={inputClass} /></label></Section>
    <Section number="8. Videos" title="Campus videos"><div className="col-span-2 flex justify-end"><button type="button" onClick={() => setSchoolVideos((items) => [...items, { title: '', type: 'youtube', url: '', file: null }])} className="rounded-full bg-[#147eff] px-4 py-2 text-xs font-bold text-white">+ Add Video</button></div>{schoolVideos.map((item, index) => <div key={index} className="col-span-2 grid grid-cols-2 gap-3 rounded-lg border border-[#d8e7fa] p-4"><Field label="Video title" field="title" form={item} setForm={(_, value) => updateVideo(index, 'title', value)} inputClass={inputClass} /><label className="text-sm text-ink/70">Source<select value={item.type} onChange={(e) => updateVideo(index, 'type', e.target.value)} className={inputClass}><option value="youtube">YouTube URL</option><option value="upload">Upload from device</option><option value="url">Direct video URL</option></select></label>{item.type === 'upload' ? <label className="col-span-2 text-sm text-ink/70">Video file<input type="file" accept="video/*" onChange={(e) => updateVideo(index, 'file', e.target.files?.[0] || null)} className={inputClass} /></label> : <label className="col-span-2 text-sm text-ink/70">Video URL<input value={item.url || ''} onChange={(e) => updateVideo(index, 'url', e.target.value)} className={inputClass} /></label>}<button type="button" onClick={() => setSchoolVideos((items) => items.filter((_, entryIndex) => entryIndex !== index))} className="col-span-2 text-left text-xs font-bold text-vermilion">Remove video</button></div>)}</Section>
    <Section number="9. Social media & contact" title="Optional links"><Field label="WhatsApp" field="whatsapp" form={form} setForm={setForm} inputClass={inputClass} /><Field label="Facebook" field="facebook" form={form} setForm={setForm} inputClass={inputClass} /><Field label="Instagram" field="instagram" form={form} setForm={setForm} inputClass={inputClass} /><Field label="LinkedIn" field="linkedin" form={form} setForm={setForm} inputClass={inputClass} /></Section>
    <Section number="10. Ranking / recognition" title="Recognition"><label className="col-span-2 flex items-center gap-2 text-sm"><input type="checkbox" checked={university.rankingEnabled === true} onChange={(e) => setUniversity('rankingEnabled', e.target.checked)} /> Enable ranking card</label><Field label="Rank" field="rank" form={university} setForm={(_, value) => setUniversity('rank', value)} inputClass={inputClass} placeholder="#12" /><Field label="Ranking year" field="rankingYear" form={university} setForm={(_, value) => setUniversity('rankingYear', value)} inputClass={inputClass} /><Field label="Ranking organization" field="rankingOrganization" form={university} setForm={(_, value) => setUniversity('rankingOrganization', value)} inputClass={inputClass} /><label className="col-span-2 text-sm text-ink/70">Ranking description<textarea value={university.rankingDescription || ''} onChange={(e) => setUniversity('rankingDescription', e.target.value)} rows={2} className={inputClass} /></label></Section>
    <Section number="11. Location & maps" title="Map details"><label className="col-span-2 text-sm text-ink/70">Google Maps URL<input value={university.mapsUrl || ''} onChange={(e) => setUniversity('mapsUrl', e.target.value)} className={inputClass} /></label><label className="col-span-2 text-sm text-ink/70">Google Maps embed URL<input value={university.mapEmbedUrl || ''} onChange={(e) => setUniversity('mapEmbedUrl', e.target.value)} className={inputClass} /></label></Section>
    <Section number="12. Admissions / CTA" title="Admission banner"><label className="col-span-2 flex items-center gap-2 text-sm"><input type="checkbox" checked={university.showAdmission !== false} onChange={(e) => setUniversity('showAdmission', e.target.checked)} /> Show admission section</label><Field label="Title" field="admissionTitle" form={university} setForm={(_, value) => setUniversity('admissionTitle', value)} inputClass={inputClass} placeholder="Admissions Open" /><label className="col-span-2 text-sm text-ink/70">Description<textarea value={university.admissionDescription || ''} onChange={(e) => setUniversity('admissionDescription', e.target.value)} rows={2} className={inputClass} /></label><Field label="Button text" field="admissionButtonText" form={university} setForm={(_, value) => setUniversity('admissionButtonText', value)} inputClass={inputClass} placeholder="Apply Now" /><Field label="Application URL" field="admissionUrl" form={university} setForm={(_, value) => setUniversity('admissionUrl', value)} inputClass={inputClass} /></Section>
  </div>;
}
