import React from 'react';
import ReviewsSection from './ReviewsSection';

const nav = [['⌂', 'Home', '#top'], ['▥', 'About Us', '#about'], ['▣', 'Academics', '#programs'], ['◉', 'Admissions', '#admissions'], ['♟', 'Campus Life', '#campus'], ['▤', 'Gallery', '#gallery'], ['✉', 'Contact', '#contact']];
const colours = ['bg-[#e3f2ff] text-[#0966d8]', 'bg-[#f1e8ff] text-[#7c31d1]', 'bg-[#e6f8eb] text-[#09934d]', 'bg-[#fff0df] text-[#d46707]', 'bg-[#dff9fb] text-[#008a9a]'];
function Header({ icon, title, action }) { return <div className="flex items-center justify-between border-b border-[#d8e7fa] pb-2"><h2 className="flex items-center gap-2 text-base font-bold text-[#063b7d]"><span className="rounded bg-[#0b67cc] px-1.5 py-1 text-xs text-white">{icon}</span>{title}</h2>{action && <a href={action} className="text-[10px] font-bold text-[#0966d8]">View All →</a>}</div>; }

export default function UniversityPage({ place, mapsUrl, onShare, onReport }) {
  const rawData = place.attributes || {};
  const data = { ...rawData, ...(rawData.university || {}) };
  const programs = data.programs || data.collegePrograms || data.courses || [];
  const facilities = data.facilities || data.collegeFacilities || place.facilities || [];
  const stats = data.stats || [];
  const gallery = place.images || [];
  const faculty = data.faculty || [];
  const logo = place.logo;
  const campusImage = place.coverImage || gallery[0];
  const city = place.location?.city?.name || 'Your City';
  const website = place.website?.startsWith('http') ? place.website : place.website ? `https://${place.website}` : null;
  return <div className="min-h-screen bg-[#f6fbff] text-[#063b7d] lg:pl-[196px]">
    <aside className="fixed inset-y-0 left-0 z-40 hidden w-[196px] flex-col bg-[linear-gradient(160deg,#032b57,#064b91_56%,#032b57)] px-3 py-5 text-white lg:flex"><div className="flex flex-col items-center text-center">{logo ? <img src={logo} alt={`${place.name} logo`} className="h-12 w-12 rounded-lg bg-white object-contain p-1" /> : <span className="text-4xl">🎓</span>}<strong className="mt-2 text-sm">{place.name}</strong><small className="mt-1 text-[10px] text-white/85">{data.tagline || 'Learn | Grow | Your Future'}</small></div><nav className="mt-7 space-y-2">{nav.map(([icon, label, href], index) => <a key={label} href={href} className={`flex items-center gap-3 rounded-md px-3 py-2.5 text-xs font-semibold ${index === 0 ? 'bg-[#0878ff] shadow-lg' : 'hover:bg-white/10'}`}><span className="text-lg">{icon}</span>{label}</a>)}</nav><div className="mt-auto rounded-lg bg-white/5 p-3 text-center"><p className="font-display text-xl italic">Your Future<br />Starts Here</p>{campusImage && <img src={campusImage} alt="Campus" className="mt-3 h-24 w-full rounded object-cover opacity-80" />}</div></aside>
    <header className="sticky top-0 z-30 border-b border-[#d8e7fa] bg-white/95 shadow-sm backdrop-blur"><div className="mx-auto flex h-16 max-w-[1400px] items-center gap-4 px-5"><div className="flex items-center gap-3">{logo && <img src={logo} alt="University logo" className="h-10 w-10 object-contain" />}<strong className="max-w-[190px] text-lg leading-tight">{place.name}</strong></div><nav className="ml-auto hidden gap-6 text-[10px] font-bold xl:flex">{nav.map(([, label, href]) => <a key={label} href={href}>{label}</a>)}</nav><div className="hidden rounded-full bg-[#eef5ff] px-4 py-2 text-[10px] text-[#7690ad] md:block">Search here...　⌕</div><a href="#admissions" className="rounded-full bg-[#0878ff] px-5 py-2.5 text-xs font-bold text-white shadow">Apply Now →</a></div></header>
    <main className="mx-auto max-w-[1400px] p-4 sm:p-5"><section id="top" className="relative min-h-[270px] overflow-hidden rounded-lg bg-[#053a76]">{campusImage && <img src={campusImage} alt={`${place.name} campus`} className="absolute inset-0 h-full w-full object-cover" />}<div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(0,33,70,.91),rgba(0,47,95,.48),transparent)]" /><div className="relative flex min-h-[270px] max-w-2xl flex-col justify-center p-7 text-white"><p className="text-xs font-bold tracking-[.18em]">WELCOME TO</p><h1 className="mt-1 text-4xl font-extrabold leading-none sm:text-5xl">{place.name}</h1><h2 className="mt-3 text-xl font-semibold">{data.tagline || 'Where Knowledge Meets Opportunity'}</h2><p className="mt-2 max-w-lg text-sm">{place.description || 'We provide world-class education, modern infrastructure and a vibrant campus life to help you achieve your dreams.'}</p><div className="mt-5 flex gap-3"><a href="#admissions" className="rounded-full bg-[#0878ff] px-5 py-3 text-xs font-bold">Apply Now →</a><a href="#gallery" className="rounded-full border border-white px-5 py-3 text-xs font-bold">▶ Watch Campus Tour</a></div></div></section>
      {stats.length > 0 && <section className="my-4 grid grid-cols-2 divide-x divide-y divide-[#cadcf2] overflow-hidden rounded-xl border border-[#d8e7fa] bg-white shadow-sm sm:grid-cols-4 sm:divide-y-0">{stats.map((stat, index) => <div key={`${stat.label}-${index}`} className="flex items-center justify-center gap-3 p-4"><span className="text-3xl text-[#0b67cc]">{['🎓', '👥', '♟', '▦'][index % 4]}</span><div><strong className="text-xl">{stat.number}</strong><p className="text-[10px]">{stat.label}</p></div></div>)}</section>}
      <div className="grid gap-4 xl:grid-cols-[1.55fr_.95fr]"><div className="space-y-4"><section id="about" className="rounded-xl border border-[#d8e7fa] bg-white p-4"><Header icon="▥" title={`About ${place.name}`} /><div className="mt-4 grid gap-4 sm:grid-cols-[1.2fr_.8fr]"><div><p className="text-sm leading-relaxed text-[#315b8c]">{place.description || 'University information will be added soon.'}</p><div className="mt-4 grid grid-cols-2 gap-2 text-[10px] text-[#315b8c]">{['Industry-Focused Curriculum', 'Global Learning Opportunities', 'Experienced Faculty', 'Safe & Inclusive Campus'].map((item) => <p key={item}>●　{item}</p>)}</div><a href="#contact" className="mt-4 inline-block rounded-full bg-[#0865cb] px-4 py-2 text-xs font-bold text-white">Know More →</a></div>{gallery[1] && <img src={gallery[1]} alt="University" className="h-44 w-full rounded-lg object-cover" />}</div></section>
        <section id="programs" className="rounded-xl border border-[#d8e7fa] bg-white p-4"><Header icon="▦" title="Our Programs" action="#programs" /><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-5">{(programs.length ? programs : ['Engineering', 'Management', 'Computer Science', 'Arts & Humanities', 'Science'].map((name) => ({ name }))).slice(0, 5).map((program, index) => <div key={`${program.name}-${index}`} className={`rounded-lg p-3 ${colours[index]}`}><span className="text-2xl">{['⚙', '◈', '▣', '▤', '⚗'][index]}</span><h3 className="mt-3 text-xs font-bold text-[#063b7d]">{program.name}</h3><p className="mt-2 text-[9px] text-[#315b8c]">{program.description || program.subjects || 'Discover, explore, innovate.'}</p><p className="mt-3 text-[10px] font-bold">View Details →</p></div>)}</div></section>
        <section id="campus" className="rounded-xl border border-[#d8e7fa] bg-white p-4"><Header icon="♟" title="Campus Life" /><div className="mt-4 grid gap-4 sm:grid-cols-[.8fr_1.2fr]"><div><h3 className="font-bold">More Than Just a University</h3><p className="mt-2 text-xs leading-relaxed text-[#315b8c]">A vibrant campus with modern facilities, clubs, sports and endless opportunities to grow, learn and make lifelong friends.</p><div className="mt-5 flex flex-wrap gap-2">{facilities.slice(0, 5).map((item) => <span key={item} className="rounded-full bg-[#eef5ff] px-3 py-2 text-[10px]">{item}</span>)}</div></div><div className="grid grid-cols-2 gap-2">{gallery.slice(0, 4).map((image, index) => <img key={`${image}-${index}`} src={image} alt="Campus life" className={`h-24 w-full rounded object-cover ${index === 0 ? 'row-span-2 h-full' : ''}`} />)}</div></div></section>
        {data.showAdmission !== false && <section id="admissions" className="relative overflow-hidden rounded-xl bg-[linear-gradient(110deg,#053a76,#0b67cc)] p-6 text-white">{gallery[2] && <img src={gallery[2]} alt="Students" className="absolute inset-y-0 right-0 h-full w-1/2 object-cover opacity-50" />}<div className="relative max-w-md"><h2 className="text-2xl font-bold">{data.admissionTitle || 'Admissions Open'}</h2><p className="mt-2 text-sm">{data.admissionDescription || 'Be a part of our growing community. Apply now and take the first step towards a brighter future.'}</p><a href={data.admissionUrl || website || '#contact'} className="mt-4 inline-block rounded-full bg-white px-5 py-2 text-xs font-bold text-[#0865cb]">{data.admissionButtonText || 'Apply Now'} →</a></div></section>}</div>
        <aside className="space-y-4"><section className="rounded-xl border border-[#d8e7fa] bg-white p-4"><Header icon="▦" title="University Information" /><div className="mt-3 space-y-2 text-xs">{[['University Name', place.name], ['Type', data.universityType || data.ownership || 'University'], ['Location', city], ['Address', place.address], ['Website URL', place.website], ['Contact Number', place.phone], ['Email ID', place.email]].map(([label, value]) => <div key={label} className="rounded border border-[#d8e7fa] bg-[#fbfdff] p-2"><small className="block text-[9px] font-bold text-[#315b8c]">{label}</small><span className="break-words text-[10px]">{value || '—'}</span></div>)}</div></section><section className="rounded-xl border border-[#d8e7fa] bg-white p-4"><Header icon="⚙" title="Facilities" /><div className="mt-3 flex flex-wrap gap-2">{facilities.map((item) => <span key={item} className="rounded-full bg-[#eef5ff] px-3 py-1.5 text-[10px]">{item} ↗</span>)}</div></section><section id="gallery" className="rounded-xl border border-[#d8e7fa] bg-white p-4"><Header icon="▤" title="Gallery" /><div className="mt-3 grid grid-cols-3 gap-2">{gallery.slice(0, 6).map((image, index) => <img key={`${image}-${index}`} src={image} alt="University gallery" className="h-16 w-full rounded object-cover" />)}</div></section></aside></div>
      <section className="mt-4 rounded-xl border border-[#d8e7fa] bg-white p-4"><ReviewsSection placeId={place._id} /></section>
      <section id="contact" className="mt-4 rounded-xl border border-[#d8e7fa] bg-white p-4"><Header icon="⌖" title="Contact Us" /><div className="mt-3 flex flex-wrap items-center gap-3 text-xs"><span>{place.address}</span><span>{place.phone}</span><span>{place.email}</span><a href={mapsUrl} target="_blank" rel="noreferrer" className="rounded bg-[#0865cb] px-3 py-2 text-white">Directions</a><button onClick={onShare} className="rounded border border-[#0865cb] px-3 py-2">Share</button><button onClick={onReport}>Report</button></div></section>
    </main><footer className="bg-[#032b57] px-6 py-7 text-white"><div className="mx-auto grid max-w-[1400px] gap-5 sm:grid-cols-3"><div className="flex items-center gap-3">{logo && <img src={logo} alt="Logo" className="h-11 w-11 rounded bg-white object-contain p-1" />}<div><strong>{place.name}</strong><p className="text-[10px] text-white/70">{data.tagline || 'Learn | Grow | Your Future'}</p></div></div><div className="text-xs"><strong>Quick Links</strong><div className="mt-2 grid grid-cols-2 gap-1 text-white/75">{nav.slice(0, 6).map(([, label, href]) => <a key={label} href={href}>{label}</a>)}</div></div><div className="text-xs"><strong>Contact Us</strong><p className="mt-2 text-white/75">{place.phone}<br />{place.email}<br />{place.address}</p></div></div><p className="mx-auto mt-5 max-w-[1400px] border-t border-white/20 pt-3 text-[10px] text-white/60">© {new Date().getFullYear()} {place.name}. All rights reserved.</p></footer>
  </div>;
}
