import React, { useState } from 'react';
import ReviewsSection from '../ReviewsSection';
import { getProfileData, PublicVideoCard, safeUrl } from './PublicProfileShared';
import { getWhatsAppUrl } from '../../utils/healthcare';
import api from '../../services/api';

const icons = { 'Luxury Rooms': '▣', 'Delicious Dining': '♨', 'Swimming Pool': '≋', 'Free Wi-Fi': '⌁', 'Ample Parking': '▰', '24/7 Service': '◷', 'Premium Stay': '✦', 'Multi-Cuisine Restaurant': '♨', 'High-Speed Wi-Fi': '⌁', 'Family Friendly': '♧', 'Room Service': '♙', 'Airport Pickup': '↗', Housekeeping: '⌂', Concierge: '◎', 'Travel Desk': '✧', 'Conference Booking': '▤', 'Banquet Booking': '◇', Spa: '◉', 'Modern Rooms': '▣', 'Banquet Hall': '◇', 'Conference Room': '▤', Elevators: '↕', 'Power Backup': 'ϟ', '24/7 Security': '✓', Restaurant: '♨', Gym: '♢', Garden: '❋' };
const defaults = { amenities: ['Swimming Pool', 'Multi-Cuisine Restaurant', 'Free Wi-Fi', 'Gym & Fitness', 'Spa & Wellness', '24/7 Room Service'], services: ['Room Service', 'Restaurant', 'Airport Pickup', 'Laundry', 'Housekeeping', 'Concierge'], infrastructure: ['Modern Rooms', 'Banquet Hall', 'Conference Room', 'Ample Parking', 'Elevators', '24/7 Security'], highlights: ['Premium Stay', 'Multi-Cuisine Restaurant', 'High-Speed Wi-Fi', 'Ample Parking', 'Family Friendly'] };
const list = (value) => Array.isArray(value) ? value.filter(Boolean) : String(value || '').split(/[\n,]/).map((item) => item.trim()).filter(Boolean);
const first = (...values) => values.find((value) => value !== undefined && value !== null && value !== '');
const asItems = (value, fallback) => Array.isArray(value) && value.length ? value.map((item) => typeof item === 'string' ? { name: item } : item) : fallback.map((name) => ({ name }));
const href = (label) => `#${label.toLowerCase().replace(/[^a-z]+/g, '-')}`;

function Media({ src, alt, label, className = '' }) {
  return src ? <img src={src} alt={alt} className={`h-full w-full object-cover ${className}`} /> : <div className={`grid h-full w-full place-items-center bg-[linear-gradient(135deg,#f5e6c8,#9b7650)] p-5 text-center text-[#402916] ${className}`}><div><span className="text-4xl">✦</span><p className="mt-2 text-xs font-bold uppercase tracking-[.16em]">{label}</p><p className="mt-1 text-xs opacity-70">Hotel owner media placeholder</p></div></div>;
}

function Actions({ label }) {
  const [liked, setLiked] = useState(false);
  const share = async () => navigator.share ? navigator.share({ title: label, url: window.location.href }) : navigator.clipboard?.writeText(window.location.href);
  return <div className="flex flex-wrap gap-1.5 text-[10px] font-bold text-[#6c6258]"><button type="button" onClick={() => setLiked(!liked)} className={`rounded-full border px-2.5 py-1.5 ${liked ? 'border-rose-200 bg-rose-50 text-rose-600' : 'border-[#eadfce] bg-white'}`}>♥ {liked ? 'Liked' : 'Like'}</button><button type="button" onClick={share} className="rounded-full border border-[#eadfce] bg-white px-2.5 py-1.5">↗ Share</button><a href="#contact" className="rounded-full border border-[#eadfce] bg-white px-2.5 py-1.5">💬 Comment</a><a href="#contact" className="rounded-full border border-[#eadfce] bg-white px-2.5 py-1.5">⚑ Report</a></div>;
}

function Floating({ phone, whatsapp, social }) {
  const instagram = safeUrl(social.instagram); const youtube = safeUrl(social.youtube); const call = phone ? `tel:${String(phone).replace(/\s/g, '')}` : '#contact';
  return <div className="fixed right-4 top-1/2 z-40 hidden -translate-y-1/2 flex-col gap-2 md:flex"><a href={whatsapp || '#contact'} target={whatsapp ? '_blank' : undefined} rel="noreferrer" className="grid h-11 w-11 place-items-center rounded-full bg-[#1f9d62] text-white shadow-lg" title="WhatsApp">◉</a><a href={call} className="grid h-11 w-11 place-items-center rounded-full bg-[#1877d2] text-white shadow-lg" title="Call Now">☎</a><a href="#contact" className="grid h-11 w-11 place-items-center rounded-full bg-[#e0a33b] text-[#321f12] shadow-lg" title="Live Chat">⌁</a>{instagram && <a href={instagram} target="_blank" rel="noreferrer" className="grid h-11 w-11 place-items-center rounded-full bg-[#d62976] text-xs font-bold text-white shadow-lg">IG</a>}{youtube && <a href={youtube} target="_blank" rel="noreferrer" className="grid h-11 w-11 place-items-center rounded-full bg-[#f00] text-xs font-bold text-white shadow-lg">▶</a>}</div>;
}

export default function HotelResidencyWebsite({ place }) {
  const profile = getProfileData(place); const specific = place.attributes?.businessProfile?.categorySpecific || {};
  const gallery = (profile.gallery?.length ? profile.gallery : place.images || []).filter(Boolean).slice(0, 10); const social = profile.socialMedia || {};
  const phone = place.phone || profile.phone || ''; const whatsapp = getWhatsAppUrl(social.whatsapp || profile.whatsapp || phone); const call = phone ? `tel:${String(phone).replace(/\s/g, '')}` : '#contact'; const email = place.email || profile.email || '';
  const location = [place.address, place.location?.area?.name, place.location?.city?.name, place.location?.district?.name, place.location?.state?.name, profile.pincode].filter(Boolean).join(', '); const maps = place.coordinates?.lat ? `https://www.google.com/maps/search/?api=1&query=${place.coordinates.lat},${place.coordinates.lng}` : `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(location)}`;
  const rooms = asItems(specific.Rooms || profile.rooms, []); const amenities = asItems(specific.Amenities || profile.amenities || place.facilities, defaults.amenities); const services = asItems(specific['Hotel Services'] || profile.services || place.services, defaults.services); const infrastructure = asItems(specific.Infrastructure || profile.infrastructure, defaults.infrastructure); const highlights = list(specific.Highlights || profile.highlights).length ? list(specific.Highlights || profile.highlights) : defaults.highlights;
  const videos = Array.isArray(profile.videos) ? profile.videos.filter(Boolean).map((item) => typeof item === 'string' ? { url: item, title: 'Hotel experience' } : item) : [];
  const tagline = first(profile.tagline, 'Luxury | Comfort | Hospitality'); const about = first(profile.about, 'Experience elegant rooms, thoughtful amenities, and warm hospitality in the heart of the city.'); const hero = profile.coverImage || place.coverImage;
  const [menuOpen, setMenuOpen] = useState(false); const [lightbox, setLightbox] = useState(null); const [bookingSent, setBookingSent] = useState(false); const [bookingError, setBookingError] = useState(''); const [bookingSaving, setBookingSaving] = useState(false);
  const submitBooking = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); setBookingError(''); setBookingSaving(true); try { await api.post('/enquiries', { place: place._id, name: form.get('name'), phone: form.get('phone'), email: form.get('email'), message: [`Check-in: ${form.get('checkIn')}`, `Check-out: ${form.get('checkOut')}`, `Guests: ${form.get('guests')}`, `Rooms: ${form.get('rooms')}`, `Room type: ${form.get('roomType')}`, `Message: ${form.get('message')}`].join('\n') }); setBookingSent(true); event.currentTarget.reset(); } catch (error) { setBookingError(error.message || 'Unable to send your booking enquiry.'); } finally { setBookingSaving(false); } };
  const sectionHead = (eyebrow, title, id) => <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-[#a16b22]">{eyebrow}</p><h2 id={id} className="mt-2 font-display text-4xl font-bold text-[#182b40] sm:text-5xl">{title}</h2></div><Actions label={title} /></div>;
  return <div className="min-h-screen bg-[#fbfaf7] font-body text-[#182b40]" style={{ '--hotel-navy': '#102a43', '--hotel-gold': '#c38b32' }}>
    <header className="sticky top-0 z-40 border-b border-[#eadfce] bg-white/95 shadow-sm backdrop-blur"><div className="mx-auto flex max-w-[1450px] items-center justify-between gap-4 px-5 py-3 sm:px-8"><a href="#home" className="flex min-w-0 items-center gap-3"><div className="h-12 w-12 shrink-0 overflow-hidden rounded-full border border-[#eadfce] bg-[#f7efe1]"><Media src={profile.logo || place.logo} alt={`${place.name} logo`} label="Hotel logo" /></div><div className="min-w-0"><p className="truncate font-display text-xl font-bold">{place.name}</p><p className="truncate text-[11px] text-[#8b7865]">{tagline}</p></div></a><nav className="hidden items-center gap-5 text-xs font-bold lg:flex">{['Home', 'About', 'Rooms', 'Amenities', 'Services', 'Gallery', 'Videos', 'Contact'].map((item) => <a key={item} href={href(item)} className="hover:text-[#a16b22]">{item}</a>)}</nav><div className="hidden items-center gap-2 md:flex"><a href={safeUrl(social.instagram) || '#contact'} target={social.instagram ? '_blank' : undefined} rel="noreferrer" className="grid h-8 w-8 place-items-center rounded-full bg-[#d62976] text-xs font-bold text-white">IG</a><a href={safeUrl(social.facebook) || '#contact'} target={social.facebook ? '_blank' : undefined} rel="noreferrer" className="grid h-8 w-8 place-items-center rounded-full bg-[#1877f2] text-xs font-bold text-white">f</a><a href={safeUrl(social.youtube) || '#contact'} target={social.youtube ? '_blank' : undefined} rel="noreferrer" className="grid h-8 w-8 place-items-center rounded-full bg-[#f00] text-xs font-bold text-white">▶</a><a href="#contact" className="grid h-8 w-8 place-items-center rounded-full border border-[#eadfce]">⌕</a><a href="#contact" className="rounded-full bg-[#c38b32] px-5 py-2.5 text-xs font-bold text-white">Book Now</a></div><button type="button" onClick={() => setMenuOpen(!menuOpen)} className="rounded-lg border border-[#eadfce] px-3 py-2 text-lg lg:hidden" aria-label="Open navigation">☰</button></div>{menuOpen && <nav className="border-t border-[#eadfce] bg-white px-5 py-2 lg:hidden">{['Home', 'About', 'Rooms', 'Amenities', 'Services', 'Gallery', 'Videos', 'Contact'].map((item) => <a key={item} href={href(item)} className="block border-b border-[#f1e8da] py-3 text-sm font-semibold">{item}</a>)}</nav>}</header>
    <main><section id="home" className="relative isolate min-h-[580px] overflow-hidden bg-[#102a43] text-white sm:min-h-[680px]"><div className="absolute inset-0"><Media src={hero || gallery[0]} alt={`${place.name} hotel hero`} label="Hero banner" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(16,42,67,.92),rgba(16,42,67,.52),rgba(16,42,67,.12))]" /></div><div className="relative mx-auto flex min-h-[580px] max-w-[1450px] items-center px-6 py-16 sm:min-h-[680px] sm:px-12"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.28em] text-[#f1cb76]">{tagline}</p><h1 className="mt-4 font-display text-5xl font-bold leading-[.98] sm:text-7xl">{first(profile.heroHeading, `A Perfect Stay in ${place.location?.city?.name || 'the city'}`)}</h1><p className="mt-5 max-w-xl text-base leading-7 text-white/80">{about}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#contact" className="rounded-full bg-[#c38b32] px-6 py-3 text-sm font-bold text-white">Book a Room</a>{videos[0] && <a href="#videos" className="rounded-full border border-white/50 bg-white/10 px-6 py-3 text-sm font-bold">▷ Watch Video</a>}</div>{location && <p className="mt-6 text-sm text-white/70">⌖ {location}</p>}</div></div></section>
    <section className="border-b border-[#eadfce] bg-white"><div className="mx-auto grid max-w-[1300px] grid-cols-2 gap-px bg-[#eadfce] sm:grid-cols-3 lg:grid-cols-6">{highlights.slice(0, 6).map((item) => <div key={item} className="bg-white px-3 py-5 text-center"><span className="text-xl text-[#b87921]">{icons[item] || '✦'}</span><p className="mt-2 text-xs font-bold">{item}</p></div>)}</div></section>
    <section id="about" className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><div className="h-[340px] overflow-hidden rounded-3xl shadow-xl sm:h-[460px]"><Media src={gallery[0]} alt={`${place.name} room`} label="About hotel image" /></div><div>{sectionHead('Welcome', 'About Us', 'about-title')}<p className="mt-6 whitespace-pre-line text-base leading-8 text-[#6c6258]">{about}</p><div className="mt-7 grid grid-cols-2 gap-3">{highlights.slice(0, 6).map((item) => <div key={item} className="rounded-xl bg-[#f7efe1] p-4"><span className="text-xl text-[#b87921]">{icons[item] || '✦'}</span><p className="mt-2 text-xs font-bold">{item}</p></div>)}</div></div></section>
    <section id="rooms" className="bg-white px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl">{sectionHead('Stay beautifully', 'Our Rooms & Suites', 'rooms-title')}<p className="mt-2 text-sm text-[#8b7865]">Choose from thoughtfully designed rooms for a comfortable stay.</p><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{rooms.length ? rooms.map((room, index) => <article key={`${room.name || room.title}-${index}`} className="overflow-hidden rounded-2xl border border-[#eadfce] bg-white shadow-sm"><div className="h-40"><Media src={room.image || gallery[(index + 1) % Math.max(gallery.length, 1)]} alt={room.name || room.title || 'Hotel room'} label="Room image" /></div><div className="p-4"><h3 className="font-display text-xl font-bold">{room.name || room.title || 'Room'}</h3><p className="mt-2 text-xs text-[#6c6258]">{room.guests || room.capacity || 'Guests'} · {room.bed || room.bedType || 'Comfortable bed'}</p><p className="mt-2 text-xs text-[#6c6258]">{room.view || 'Beautiful views'} · {room.breakfast || 'Breakfast available'}</p>{room.price && <p className="mt-4 text-lg font-bold text-[#b87921]">{room.price}<span className="text-xs font-normal"> / Night</span></p>}<a href="#contact" className="mt-4 block rounded-full bg-[#c38b32] px-3 py-2 text-center text-xs font-bold text-white">Book Now</a></div></article>) : <div className="col-span-full rounded-2xl border border-dashed border-[#cdbb9f] p-10 text-center text-sm text-[#8b7865]">Rooms added by the hotel owner will appear here.</div>}</div></div></section>
    <section id="amenities" className="px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl">{sectionHead('Made for comfort', 'Our Amenities', 'amenities-title')}<div className="mt-8 grid gap-4 sm:grid-cols-3 lg:grid-cols-6">{amenities.map((item, index) => <div key={`${item.name}-${index}`} className="rounded-xl border border-[#eadfce] bg-white p-5 text-center shadow-sm"><span className="text-2xl text-[#b87921]">{icons[item.name] || '✦'}</span><h3 className="mt-3 text-sm font-bold">{item.name}</h3><p className="mt-2 text-xs leading-5 text-[#8b7865]">{item.description || 'Thoughtful facilities for your stay.'}</p></div>)}</div></div></section>
    <section id="services" className="bg-[#f7efe1] px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl">{sectionHead('At your service', 'Our Services', 'services-title')}<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{services.map((item, index) => <div key={`${item.name}-${index}`} className="rounded-2xl bg-white p-6 shadow-sm"><span className="text-2xl text-[#b87921]">{icons[item.name] || '✦'}</span><h3 className="mt-4 font-display text-xl font-bold">{item.name}</h3><p className="mt-2 text-sm leading-6 text-[#6c6258]">{item.description || 'Warm, reliable support throughout your stay.'}</p></div>)}</div></div></section>
    <section id="gallery" className="bg-[#102a43] px-5 py-20 text-white sm:px-8"><div className="mx-auto max-w-7xl">{sectionHead('A glimpse inside', 'Our Gallery', 'gallery-title')}<div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{gallery.length ? gallery.map((image, index) => <button type="button" key={`${image}-${index}`} onClick={() => setLightbox(image)} className={`overflow-hidden rounded-xl ${index === 0 ? 'col-span-2 row-span-2 aspect-square' : 'aspect-square'}`}><img src={image} alt={`${place.name} gallery ${index + 1}`} className="h-full w-full object-cover transition duration-500 hover:scale-105" /></button>) : <div className="col-span-full rounded-2xl border border-dashed border-white/30 p-10 text-center text-white/70">Gallery photos uploaded by the hotel owner will appear here. Maximum 10 photos.</div>}</div><p className="mt-4 text-xs text-white/50">Gallery Photos: {gallery.length} / 10</p></div></section>
    {videos.length > 0 && <section id="videos" className="mx-auto max-w-7xl px-5 py-20 sm:px-8">{sectionHead('See the experience', 'Our Videos', 'videos-title')}<div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{videos.slice(0, 6).map((video, index) => <div key={`${video.url}-${index}`}><PublicVideoCard video={video} /><p className="mt-2 text-sm font-bold">{video.title || 'Hotel experience'}</p></div>)}</div></section>}
    <section id="infrastructure" className="bg-white px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl">{sectionHead('Designed around you', 'Our Infrastructure', 'infrastructure-title')}<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{infrastructure.map((item, index) => <div key={`${item.name}-${index}`} className="rounded-xl border border-[#eadfce] p-5"><span className="text-2xl text-[#b87921]">{icons[item.name] || '✦'}</span><h3 className="mt-3 font-bold">{item.name}</h3><p className="mt-2 text-sm text-[#8b7865]">{item.description || 'Comfortable, convenient, and carefully maintained.'}</p></div>)}</div></div></section>
    <section id="reviews" className="bg-[#f7efe1] px-5 py-20 sm:px-8"><div className="mx-auto max-w-5xl">{sectionHead('From our guests', 'Guest Reviews', 'reviews-title')}<div className="mt-8 rounded-2xl bg-white p-5 shadow-sm sm:p-8"><ReviewsSection placeId={place._id} /></div></div></section>
    <section id="contact" className="bg-white px-5 py-20 sm:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-[#a16b22]">Plan your stay</p><h2 className="mt-2 font-display text-4xl font-bold">Book your room.</h2><div className="mt-6 space-y-3 text-sm leading-6 text-[#6c6258]">{location && <p>⌖ {location}</p>}{phone && <p>☎ <a href={call} className="font-bold">{phone}</a></p>}{email && <p>✉ {email}</p>}{whatsapp && <p>◉ WhatsApp available</p>}</div><a href={maps} target="_blank" rel="noreferrer" className="mt-6 inline-block rounded-full bg-[#102a43] px-5 py-3 text-sm font-bold text-white">Get Directions</a></div><form onSubmit={submitBooking} className="rounded-3xl bg-[#f7efe1] p-6 sm:p-8"><h3 className="font-display text-2xl font-bold">Check Availability</h3><div className="mt-5 grid gap-3 sm:grid-cols-2"><input name="name" required placeholder="Guest name" className="rounded-xl border-0 px-4 py-3 text-sm ring-1 ring-[#eadfce]" /><input name="phone" required placeholder="Phone number" className="rounded-xl border-0 px-4 py-3 text-sm ring-1 ring-[#eadfce]" /><input name="email" type="email" placeholder="Email" className="rounded-xl border-0 px-4 py-3 text-sm ring-1 ring-[#eadfce]" /><input name="roomType" placeholder="Room type" className="rounded-xl border-0 px-4 py-3 text-sm ring-1 ring-[#eadfce]" /><input name="checkIn" type="date" className="rounded-xl border-0 px-4 py-3 text-sm ring-1 ring-[#eadfce]" /><input name="checkOut" type="date" className="rounded-xl border-0 px-4 py-3 text-sm ring-1 ring-[#eadfce]" /><input name="guests" type="number" min="1" placeholder="Guests" className="rounded-xl border-0 px-4 py-3 text-sm ring-1 ring-[#eadfce]" /><input name="rooms" type="number" min="1" placeholder="Rooms" className="rounded-xl border-0 px-4 py-3 text-sm ring-1 ring-[#eadfce]" /><textarea name="message" placeholder="Message" rows="4" className="sm:col-span-2 rounded-xl border-0 px-4 py-3 text-sm ring-1 ring-[#eadfce]" /></div>{bookingError && <p className="mt-3 text-sm text-red-600">{bookingError}</p>}<div className="mt-5 flex flex-wrap gap-2"><button disabled={bookingSaving} className="rounded-full bg-[#c38b32] px-5 py-3 text-sm font-bold text-white">{bookingSaving ? 'Sending…' : bookingSent ? 'Request sent' : 'Check Availability'}</button><a href={whatsapp || '#contact'} target={whatsapp ? '_blank' : undefined} rel="noreferrer" className="rounded-full bg-[#1f9d62] px-5 py-3 text-sm font-bold text-white">WhatsApp</a><a href={call} className="rounded-full border border-[#d9c7a9] px-5 py-3 text-sm font-bold">Call</a></div></form></div></section></main>
    <footer className="bg-[#071b31] px-5 py-12 text-white sm:px-8"><div className="mx-auto grid max-w-7xl gap-10 sm:grid-cols-2 lg:grid-cols-4"><div><h3 className="font-bold text-[#f1cb76]">Our Location</h3><p className="mt-4 text-sm leading-6 text-white/60">{location || 'Address added by the hotel owner'}</p><a href={maps} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-bold text-[#f1cb76]">Google Maps · Get Directions</a></div><div><h3 className="font-bold text-[#f1cb76]">Contact Details</h3><div className="mt-4 space-y-2 text-sm text-white/60">{phone && <a href={call} className="block">{phone}</a>}{whatsapp && <a href={whatsapp} target="_blank" rel="noreferrer" className="block">WhatsApp</a>}{email && <a href={`mailto:${email}`} className="block">{email}</a>}<p>{profile.openingHours ? 'Business hours available' : 'Open 24/7 for reservations'}</p></div></div><div><h3 className="font-bold text-[#f1cb76]">Follow Us</h3><p className="mt-4 text-sm text-white/60">Follow Us for Latest Updates, Offers & Reels</p><div className="mt-4 flex gap-2">{[['Instagram', social.instagram], ['Facebook', social.facebook], ['YouTube', social.youtube], ['WhatsApp', whatsapp]].map(([name, url]) => <a key={name} href={url ? safeUrl(url) : '#contact'} target={url ? '_blank' : undefined} rel="noreferrer" className="rounded-full border border-white/20 px-3 py-2 text-xs">{name}</a>)}</div></div><div><h3 className="font-bold text-[#f1cb76]">Listed on G-PAGES</h3><p className="mt-4 text-sm text-white/60">This hotel is proudly listed on G-PAGES.</p><div className="mt-4 flex flex-wrap gap-2"><a href="/" className="rounded-full bg-[#c38b32] px-3 py-2 text-xs font-bold">Contact G-PAGES</a><a href="/" className="rounded-full border border-white/30 px-3 py-2 text-xs font-bold">Back to Home</a></div></div></div><div className="mx-auto mt-10 max-w-7xl border-t border-white/15 pt-5 text-xs text-white/40">© {new Date().getFullYear()} {place.name}. All rights reserved.</div></footer><Floating phone={phone} whatsapp={whatsapp} social={social} />
    {lightbox && <div className="fixed inset-0 z-50 grid place-items-center bg-black/90 p-4" onClick={() => setLightbox(null)}><img src={lightbox} alt="Hotel gallery enlarged" className="max-h-[90vh] max-w-[94vw] object-contain" /></div>}
  </div>;
}