import React, { useState } from 'react';
import ReviewsSection from '../ReviewsSection';
import { getProfileData, PublicVideoCard, safeUrl } from './PublicProfileShared';
import { getWhatsAppUrl } from '../../utils/healthcare';
import api from '../../services/api';

const list = (value) => Array.isArray(value) ? value.filter(Boolean) : String(value || '').split(/[\n,]/).map((item) => item.trim()).filter(Boolean);
const first = (...values) => values.find((value) => value !== undefined && value !== null && value !== '');
const objects = (value) => Array.isArray(value) ? value.map((item) => typeof item === 'string' ? { name: item } : item) : [];
const icons = { 'High Quality Products': 'Q', 'Modern Manufacturing': 'M', 'Custom Solutions': 'C', 'Bulk Supply': 'B', 'Timely Delivery': 'D', 'Expert Support': 'S', Factory: 'F', Warehouse: 'W', Machinery: 'M', 'Production Unit': 'P', Storage: 'S', Logistics: 'L', 'Quality & Safety': 'Q', Packaging: 'PK', Distribution: 'DS' };

function Media({ src, alt, label, className = '' }) {
  return src ? <img src={src} alt={alt} className={`h-full w-full object-cover ${className}`} /> : <div className={`grid h-full w-full place-items-center bg-[linear-gradient(135deg,#dce5ee,#60758a)] p-5 text-center text-[#102a43] ${className}`}><div><span className="text-4xl">+</span><p className="mt-2 text-xs font-bold uppercase tracking-[.16em]">{label}</p><p className="mt-1 text-xs opacity-70">Business media not configured</p></div></div>;
}

function Actions({ label }) {
  const [liked, setLiked] = useState(false);
  const share = async () => navigator.share ? navigator.share({ title: label, url: window.location.href }) : navigator.clipboard?.writeText(window.location.href);
  return <div className="flex flex-wrap gap-1.5 text-[10px] font-bold text-[#5f7180]"><button type="button" onClick={() => setLiked(!liked)} className={`rounded-full border px-2.5 py-1.5 ${liked ? 'border-blue-200 bg-blue-50 text-blue-700' : 'border-[#d8e1e9] bg-white'}`}>♥ {liked ? 'Liked' : 'Like'}</button><button type="button" onClick={share} className="rounded-full border border-[#d8e1e9] bg-white px-2.5 py-1.5">↗ Share</button><a href="#contact" className="rounded-full border border-[#d8e1e9] bg-white px-2.5 py-1.5">Comment</a><a href="#contact" className="rounded-full border border-[#d8e1e9] bg-white px-2.5 py-1.5">Report</a></div>;
}

function Socials({ social, whatsapp }) {
  const links = [['Facebook', social.facebook, 'f'], ['Instagram', social.instagram, 'IG'], ['YouTube', social.youtube, 'YT'], ['LinkedIn', social.linkedin, 'in'], ['WhatsApp', whatsapp, 'WA'], ['X', social.twitter || social.x, 'X']];
  return <div className="flex flex-wrap gap-2">{links.filter(([, url]) => url).map(([name, url, label]) => <a key={name} href={safeUrl(url)} target="_blank" rel="noreferrer" title={name} className={`grid h-8 w-8 place-items-center rounded-full border border-current/20 text-[10px] font-bold ${name === 'WhatsApp' ? 'bg-[#1e9c63] text-white' : 'bg-white/10'}`}>{name === 'WhatsApp' ? <ContactIcon type="whatsapp" /> : label}</a>)}</div>;
}

function ContactIcon({ type }) {
  if (type === 'whatsapp') return <svg viewBox="0 0 24 24" aria-hidden="true" className="h-7 w-7 fill-none stroke-current stroke-[2.2]"><circle cx="12" cy="12" r="8.5" /><path d="M7.8 20.1 6.9 17l-.1-.2A8.5 8.5 0 1 1 12 20.5c-1.4 0-2.8-.4-4.2-1.1Z" /><path d="M9 8.8c.2-.5.4-.5.7-.5h.5c.2 0 .4.1.5.4l.7 1.6c.1.2.1.4-.1.6l-.5.6c.7 1.2 1.7 2 3 2.6l.6-.7c.2-.2.4-.2.7-.1l1.5.7c.3.1.4.3.4.6-.1 1-.8 1.5-1.6 1.5-2.1-.1-5.8-3.1-6.6-5.4-.3-.7-.2-1.4.2-1.9Z" /></svg>;
  if (type === 'phone') return <svg viewBox="0 0 24 24" aria-hidden="true" className="h-7 w-7 fill-current"><path d="M7.2 3.8 5 5.1c-.8.5-.9 1.4-.6 2.3 1.5 5.1 6 9.7 11.1 11.1.9.3 1.8.2 2.3-.6l1.3-2.2c.3-.6.2-1.3-.4-1.7l-2.4-1.4c-.5-.3-1.1-.2-1.5.2l-1 1.2a12.3 12.3 0 0 1-4.4-4.4l1.2-1c.4-.4.5-1 .2-1.5L9 4.2c-.4-.6-1.1-.7-1.8-.4Z" /></svg>;
  return <svg viewBox="0 0 24 24" aria-hidden="true" className="h-7 w-7 fill-current"><path d="M4 5.5h16v11H9l-5 3v-14Z" /></svg>;
}

function Floating({ phone, whatsapp, social }) {
  const call = phone ? `tel:${String(phone).replace(/\s/g, '')}` : '#contact';
  return <div className="fixed right-4 top-1/2 z-40 hidden -translate-y-1/2 flex-col gap-3 md:flex"><a href={whatsapp || '#contact'} target={whatsapp ? '_blank' : undefined} rel="noreferrer" aria-label="WhatsApp" title="WhatsApp" className="grid h-14 w-14 place-items-center rounded-full bg-[#16a765] text-[#071b31] shadow-[0_8px_22px_rgba(7,27,49,.18)]"><ContactIcon type="whatsapp" /></a><a href={call} aria-label="Call business" title="Call" className="grid h-14 w-14 place-items-center rounded-full bg-white text-[#071b31] shadow-[0_8px_22px_rgba(7,27,49,.14)]"><ContactIcon type="phone" /></a><a href="#contact" aria-label="Request a quote" title="Request a quote" className="grid h-14 w-14 place-items-center rounded-full bg-white text-[#071b31] shadow-[0_8px_22px_rgba(7,27,49,.14)]"><ContactIcon type="enquiry" /></a></div>;
}

export default function IndustrialWebsite({ place }) {
  const profile = getProfileData(place); const specific = place.attributes?.businessProfile?.categorySpecific || {}; const category = String(place.category?.slug || place.category?.name || '').toLowerCase().replace(/[_\s]+/g, '-');
  const isFood = category === 'food-processing'; const isTrading = category === 'trading-businesses';
  const gallery = (profile.gallery?.length ? profile.gallery : place.images || []).filter(Boolean).slice(0, 10); const social = profile.socialMedia || {}; const phone = place.phone || profile.phone || ''; const whatsapp = getWhatsAppUrl(social.whatsapp || profile.whatsapp || phone); const call = phone ? `tel:${String(phone).replace(/\s/g, '')}` : '#contact'; const email = place.email || profile.email || ''; const website = place.website || profile.website;
  const location = [place.address, place.location?.area?.name, place.location?.city?.name, place.location?.district?.name, place.location?.state?.name, profile.pincode].filter(Boolean).join(', '); const maps = place.coordinates?.lat ? `https://www.google.com/maps/search/?api=1&query=${place.coordinates.lat},${place.coordinates.lng}` : `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(location)}`;
  const products = objects(specific.Products || profile.products); const services = list(specific.Services || profile.services || place.services).map((name) => ({ name })); const facilities = objects(specific.Infrastructure || profile.infrastructure); const videos = [...(Array.isArray(profile.videos) ? profile.videos : []), ...(place.video ? [{ url: place.video, title: 'Business video' }] : [])].filter(Boolean).map((video) => typeof video === 'string' ? { url: video, title: 'Business video' } : video);
  const quality = list(specific.Quality || specific['Quality & Safety'] || profile.quality); const certifications = objects(specific.Certifications || profile.certifications); const process = objects(specific['Manufacturing Process'] || profile.process); const highlights = list(profile.highlights || specific.Highlights); const about = first(profile.about, place.description); const tagline = first(profile.tagline, isFood ? 'Food Manufacturing | Quality | Distribution' : isTrading ? 'Trade | Supply | Distribution' : 'Quality Products | Reliable Supply | Industrial Expertise'); const hero = profile.coverImage || place.coverImage;
  const [menuOpen, setMenuOpen] = useState(false); const [lightbox, setLightbox] = useState(null); const [sent, setSent] = useState(false); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const submit = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); setError(''); try { await api.post('/enquiries', { place: place._id, name: form.get('name'), phone: form.get('phone'), email: form.get('email'), message: [`Company: ${form.get('company') || 'Not provided'}`, `Product / service: ${form.get('product') || 'Not specified'}`, `Quantity: ${form.get('quantity') || 'Not specified'}`, `Message: ${form.get('message') || ''}`].join('\n') }); setSent(true); event.currentTarget.reset(); } catch (submitError) { setError(submitError.message || 'Unable to submit the enquiry.'); } finally { setSaving(false); } };
  const heading = (eyebrow, title) => <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-[#d86f22]">{eyebrow}</p><h2 className="mt-2 font-display text-4xl font-bold text-[#102a43] sm:text-5xl">{title}</h2></div><Actions label={title} /></div>;
  const nav = isTrading ? ['Home', 'About Us', 'Products', 'Distribution', 'Gallery', 'Videos', 'Contact'] : ['Home', 'About Us', 'Products', 'Manufacturing', 'Services', 'Quality', 'Infrastructure', 'Gallery', 'Videos', 'Contact'];
  return <div className="min-h-screen bg-[#f4f7fa] font-body text-[#0b2035]">
    <header className="sticky top-0 z-40 border-b border-[#d8e1e9] bg-white/95 shadow-sm backdrop-blur"><div className="mx-auto flex max-w-[1480px] items-center justify-between gap-4 px-5 py-3 sm:px-8"><a href="#home" className="flex min-w-0 items-center gap-3"><div className="h-11 w-11 shrink-0 overflow-hidden rounded-lg border border-[#d8e1e9] bg-[#eef3f7]"><Media src={profile.logo || place.logo} alt={`${place.name} logo`} label="Logo" /></div><div className="min-w-0"><p className="truncate font-display text-xl font-bold">{place.name}</p><p className="truncate text-[11px] text-[#65798a]">{tagline}</p></div></a><nav className="hidden items-center gap-4 text-xs font-bold lg:flex">{nav.map((item) => <a key={item} href={`#${item.toLowerCase().replace(/[^a-z]+/g, '-')}`} className="hover:text-[#d86f22]">{item}</a>)}</nav><div className="hidden items-center gap-2 md:flex"><a href={call} aria-label="Call business" title={phone ? `Call ${phone}` : 'Call business'} className="grid h-8 w-8 place-items-center rounded-full border border-[#b9dfc9] bg-[#eaf8ef] text-[#1e9c63]"><ContactIcon type="phone" /></a><Socials social={social} whatsapp={whatsapp} /><a href="#contact" className="flex items-center gap-1 rounded-md bg-[#e87524] px-4 py-2.5 text-xs font-bold text-white"><span>✉</span>Request a Quote</a></div><button type="button" onClick={() => setMenuOpen(!menuOpen)} className="rounded border border-[#d8e1e9] px-3 py-2 lg:hidden" aria-label="Open navigation">Menu</button></div>{menuOpen && <nav className="border-t border-[#d8e1e9] bg-white px-5 py-2 lg:hidden">{nav.map((item) => <a key={item} href={`#${item.toLowerCase().replace(/[^a-z]+/g, '-')}`} className="block border-b border-[#eef2f5] py-3 text-sm font-semibold">{item}</a>)}</nav>}</header>
    <main><section id="home" className="relative isolate min-h-[560px] overflow-hidden bg-[#102a43] text-white sm:min-h-[650px]"><div className="absolute inset-0"><Media src={hero} alt={`${place.name} industrial cover`} label="Industrial banner" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(16,42,67,.94),rgba(16,42,67,.6),rgba(16,42,67,.12))]" /></div><div className="relative mx-auto flex min-h-[560px] max-w-[1480px] items-center px-6 py-16 sm:min-h-[650px] sm:px-12"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#f4bd70]">{place.category?.name || 'Industries & Manufacturing'}</p><h1 className="mt-4 font-display text-5xl font-bold leading-[.98] sm:text-7xl">{place.name}</h1>{tagline && <p className="mt-5 text-2xl font-semibold text-white/90 sm:text-3xl">{tagline}</p>}{about && <p className="mt-5 max-w-xl text-base leading-7 text-white/75">{about}</p>}<div className="mt-8 flex flex-wrap gap-3"><a href="#products" className="rounded-md bg-[#e87524] px-6 py-3 text-sm font-bold text-white">Our Products</a><a href="#contact" className="rounded-md border border-white/50 bg-white/10 px-6 py-3 text-sm font-bold">Contact Us</a></div>{location && <p className="mt-6 text-sm text-white/70">{location}</p>}</div></div></section>
    {(highlights.length > 0) && <section className="border-b border-[#d8e1e9] bg-white"><div className="mx-auto grid max-w-[1300px] grid-cols-2 gap-px bg-[#d8e1e9] sm:grid-cols-3 lg:grid-cols-6">{highlights.slice(0, 6).map((item) => <div key={item} className="bg-white px-3 py-5 text-center"><span className="grid mx-auto h-9 w-9 place-items-center rounded-full bg-[#fff0e5] text-xs font-black text-[#d86f22]">{icons[item] || '+'}</span><p className="mt-2 text-xs font-bold">{item}</p></div>)}</div></section>}
    <section id="about-us" className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div className="h-[350px] overflow-hidden rounded-xl shadow-lg sm:h-[460px]"><Media src={gallery[0]} alt={`${place.name} facility`} label="Company image" /></div><div>{heading('Company profile', 'About Us')}{about && <p className="mt-6 whitespace-pre-line text-base leading-8 text-[#5f7180]">{about}</p>}{specific.Mission && <p className="mt-4 text-sm leading-7 text-[#5f7180]"><strong>Mission:</strong> {specific.Mission}</p>}{specific.Vision && <p className="mt-3 text-sm leading-7 text-[#5f7180]"><strong>Vision:</strong> {specific.Vision}</p>}{location && <p className="mt-5 text-sm font-semibold text-[#d86f22]">{location}</p>}</div></section>
    {products.length > 0 && <section id="products" className="bg-white px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl">{heading(isTrading ? 'B2B supply' : isFood ? 'Food products' : 'Industrial range', 'Our Products')}<div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.map((product, index) => <article key={`${product.name || product.title}-${index}`} className="overflow-hidden rounded-xl border border-[#d8e1e9] bg-white shadow-sm"><div className="h-40"><Media src={product.image || gallery[(index + 1) % Math.max(gallery.length, 1)]} alt={product.name || product.title || 'Product'} label="Product image" /></div><div className="p-4"><h3 className="font-display text-xl font-bold">{product.name || product.title}</h3>{product.category && <p className="mt-1 text-xs font-bold text-[#d86f22]">{product.category}</p>}{product.description && <p className="mt-3 text-sm leading-6 text-[#5f7180]">{product.description}</p>}{product.specifications && <p className="mt-2 text-xs text-[#5f7180]">{product.specifications}</p>}{product.price && <p className="mt-3 font-bold text-[#d86f22]">{product.price}</p>}<a href="#contact" className="mt-4 block rounded-md border border-[#e87524] px-3 py-2 text-center text-xs font-bold text-[#d86f22]">Enquire</a></div></article>)}</div></div></section>}
    {services.length > 0 && <section id="services" className="px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl">{heading('Capabilities', isTrading ? 'Trading & Distribution' : 'Our Services')}<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{services.map((service, index) => <div key={`${service.name}-${index}`} className="rounded-xl border border-[#d8e1e9] bg-white p-5 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded bg-[#102a43] text-xs font-bold text-white">{index + 1}</span><h3 className="mt-4 font-bold">{service.name}</h3><p className="mt-2 text-sm leading-6 text-[#5f7180]">{service.description || 'Business service details provided by the company.'}</p></div>)}</div></div></section>}
    {process.length > 0 && <section id="manufacturing" className="bg-[#102a43] px-5 py-20 text-white sm:px-8"><div className="mx-auto max-w-7xl">{heading('How we work', isFood ? 'Processing & Production' : 'Manufacturing Process')}<div className="mt-8 grid gap-4 md:grid-cols-5">{process.map((step, index) => <div key={`${step.name || step.title}-${index}`} className="relative rounded-lg border border-white/15 bg-white/10 p-5"><span className="text-3xl font-black text-[#f4bd70]">{String(index + 1).padStart(2, '0')}</span><h3 className="mt-4 font-bold">{step.name || step.title}</h3>{step.description && <p className="mt-2 text-sm text-white/65">{step.description}</p>}</div>)}</div></div></section>}
    {quality.length > 0 && <section id="quality" className="bg-[#eef3f7] px-5 py-16 sm:px-8"><div className="mx-auto max-w-7xl">{heading('Built to perform', isFood ? 'Quality & Safety' : 'Quality')}<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{quality.map((item) => <div key={item} className="rounded-lg bg-white p-5 font-semibold text-[#102a43]">{item}</div>)}</div></div></section>}
    {facilities.length > 0 && <section id="infrastructure" className="px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl">{heading('Capability on the ground', isTrading ? 'Supply Network' : isFood ? 'Production Facility' : 'Our Infrastructure')}<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{facilities.map((facility, index) => <div key={`${facility.name}-${index}`} className="rounded-xl border border-[#d8e1e9] bg-white p-5"><span className="grid h-10 w-10 place-items-center rounded bg-[#fff0e5] text-xs font-black text-[#d86f22]">{icons[facility.name] || 'I'}</span><h3 className="mt-4 font-bold">{facility.name}</h3>{facility.description && <p className="mt-2 text-sm text-[#5f7180]">{facility.description}</p>}{facility.image && <div className="mt-4 h-28 overflow-hidden rounded"><img src={facility.image} alt={facility.name} className="h-full w-full object-cover" /></div>}</div>)}</div></div></section>}
    {certifications.length > 0 && <section id="certifications" className="bg-white px-5 py-16 sm:px-8"><div className="mx-auto max-w-7xl">{heading('Proof of quality', 'Certifications')}<div className="mt-7 flex flex-wrap gap-4">{certifications.map((cert, index) => <div key={`${cert.name || cert.title}-${index}`} className="rounded-lg border border-[#d8e1e9] bg-[#f7fafc] p-5"><h3 className="font-bold">{cert.name || cert.title}</h3>{cert.issuer && <p className="mt-1 text-sm text-[#5f7180]">{cert.issuer}</p>}{cert.validity && <p className="mt-1 text-xs text-[#5f7180]">Valid: {cert.validity}</p>}</div>)}</div></div></section>}
    {gallery.length > 0 && <section id="gallery" className="bg-[#eef3f7] px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl">{heading('Inside the business', 'Gallery')}<div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{gallery.map((image, index) => <button type="button" key={`${image}-${index}`} onClick={() => setLightbox(image)} className="aspect-square overflow-hidden rounded-lg"><img src={image} alt={`${place.name} gallery ${index + 1}`} className="h-full w-full object-cover transition hover:scale-105" /></button>)}</div><p className="mt-4 text-xs text-[#5f7180]">Gallery Photos: {gallery.length} / 10</p></div></section>}
    {videos.length > 0 && <section id="videos" className="mx-auto max-w-7xl px-5 py-20 sm:px-8">{heading('See the work', 'Watch Our Videos')}<div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{videos.slice(0, 6).map((video, index) => <div key={`${video.url}-${index}`}><PublicVideoCard video={video} /><p className="mt-2 text-sm font-bold">{video.title || 'Business video'}</p></div>)}</div></section>}
    <section id="reviews" className="bg-white px-5 py-20 sm:px-8"><div className="mx-auto max-w-5xl">{heading('Customer trust', 'Reviews')}<div className="mt-8 rounded-lg border border-[#d8e1e9] p-5 sm:p-8"><ReviewsSection placeId={place._id} /></div></div></section>
    <section id="contact" className="bg-[#102a43] px-5 py-20 text-white sm:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-[#f4bd70]">Start a conversation</p><h2 className="mt-2 font-display text-4xl font-bold">Request a Quote</h2><div className="mt-6 space-y-3 text-sm leading-6 text-white/70">{location && <p>{location}</p>}{phone && <p><a href={call}>{phone}</a></p>}{whatsapp && <p><a href={whatsapp} target="_blank" rel="noreferrer">WhatsApp</a></p>}{email && <p>{email}</p>}{website && <p>{website}</p>}</div><a href={maps} target="_blank" rel="noreferrer" className="mt-6 inline-block rounded-md bg-[#e87524] px-5 py-3 text-sm font-bold text-white">Get Directions</a><div className="mt-7"><Socials social={social} whatsapp={whatsapp} /></div></div><form onSubmit={submit} className="rounded-xl bg-white p-6 text-[#102a43] shadow-xl sm:p-8"><h3 className="font-display text-2xl font-bold">Send an Enquiry</h3><div className="mt-5 grid gap-3 sm:grid-cols-2"><input name="name" required placeholder="Name" className="rounded border border-[#d8e1e9] px-4 py-3 text-sm" /><input name="company" placeholder="Company name" className="rounded border border-[#d8e1e9] px-4 py-3 text-sm" /><input name="phone" required placeholder="Phone" className="rounded border border-[#d8e1e9] px-4 py-3 text-sm" /><input name="email" type="email" placeholder="Email" className="rounded border border-[#d8e1e9] px-4 py-3 text-sm" /><input name="product" placeholder="Product / service" className="rounded border border-[#d8e1e9] px-4 py-3 text-sm" /><input name="quantity" placeholder="Quantity" className="rounded border border-[#d8e1e9] px-4 py-3 text-sm" /><textarea name="message" required placeholder="Message" rows="5" className="sm:col-span-2 rounded border border-[#d8e1e9] px-4 py-3 text-sm" /></div>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<button disabled={saving} className="mt-5 rounded-md bg-[#e87524] px-6 py-3 text-sm font-bold text-white">{saving ? 'Sending...' : sent ? 'Enquiry sent' : 'Submit Enquiry'}</button></form></div></section></main>
    <footer className="bg-[#071b31] px-5 py-12 text-white sm:px-8"><div className="mx-auto grid max-w-7xl gap-10 sm:grid-cols-2 lg:grid-cols-4"><div><div className="flex items-center gap-3"><div className="h-10 w-10 overflow-hidden rounded bg-white"><Media src={profile.logo || place.logo} alt={`${place.name} logo`} label="Logo" /></div><p className="font-display text-lg font-bold">{place.name}</p></div><p className="mt-4 text-sm text-white/60">{tagline}</p></div><div><h3 className="font-bold text-[#f4bd70]">Quick Links</h3><div className="mt-4 space-y-2 text-sm text-white/60">{nav.slice(0, 6).map((item) => <a key={item} href={`#${item.toLowerCase().replace(/[^a-z]+/g, '-')}`} className="block">{item}</a>)}</div></div><div><h3 className="font-bold text-[#f4bd70]">Contact</h3><div className="mt-4 space-y-2 text-sm text-white/60">{phone && <a href={call} className="block">{phone}</a>}{email && <a href={`mailto:${email}`} className="block">{email}</a>}{location && <p>{location}</p>}</div></div><div><h3 className="font-bold text-[#f4bd70]">Follow Us</h3><div className="mt-4"><Socials social={social} whatsapp={whatsapp} /></div></div></div><div className="mx-auto mt-10 max-w-7xl border-t border-white/15 pt-5 text-xs text-white/40">Copyright {new Date().getFullYear()} {place.name}. All rights reserved.</div></footer><Floating phone={phone} whatsapp={whatsapp} social={social} />
    {lightbox && <div className="fixed inset-0 z-50 grid place-items-center bg-black/90 p-4" onClick={() => setLightbox(null)}><img src={lightbox} alt="Industrial gallery enlarged" className="max-h-[90vh] max-w-[94vw] object-contain" /></div>}
  </div>;
}
