import React, { useState } from 'react';
import ReviewsSection from '../ReviewsSection';
import { getProfileData, PublicVideoCard, safeUrl } from './PublicProfileShared';
import { getWhatsAppUrl } from '../../utils/healthcare';
import api from '../../services/api';

const icons = { 'Birthday Parties': '*', 'DJ Nights': 'DJ', 'Live Music': 'M', 'Private Parties': 'P', 'Corporate Events': 'C', 'Theme Parties': 'T', 'Premium Venue': 'V', 'Custom Event Setup': '+', 'Professional Sound & Lights': 'S', 'Delicious Catering': 'F', 'Memorable Celebrations': 'G', 'Spacious Halls': 'H', 'Dance Floor': 'D', 'Sound System': 'S', 'DJ Console': 'DJ', 'Lighting Setup': 'L', 'Catering Area': 'F', Parking: 'P', 'AC Venue': 'AC', 'Outdoor Venue': 'O', Stage: 'ST', 'Green Room': 'GR', 'VIP Area': 'VIP', Security: 'SEC' };
const defaultServices = ['Birthday Parties', 'DJ Nights', 'Live Music', 'Private Parties', 'Corporate Events', 'Theme Parties'];
const defaultFacilities = ['Spacious Halls', 'Dance Floor', 'Professional Sound & Lights', 'DJ Console', 'Lighting Setup', 'Catering Area', 'Parking', 'AC Venue'];
const defaultHighlights = ['Premium Venue', 'Custom Event Setup', 'Professional Sound & Lights', 'Delicious Catering', 'Memorable Celebrations'];
const list = (value) => Array.isArray(value) ? value.filter(Boolean) : String(value || '').split(/[\n,]/).map((item) => item.trim()).filter(Boolean);
const first = (...values) => values.find((value) => value !== undefined && value !== null && value !== '');
const items = (value, fallback = []) => Array.isArray(value) && value.length ? value.map((item) => typeof item === 'string' ? { name: item } : item) : fallback.map((name) => ({ name }));
const href = (value) => `#${value.toLowerCase().replace(/[^a-z]+/g, '-')}`;

function Media({ src, alt, label, className = '' }) {
  return src ? <img src={src} alt={alt} className={`h-full w-full object-cover ${className}`} /> : <div className={`grid h-full w-full place-items-center bg-[linear-gradient(135deg,#191325,#85264c)] p-5 text-center text-white ${className}`}><div><span className="text-4xl">*</span><p className="mt-2 text-xs font-bold uppercase tracking-[.16em]">{label}</p><p className="mt-1 text-xs text-white/65">Owner media placeholder</p></div></div>;
}

function Actions({ label }) {
  const [liked, setLiked] = useState(false);
  const share = async () => navigator.share ? navigator.share({ title: label, url: window.location.href }) : navigator.clipboard?.writeText(window.location.href);
  return <div className="flex flex-wrap gap-1.5 text-[10px] font-bold text-[#75677b]"><button type="button" onClick={() => setLiked(!liked)} className={`rounded-full border px-2.5 py-1.5 ${liked ? 'border-rose-200 bg-rose-50 text-rose-600' : 'border-[#eadfea] bg-white'}`}>â™¥ {liked ? 'Liked' : 'Like'}</button><button type="button" onClick={share} className="rounded-full border border-[#eadfea] bg-white px-2.5 py-1.5">â†— Share</button><a href="#contact" className="rounded-full border border-[#eadfea] bg-white px-2.5 py-1.5">Comment</a><a href="#contact" className="rounded-full border border-[#eadfea] bg-white px-2.5 py-1.5">Report</a></div>;
}

function Floating({ phone, whatsapp, social }) {
  const call = phone ? `tel:${String(phone).replace(/\s/g, '')}` : '#contact'; const instagram = safeUrl(social.instagram); const youtube = safeUrl(social.youtube);
  return <div className="fixed right-4 top-1/2 z-40 hidden -translate-y-1/2 flex-col gap-2 md:flex"><a href={whatsapp || '#contact'} target={whatsapp ? '_blank' : undefined} rel="noreferrer" title="WhatsApp" className="grid h-11 w-11 place-items-center rounded-full bg-[#1e9c63] text-xs font-bold text-white shadow-lg">WA</a><a href={call} title="Call Now" className="grid h-11 w-11 place-items-center rounded-full bg-[#287fe0] text-xs font-bold text-white shadow-lg">CALL</a><a href="#contact" title="Live Chat" className="grid h-11 w-11 place-items-center rounded-full bg-[#e4a73e] text-xs font-bold text-[#211629] shadow-lg">CHAT</a>{instagram && <a href={instagram} target="_blank" rel="noreferrer" title="Instagram" className="grid h-11 w-11 place-items-center rounded-full bg-[#d62976] text-xs font-bold text-white shadow-lg">IG</a>}{youtube && <a href={youtube} target="_blank" rel="noreferrer" title="YouTube" className="grid h-11 w-11 place-items-center rounded-full bg-red-600 text-xs font-bold text-white shadow-lg">YT</a>}</div>;
}

export default function PartyZoneWebsite({ place }) {
  const profile = getProfileData(place); const specific = place.attributes?.businessProfile?.categorySpecific || {};
  const gallery = (profile.gallery?.length ? profile.gallery : place.images || []).filter(Boolean).slice(0, 10); const social = profile.socialMedia || {};
  const phone = place.phone || profile.phone || ''; const whatsapp = getWhatsAppUrl(social.whatsapp || profile.whatsapp || phone); const call = phone ? `tel:${String(phone).replace(/\s/g, '')}` : '#contact'; const email = place.email || profile.email || '';
  const location = [place.address, place.location?.area?.name, place.location?.city?.name, place.location?.district?.name, place.location?.state?.name, profile.pincode].filter(Boolean).join(', '); const maps = place.coordinates?.lat ? `https://www.google.com/maps/search/?api=1&query=${place.coordinates.lat},${place.coordinates.lng}` : `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(location)}`;
  const services = items(specific['Party Services'] || profile.services || place.services, defaultServices); const facilities = items(specific.Infrastructure || specific.Facilities || profile.infrastructure || place.facilities, defaultFacilities); const highlights = list(specific.Highlights || profile.highlights).length ? list(specific.Highlights || profile.highlights) : defaultHighlights; const packages = items(specific.Packages || profile.packages);
  const videos = Array.isArray(profile.videos) ? profile.videos.filter(Boolean).map((item) => typeof item === 'string' ? { url: item, title: 'Event experience' } : item) : [];
  const tagline = first(profile.tagline, 'Party | Music | Events | Celebrations'); const about = first(profile.about, 'The perfect venue for birthdays, DJ nights, corporate events and unforgettable celebrations.'); const philosophy = first(specific['Venue Philosophy'], profile.mission, 'We create energetic, welcoming spaces where every celebration feels personal.'); const hero = profile.coverImage || place.coverImage;
  const [menuOpen, setMenuOpen] = useState(false); const [lightbox, setLightbox] = useState(null); const [sent, setSent] = useState(false); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const submit = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); setError(''); try { await api.post('/enquiries', { place: place._id, name: form.get('name'), phone: form.get('phone'), email: form.get('email'), message: [`Event type: ${form.get('eventType')}`, `Date: ${form.get('date')}`, `Time: ${form.get('time')}`, `Guests: ${form.get('guests')}`, `Package: ${form.get('package')}`, `Budget: ${form.get('budget')}`, `Requirements: ${form.get('message')}`].join('\n') }); setSent(true); event.currentTarget.reset(); } catch (submitError) { setError(submitError.message || 'Unable to send your event enquiry.'); } finally { setSaving(false); } };
  const heading = (eyebrow, title) => <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-[#e5ad3d]">{eyebrow}</p><h2 className="mt-2 font-display text-4xl font-bold text-[#211629] sm:text-5xl">{title}</h2></div><Actions label={title} /></div>;
  return <div className="min-h-screen bg-[#fbf9fd] font-body text-[#211629]" style={{ '--party-dark': '#211629', '--party-gold': '#e5ad3d', '--party-pink': '#df267b' }}>
    <header className="sticky top-0 z-40 border-b border-[#eadfea] bg-[#211629]/95 text-white shadow-lg backdrop-blur"><div className="mx-auto flex max-w-[1450px] items-center justify-between gap-4 px-5 py-3 sm:px-8"><a href="#home" className="flex min-w-0 items-center gap-3"><div className="grid h-12 w-12 shrink-0 place-items-center overflow-hidden rounded-xl border border-white/20 bg-[#df267b]"><Media src={profile.logo || place.logo} alt={`${place.name} logo`} label="Logo" /></div><div className="min-w-0"><p className="truncate font-display text-xl font-bold text-[#f3c65c]">{place.name}</p><p className="truncate text-[11px] text-white/60">{tagline}</p></div></a><nav className="hidden items-center gap-5 text-xs font-bold lg:flex">{['Home', 'About', 'Services', 'Events', 'Packages', 'Gallery', 'Videos', 'Contact'].map((item) => <a key={item} href={href(item)} className="hover:text-[#f3c65c]">{item}</a>)}</nav><div className="hidden items-center gap-2 md:flex"><a href={safeUrl(social.instagram) || '#contact'} target={social.instagram ? '_blank' : undefined} rel="noreferrer" className="grid h-8 w-8 place-items-center rounded-full bg-[#d62976] text-xs font-bold">IG</a><a href={safeUrl(social.facebook) || '#contact'} target={social.facebook ? '_blank' : undefined} rel="noreferrer" className="grid h-8 w-8 place-items-center rounded-full bg-[#1877f2] text-xs font-bold">f</a><a href={safeUrl(social.youtube) || '#contact'} target={social.youtube ? '_blank' : undefined} rel="noreferrer" className="grid h-8 w-8 place-items-center rounded-full bg-red-600 text-xs font-bold">YT</a><a href="#contact" className="grid h-8 w-8 place-items-center rounded-full border border-white/25">âŒ•</a><a href="#contact" className="rounded-full bg-[#e5ad3d] px-5 py-2.5 text-xs font-bold text-[#211629]">Book Your Event</a></div><button type="button" onClick={() => setMenuOpen(!menuOpen)} className="rounded-lg border border-white/25 px-3 py-2 text-lg lg:hidden" aria-label="Open navigation">â˜°</button></div>{menuOpen && <nav className="border-t border-white/15 bg-[#211629] px-5 py-2 lg:hidden">{['Home', 'About', 'Services', 'Events', 'Packages', 'Gallery', 'Videos', 'Contact'].map((item) => <a key={item} href={href(item)} className="block border-b border-white/10 py-3 text-sm font-semibold">{item}</a>)}</nav>}</header>
    <main><section id="home" className="relative isolate min-h-[590px] overflow-hidden bg-[#211629] text-white sm:min-h-[690px]"><div className="absolute inset-0"><Media src={hero || gallery[0]} alt={`${place.name} event hero`} label="Hero image" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(33,22,41,.95),rgba(54,23,62,.57),rgba(54,23,62,.1))]" /></div><div className="relative mx-auto flex min-h-[590px] max-w-[1450px] items-center px-6 py-16 sm:min-h-[690px] sm:px-12"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.28em] text-[#f3c65c]">{tagline}</p><h1 className="mt-4 font-display text-5xl font-bold leading-[.98] sm:text-7xl">{first(profile.heroHeading, 'Make Every Moment a Celebration')}</h1><p className="mt-5 max-w-xl text-base leading-7 text-white/80">{about}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#contact" className="rounded-full bg-[#e5ad3d] px-6 py-3 text-sm font-bold text-[#211629]">Book Your Event</a>{videos[0] && <a href="#videos" className="rounded-full border border-white/50 bg-white/10 px-6 py-3 text-sm font-bold">Play Watch Video</a>}</div>{location && <p className="mt-6 text-sm text-white/70">{location}</p>}</div></div></section>
    <section className="border-b border-[#eadfea] bg-white"><div className="mx-auto grid max-w-[1300px] grid-cols-2 gap-px bg-[#eadfea] sm:grid-cols-3 lg:grid-cols-6">{(highlights.length ? highlights : defaultHighlights).slice(0, 6).map((item) => <div key={item} className="bg-white px-3 py-5 text-center"><span className="text-xl text-[#df267b]">{icons[item] || '*'}</span><p className="mt-2 text-xs font-bold">{item}</p></div>)}</div></section>
    <section id="about" className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><div className="h-[350px] overflow-hidden rounded-3xl shadow-xl sm:h-[470px]"><Media src={gallery[0]} alt={`${place.name} party venue`} label="About venue image" /></div><div>{heading('Welcome to the celebration', 'About Us')}<p className="mt-6 whitespace-pre-line text-base leading-8 text-[#75677b]">{about}</p><p className="mt-4 text-sm leading-7 text-[#75677b]">{philosophy}</p><div className="mt-7 grid grid-cols-2 gap-3">{highlights.slice(0, 6).map((item) => <div key={item} className="rounded-xl bg-[#f7edf7] p-4"><span className="text-xl text-[#df267b]">{icons[item] || '*'}</span><p className="mt-2 text-xs font-bold">{item}</p></div>)}</div></div></section>
    <section id="services" className="bg-white px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl">{heading('Celebrate your way', 'Our Party Services')}<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map((service, index) => <article key={`${service.name}-${index}`} className="group relative min-h-[220px] overflow-hidden rounded-2xl"><Media src={service.image || gallery[(index + 1) % Math.max(gallery.length, 1)]} alt={service.name} label="Service image" className="transition duration-500 group-hover:scale-105" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#211629ee] to-transparent p-5 pt-16 text-white"><span className="text-2xl text-[#f3c65c]">{icons[service.name] || '*'}</span><h3 className="mt-2 font-display text-xl font-bold">{service.name}</h3><p className="mt-1 text-sm text-white/75">{service.description || 'Professional event planning and unforgettable energy.'}</p>{service.price && <p className="mt-2 text-xs font-bold text-[#f3c65c]">Starting {service.price}{service.duration ? ` Â· ${service.duration}` : ''}</p>}</div></article>)}</div></div></section>
    <section id="events" className="bg-[#f7edf7] px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl">{heading('Curated celebrations', 'Event Packages')}<div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{packages.length ? packages.map((pack, index) => <article key={`${pack.name || pack.title}-${index}`} className="overflow-hidden rounded-2xl border border-[#eadfea] bg-white shadow-sm"><div className="h-36"><Media src={pack.image || gallery[(index + 2) % Math.max(gallery.length, 1)]} alt={pack.name || pack.title || 'Event package'} label="Package image" /></div><div className="p-4"><h3 className="font-display text-xl font-bold">{pack.name || pack.title || 'Event package'}</h3><p className="mt-2 text-xs text-[#75677b]">{pack.eventType || 'Custom celebration'}</p><p className="mt-3 text-sm text-[#75677b]">{pack.description || 'A complete event experience tailored to your occasion.'}</p>{pack.price && <p className="mt-3 font-bold text-[#d58122]">{pack.price}</p>}<a href="#contact" className="mt-4 block rounded-full bg-[#e5ad3d] px-3 py-2 text-center text-xs font-bold">Book Now</a></div></article>) : <div className="col-span-full rounded-2xl border border-dashed border-[#cbb4d0] p-10 text-center text-sm text-[#75677b]">Event packages added by the business owner will appear here.</div>}</div></div></section>
    <section id="facilities" className="px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl">{heading('Built for the perfect event', 'Venue & Infrastructure')}<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{facilities.map((facility, index) => <div key={`${facility.name}-${index}`} className="rounded-xl border border-[#eadfea] bg-white p-5 shadow-sm"><span className="text-2xl text-[#236bd1]">{icons[facility.name] || '*'}</span><h3 className="mt-3 font-bold">{facility.name}</h3><p className="mt-2 text-sm text-[#75677b]">{facility.description || 'Premium event infrastructure for a smooth celebration.'}</p></div>)}</div></div></section>
    <section id="gallery" className="bg-[#211629] px-5 py-20 text-white sm:px-8"><div className="mx-auto max-w-7xl">{heading('The party story', 'Our Gallery')}<div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{gallery.length ? gallery.map((image, index) => <button type="button" key={`${image}-${index}`} onClick={() => setLightbox(image)} className={`overflow-hidden rounded-xl ${index === 0 ? 'col-span-2 row-span-2 aspect-square' : 'aspect-square'}`}><img src={image} alt={`${place.name} event gallery ${index + 1}`} className="h-full w-full object-cover transition duration-500 hover:scale-105" /></button>) : <div className="col-span-full rounded-2xl border border-dashed border-white/30 p-10 text-center text-white/70">Gallery photos uploaded by the business owner will appear here. Maximum 10 photos.</div>}</div><p className="mt-4 text-xs text-white/50">Gallery Photos: {gallery.length} / 10. Maximum 10 gallery photos allowed.</p></div></section>
    {videos.length > 0 && <section id="videos" className="mx-auto max-w-7xl px-5 py-20 sm:px-8">{heading('Feel the energy', 'Our Videos')}<div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{videos.slice(0, 6).map((video, index) => <div key={`${video.url}-${index}`}><PublicVideoCard video={video} /><p className="mt-2 text-sm font-bold">{video.title || 'Event experience'}</p></div>)}</div></section>}
    <section id="reels" className="bg-[#f7edf7] px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl">{heading('Short celebrations', 'Watch Our Reels')}<div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-4">{videos.filter((video) => /instagram|short|reel/i.test(`${video.platform || ''} ${video.url || ''}`)).slice(0, 4).map((video, index) => <a key={`${video.url}-${index}`} href={safeUrl(video.url)} target="_blank" rel="noreferrer" className="relative aspect-[9/16] overflow-hidden rounded-2xl bg-[#211629] p-4 text-white"><span className="absolute inset-0 grid place-items-center text-4xl">PLAY</span><span className="absolute inset-x-4 bottom-4 text-sm font-bold">{video.title || 'Event reel'}<br /><small className="text-[#f3c65c]">View Reel</small></span></a>)}</div></div></section>
    <section id="reviews" className="bg-white px-5 py-20 sm:px-8"><div className="mx-auto max-w-5xl">{heading('From our guests', 'Customer Reviews')}<div className="mt-8 rounded-2xl bg-[#f7edf7] p-5 sm:p-8"><ReviewsSection placeId={place._id} /></div></div></section>
    <section id="contact" className="bg-[#fbf9fd] px-5 py-20 sm:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-[#df267b]">Make it memorable</p><h2 className="mt-2 font-display text-4xl font-bold">Book Your Event</h2><div className="mt-6 space-y-3 text-sm leading-6 text-[#75677b]">{location && <p>{location}</p>}{phone && <p><a href={call} className="font-bold">{phone}</a></p>}{email && <p>{email}</p>}{whatsapp && <p>WhatsApp available</p>}</div><a href={maps} target="_blank" rel="noreferrer" className="mt-6 inline-block rounded-full bg-[#211629] px-5 py-3 text-sm font-bold text-white">Get Directions</a></div><form onSubmit={submit} className="rounded-3xl bg-[#211629] p-6 text-white shadow-xl sm:p-8"><h3 className="font-display text-2xl font-bold text-[#f3c65c]">Book Your Event</h3><div className="mt-5 grid gap-3 sm:grid-cols-2"><input name="name" required placeholder="Name" className="rounded-xl border-0 px-4 py-3 text-sm text-[#211629]" /><input name="phone" required placeholder="Phone number" className="rounded-xl border-0 px-4 py-3 text-sm text-[#211629]" /><input name="email" type="email" placeholder="Email" className="rounded-xl border-0 px-4 py-3 text-sm text-[#211629]" /><input name="eventType" required placeholder="Event type" className="rounded-xl border-0 px-4 py-3 text-sm text-[#211629]" /><input name="date" required type="date" className="rounded-xl border-0 px-4 py-3 text-sm text-[#211629]" /><input name="time" type="time" className="rounded-xl border-0 px-4 py-3 text-sm text-[#211629]" /><input name="guests" type="number" min="1" placeholder="Number of guests" className="rounded-xl border-0 px-4 py-3 text-sm text-[#211629]" /><input name="package" placeholder="Package" className="rounded-xl border-0 px-4 py-3 text-sm text-[#211629]" /><input name="budget" placeholder="Budget" className="rounded-xl border-0 px-4 py-3 text-sm text-[#211629]" /><textarea name="message" placeholder="Special requirements" rows="4" className="sm:col-span-2 rounded-xl border-0 px-4 py-3 text-sm text-[#211629]" /></div>{error && <p className="mt-3 text-sm text-red-300">{error}</p>}<div className="mt-5 flex flex-wrap gap-2"><button disabled={saving} className="rounded-full bg-[#e5ad3d] px-5 py-3 text-sm font-bold text-[#211629]">{saving ? 'Sending...' : sent ? 'Enquiry sent' : 'Check Availability'}</button><a href={whatsapp || '#contact'} target={whatsapp ? '_blank' : undefined} rel="noreferrer" className="rounded-full bg-[#1e9c63] px-5 py-3 text-sm font-bold">WhatsApp</a><a href={call} className="rounded-full border border-white/30 px-5 py-3 text-sm font-bold">Call Now</a></div></form></div></section></main>
    <footer className="bg-[#100d18] px-5 py-12 text-white sm:px-8"><div className="mx-auto grid max-w-7xl gap-10 sm:grid-cols-2 lg:grid-cols-4"><div><h3 className="font-bold text-[#f3c65c]">Our Location</h3><p className="mt-4 text-sm leading-6 text-white/60">{location || 'Address added by the business owner'}</p><a href={maps} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-bold text-[#f3c65c]">Google Maps - Get Directions</a></div><div><h3 className="font-bold text-[#f3c65c]">Contact Details</h3><div className="mt-4 space-y-2 text-sm text-white/60">{phone && <a href={call} className="block">{phone}</a>}{whatsapp && <a href={whatsapp} target="_blank" rel="noreferrer" className="block">WhatsApp</a>}{email && <a href={`mailto:${email}`} className="block">{email}</a>}<p>Open for event enquiries</p></div></div><div><h3 className="font-bold text-[#f3c65c]">Follow Us</h3><p className="mt-4 text-sm text-white/60">Follow Us for Latest Events, Offers & Reels</p><div className="mt-4 flex flex-wrap gap-2">{[['Instagram', social.instagram], ['Facebook', social.facebook], ['YouTube', social.youtube], ['WhatsApp', whatsapp]].map(([name, url]) => <a key={name} href={url ? safeUrl(url) : '#contact'} target={url ? '_blank' : undefined} rel="noreferrer" className="rounded-full border border-white/20 px-3 py-2 text-xs">{name}</a>)}</div></div><div><h3 className="font-bold text-[#f3c65c]">Listed on G-PAGES</h3><p className="mt-4 text-sm text-white/60">This venue is proudly listed on G-PAGES.</p><div className="mt-4 flex flex-wrap gap-2"><a href="/" className="rounded-full bg-[#e5ad3d] px-3 py-2 text-xs font-bold text-[#211629]">Contact G-PAGES</a><a href="/" className="rounded-full border border-white/30 px-3 py-2 text-xs font-bold">Back to Home</a></div></div></div><div className="mx-auto mt-10 max-w-7xl border-t border-white/15 pt-5 text-xs text-white/40">Copyright {new Date().getFullYear()} {place.name}. All rights reserved.</div></footer><Floating phone={phone} whatsapp={whatsapp} social={social} />
    {lightbox && <div className="fixed inset-0 z-50 grid place-items-center bg-black/90 p-4" onClick={() => setLightbox(null)}><img src={lightbox} alt="Event gallery enlarged" className="max-h-[90vh] max-w-[94vw] object-contain" /></div>}
  </div>;
}
