import React, { useState } from 'react';
import ReviewsSection from '../ReviewsSection';
import { getProfileData, ImageFrame } from './PublicProfileShared';
import { getWhatsAppUrl } from '../../utils/healthcare';

const configs = {
  'real-estate': { label: 'Real Estate', eyebrow: 'Spaces designed for better living.', cta: 'View Properties', target: 'projects', projectTitle: 'Featured Properties', aboutTitle: 'About Company', nav: ['Home', 'About', 'Properties', 'Projects', 'Services', 'Gallery', 'Contact'], accent: '#b27b22' },
  construction: { label: 'Construction', eyebrow: 'Building quality that lasts.', cta: 'Request a Quote', target: 'projects', projectTitle: 'Latest Projects', aboutTitle: 'About Construction Company', nav: ['Home', 'About', 'Projects', 'Services', 'Process', 'Gallery', 'Contact'], accent: '#b27b22' },
  roofing: { label: 'Roofing', eyebrow: 'Protection, performance, and precise craftsmanship.', cta: 'Get an Estimate', target: 'services', projectTitle: 'Completed Roofing Work', aboutTitle: 'About Roofing Services', nav: ['Home', 'About', 'Roofing Services', 'Solutions', 'Projects', 'Gallery', 'Contact'], accent: '#9a6c1f' },
  interiors: { label: 'Interiors & Decorations', eyebrow: 'Thoughtful interiors for the way you live and work.', cta: 'Request Consultation', target: 'gallery', projectTitle: 'Interior Portfolio', aboutTitle: 'About Studio', nav: ['Home', 'About', 'Services', 'Portfolio', 'Spaces', 'Gallery', 'Contact'], accent: '#7c5b3c' },
  tiles: { label: 'Tiles Shops', eyebrow: 'Surfaces that define your space.', cta: 'Visit Showroom', target: 'projects', projectTitle: 'Tile Collections', aboutTitle: 'About Showroom', nav: ['Home', 'About', 'Collections', 'Products', 'Brands', 'Gallery', 'Showroom'], accent: '#b27b22' },
  furniture: { label: 'Furniture Shops', eyebrow: 'Furniture with character, comfort, and purpose.', cta: 'View Collection', target: 'projects', projectTitle: 'Furniture Collections', aboutTitle: 'About Store', nav: ['Home', 'About', 'Collections', 'Furniture', 'Services', 'Gallery', 'Showroom'], accent: '#8b5e34' },
};

const list = (value) => Array.isArray(value) ? value.filter(Boolean) : String(value || '').split(/[\n,]/).map((item) => item.trim()).filter(Boolean);
const safeUrl = (value) => value && (/^https?:\/\//i.test(value) ? value : `https://${value}`);
const valueOf = (profile, ...keys) => keys.map((key) => profile[key]).find((value) => value !== undefined && value !== null && value !== '');

export default function PropertyBusinessWebsite({ place, propertyType }) {
  const profile = getProfileData(place); const config = configs[propertyType] || configs.construction; const [menuOpen, setMenuOpen] = useState(false); const [lightbox, setLightbox] = useState(null);
  const gallery = (profile.gallery?.length ? profile.gallery : place.images || []).filter(Boolean).slice(0, 10); const services = list(profile.services || place.services); const facilities = list(profile.infrastructure || place.facilities); const projects = Array.isArray(valueOf(profile, 'projects', 'properties', 'portfolio')) ? valueOf(profile, 'projects', 'properties', 'portfolio') : []; const social = profile.socialMedia || {}; const phone = place.phone || profile.phone; const whatsapp = getWhatsAppUrl(social.whatsapp || profile.whatsapp || phone); const website = safeUrl(place.website || profile.website); const maps = place.coordinates?.lat ? `https://www.google.com/maps/search/?api=1&query=${place.coordinates.lat},${place.coordinates.lng}` : place.address ? `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(place.address)}` : ''; const location = [place.address, place.location?.area?.name, place.location?.city?.name, place.location?.district?.name, place.location?.state?.name, profile.pincode].filter(Boolean).join(', '); const enquiry = valueOf(profile, 'enquiryUrl', 'bookingUrl', 'appointmentUrl') || (phone ? `tel:${phone}` : '#contact'); const call = phone ? `tel:${String(phone).replace(/\s/g, '')}` : ''; const action = 'inline-flex items-center justify-center rounded-md px-5 py-3 text-sm font-bold transition hover:brightness-95'; const href = (item) => `#${item.toLowerCase().replace(/[^a-z]+/g, '-')}`;
  const projectImages = gallery.slice(0, Math.min(projects.length, 6));
  return <div className="min-h-screen bg-[#fbfaf7] text-[#18263b]" style={{ '--property-gold': config.accent, '--property-navy': '#10283f' }}>
    <header className="sticky top-0 z-40 border-b border-slate-200 bg-white/95 shadow-sm backdrop-blur"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-5 py-3 sm:px-8"><a href="#home" className="flex min-w-0 items-center gap-3"><div className="h-12 w-12 shrink-0 overflow-hidden rounded border border-slate-200 bg-white"><ImageFrame src={profile.logo} alt={`${place.name} logo`} /></div><div className="min-w-0"><p className="truncate font-display text-xl font-bold text-[#10283f]">{place.name}</p><p className="truncate text-[11px] text-slate-500">{profile.tagline || config.label}</p></div></a><nav className="hidden items-center gap-6 text-xs font-bold lg:flex">{config.nav.map((item) => <a key={item} href={href(item)} className="hover:text-[#b27b22]">{item}</a>)}</nav><div className="hidden items-center gap-2 md:flex">{whatsapp && <a href={whatsapp} target="_blank" rel="noreferrer" title="Chat on WhatsApp" className="grid h-10 w-10 place-items-center rounded-full bg-emerald-500 text-xl text-white">💬</a>}{enquiry && <a href={enquiry} target={enquiry.startsWith('http') ? '_blank' : undefined} rel="noreferrer" className={`${action} bg-[#b27b22] text-white`}>Enquire Now</a>}</div><button type="button" onClick={() => setMenuOpen((value) => !value)} className="rounded border border-slate-200 px-3 py-2 text-lg lg:hidden" aria-label="Open navigation">☰</button></div>{menuOpen && <nav className="border-t border-slate-200 bg-white px-5 py-2 lg:hidden">{config.nav.map((item) => <a key={item} href={href(item)} onClick={() => setMenuOpen(false)} className="block border-b border-slate-100 py-3 text-sm font-semibold">{item}</a>)}</nav>}</header>

    <main><section id="home" className="relative isolate min-h-[480px] overflow-hidden text-white sm:min-h-[570px]"><div className="absolute inset-0"><ImageFrame src={profile.coverImage || gallery[0]} alt={`${place.name} cover`} eager /><div className="absolute inset-0 bg-gradient-to-r from-[#10283fe8] via-[#10283f99] to-transparent" /></div><div className="relative mx-auto flex min-h-[480px] max-w-[1500px] items-end px-6 py-12 sm:min-h-[570px] sm:px-12 sm:py-16"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.24em] text-[#e7c985]">{config.eyebrow}</p><p className="mt-4 text-sm font-semibold uppercase tracking-[0.15em] text-white/75">{place.subcategory?.name || config.label}</p><h1 className="mt-2 font-display text-5xl font-bold leading-[0.98] sm:text-7xl">{profile.tagline || place.name}</h1>{profile.about && <p className="mt-5 max-w-xl text-base leading-7 text-white/85">{profile.about}</p>}<div className="mt-7 flex flex-wrap gap-3"><a href={`#${config.target}`} className={`${action} text-white`} style={{ backgroundColor: config.accent }}>{config.cta}</a><a href={enquiry} target={enquiry.startsWith('http') ? '_blank' : undefined} rel="noreferrer" className={`${action} border border-white/70 bg-white/10 text-white`}>Contact Us</a></div>{location && <p className="mt-5 text-sm text-white/75">⌖ {location}</p>}</div></div></section>

    {services.length > 0 && <section className="border-b border-slate-200 bg-white"><div className="mx-auto grid max-w-[1400px] grid-cols-2 divide-x divide-slate-200 sm:grid-cols-3 lg:grid-cols-6">{services.slice(0, 6).map((item) => <div key={item} className="px-4 py-6 text-center"><div className="mx-auto mb-2 text-2xl text-[#b27b22]">⌂</div><p className="text-sm font-bold">{item}</p></div>)}</div></section>}

    <section id="about" className="mx-auto grid max-w-7xl gap-8 px-5 py-14 sm:px-8 lg:grid-cols-[1fr_1.1fr] lg:items-center"><div className="h-72 overflow-hidden rounded sm:h-96"><ImageFrame src={gallery[1] || profile.coverImage} alt={`${place.name} portfolio`} /></div><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-[#b27b22]">About Company</p><h2 className="mt-2 font-display text-4xl font-bold text-[#10283f]">{place.name}</h2>{profile.about && <p className="mt-5 whitespace-pre-line text-sm leading-7 text-slate-600">{profile.about}</p>}{facilities.length > 0 && <div className="mt-6 flex flex-wrap gap-2">{facilities.map((item) => <span key={item} className="rounded-full bg-[#f5eee1] px-3 py-2 text-xs font-semibold text-[#75521d]">{item}</span>)}</div>}</div></section>

    {projects.length > 0 && <section id="projects" className="bg-white px-5 py-14 sm:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.25em] text-[#b27b22]">Featured Work</p><h2 className="mt-2 font-display text-4xl font-bold text-[#10283f]">{propertyType === 'real-estate' ? 'Featured Properties' : 'Latest Projects'}</h2><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{projects.map((project, index) => <article key={`${project.name || project.title}-${index}`} className="overflow-hidden rounded border border-slate-200 bg-white shadow-sm"><div className="h-48">{project.image || projectImages[index] ? <img src={project.image || projectImages[index]} alt={project.name || project.title} loading="lazy" className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center bg-[#f5eee1] text-3xl text-[#b27b22]">⌂</div>}</div><div className="p-5"><h3 className="font-bold text-[#10283f]">{project.name || project.title}</h3>{project.location && <p className="mt-1 text-sm text-slate-500">{project.location}</p>}{project.status && <span className="mt-3 inline-block rounded bg-[#f5eee1] px-2 py-1 text-xs font-bold text-[#75521d]">{project.status}</span>}{project.description && <p className="mt-3 text-sm leading-6 text-slate-600">{project.description}</p>}</div></article>)}</div></div></section>}

    {services.length > 0 && <section id="services" className="bg-[#f4f6f7] px-5 py-14 sm:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.25em] text-[#b27b22]">Capabilities</p><h2 className="mt-2 font-display text-4xl font-bold text-[#10283f]">Services</h2><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{services.map((service) => <div key={service} className="rounded border border-slate-200 bg-white p-5 shadow-sm"><div className="text-2xl text-[#b27b22]">✦</div><h3 className="mt-4 font-bold">{service}</h3></div>)}</div></div></section>}

    {gallery.length > 0 && <section id="gallery" className="bg-[#10283f] px-5 py-14 text-white sm:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.25em] text-[#e7c985]">Portfolio</p><h2 className="mt-2 font-display text-4xl font-bold">Gallery</h2><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{gallery.map((image, index) => <button type="button" key={`${image}-${index}`} onClick={() => setLightbox(image)} className="aspect-square overflow-hidden rounded"><img src={image} alt={`${place.name} gallery ${index + 1}`} loading="lazy" className="h-full w-full object-cover transition hover:scale-105" /></button>)}</div></div></section>}

    <section id="reviews" className="bg-white px-5 py-14 sm:px-8"><div className="mx-auto max-w-5xl">{place.rating?.count > 0 && <ReviewsSection placeId={place._id} />}</div></section><section id="contact" className="mx-auto grid max-w-7xl gap-8 px-5 py-14 sm:px-8 lg:grid-cols-[1fr_.8fr]"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-[#b27b22]">Contact</p><h2 className="mt-2 font-display text-4xl font-bold text-[#10283f]">Let&apos;s build something lasting</h2><div className="mt-5 space-y-3 text-sm text-slate-600">{location && <p>⌖ {location}</p>}{phone && <p>☎ {phone}</p>}{place.email && <p>✉ {place.email}</p>}{website && <p>◉ {website}</p>}</div><div className="mt-6 flex flex-wrap gap-2">{phone && <a href={call} className={`${action} bg-[#10283f] text-white`}>Call</a>}{whatsapp && <a href={whatsapp} target="_blank" rel="noreferrer" className={`${action} bg-emerald-500 text-white`}>WhatsApp</a>}{maps && <a href={maps} target="_blank" rel="noreferrer" className={`${action} border border-slate-200 bg-white`}>Directions</a>}</div><div className="mt-6 flex flex-wrap gap-3 text-sm font-semibold text-[#9a6c1f]">{Object.entries(social).filter(([, value]) => value).map(([name, value]) => <a key={name} href={safeUrl(value)} target="_blank" rel="noreferrer">{name}</a>)}</div></div>{place.address && <iframe title={`${place.name} map`} src={`https://www.google.com/maps?q=${encodeURIComponent(place.address)}&output=embed`} className="h-72 w-full rounded border border-slate-200" loading="lazy" referrerPolicy="no-referrer-when-downgrade" />}</section></main>

    <footer className="bg-[#10283f] px-5 py-10 text-white sm:px-8"><div className="mx-auto grid max-w-7xl gap-8 sm:grid-cols-2 lg:grid-cols-4"><div><div className="flex items-center gap-3"><div className="h-11 w-11 overflow-hidden rounded bg-white"><ImageFrame src={profile.logo} alt={`${place.name} logo`} /></div><p className="font-display text-xl font-bold">{place.name}</p></div>{profile.about && <p className="mt-4 text-sm leading-6 text-white/65">{profile.about}</p>}</div><div><h3 className="font-bold">Quick Links</h3><div className="mt-3 space-y-2 text-sm text-white/70">{config.nav.slice(0, 6).map((item) => <a key={item} href={href(item)} className="block hover:text-white">{item}</a>)}</div></div><div><h3 className="font-bold">Contact</h3><div className="mt-3 space-y-2 text-sm text-white/70">{phone && <a href={call} className="block">{phone}</a>}{place.email && <a href={`mailto:${place.email}`} className="block">{place.email}</a>}{location && <p>{location}</p>}</div></div><div><h3 className="font-bold">Social</h3><div className="mt-3 flex flex-wrap gap-2 text-sm text-white/70">{Object.entries(social).filter(([, value]) => value).map(([name, value]) => <a key={name} href={safeUrl(value)} target="_blank" rel="noreferrer" className="rounded-full border border-white/20 px-3 py-2">{name}</a>)}</div></div></div><div className="mx-auto mt-8 max-w-7xl border-t border-white/15 pt-4 text-xs text-white/45">© {new Date().getFullYear()} {place.name}. All rights reserved.</div></footer><div className="fixed inset-x-0 bottom-0 z-40 border-t border-slate-200 bg-white/95 p-2 shadow-xl backdrop-blur lg:hidden"><div className="mx-auto flex max-w-md gap-2">{phone && <a href={call} className="flex-1 rounded bg-[#10283f] px-2 py-2.5 text-center text-xs font-bold text-white">Call</a>}{whatsapp && <a href={whatsapp} target="_blank" rel="noreferrer" className="flex-1 rounded bg-emerald-500 px-2 py-2.5 text-center text-xs font-bold text-white">WhatsApp</a>}<a href={enquiry} className="flex-1 rounded bg-[#b27b22] px-2 py-2.5 text-center text-xs font-bold text-white">Enquire</a></div></div>{lightbox && <div className="fixed inset-0 z-50 grid place-items-center bg-black/90 p-4" onClick={() => setLightbox(null)}><button type="button" onClick={() => setLightbox(null)} className="absolute right-4 top-4 rounded bg-white px-3 py-2 text-sm font-bold text-black">Close</button><img src={lightbox} alt={`${place.name} enlarged gallery`} className="max-h-[90vh] max-w-[94vw] object-contain" onClick={(event) => event.stopPropagation()} /></div>}
  </div>;
}
