import React, { useState } from 'react';
import ReviewsSection from '../ReviewsSection';
import { getProfileData, PublicVideoCard, safeUrl } from './PublicProfileShared';
import { getWhatsAppUrl } from '../../utils/healthcare';
import api from '../../services/api';

const icons = {
  'Luxury Villas': 'âŒ‚', 'Swimming Pool': 'â‰‹', 'Adventure Activities': 'â—ˆ', Campfire: 'â™¨', 'Delicious Food': 'â™¨', 'Peaceful Nature': 'â‹',
  'Peaceful Location': 'âŒ–', 'Family Friendly': 'â™§', 'Multi-Cuisine Food': 'â™¨', 'Free Wi-Fi': 'âŒ', 'Ample Parking': 'â–°',
  Swimming: 'â‰‹', 'Indoor Games': 'â–¦', 'Outdoor Games': 'â—Ž', 'Nature Walk': 'â‹', Boating: 'âŒ', Cycling: 'â—‰', 'Kids Activities': 'â™§',
  Restaurant: 'â™¨', 'Banquet Hall': 'â—‡', 'Garden & Lawn': 'â‹', 'Kids Play Area': 'â™§', 'Power Backup': 'ÏŸ', '24/7 Security': 'âœ“', 'Wi-Fi': 'âŒ', Spa: 'â—‰', Gym: 'â™¢', 'Conference Hall': 'â–¤',
};
const defaultHighlights = ['Luxury Villas', 'Swimming Pool', 'Adventure Activities', 'Campfire', 'Delicious Food', 'Peaceful Nature'];
const defaultFacilities = ['Swimming Pool', 'Restaurant', 'Banquet Hall', 'Garden & Lawn', 'Kids Play Area', 'Ample Parking', 'Power Backup', '24/7 Security'];
const defaultActivities = ['Swimming', 'Campfire', 'Adventure Activities', 'Indoor Games', 'Outdoor Games', 'Nature Walk'];
const list = (value) => Array.isArray(value) ? value.filter(Boolean) : String(value || '').split(/[\n,]/).map((item) => item.trim()).filter(Boolean);
const first = (...values) => values.find((value) => value !== undefined && value !== null && value !== '');
const items = (value, fallback = []) => Array.isArray(value) && value.length ? value.map((item) => typeof item === 'string' ? { name: item } : item) : fallback.map((name) => ({ name }));
const href = (value) => `#${value.toLowerCase().replace(/[^a-z]+/g, '-')}`;

function Media({ src, alt, label, className = '' }) {
  return src ? <img src={src} alt={alt} className={`h-full w-full object-cover ${className}`} /> : <div className={`grid h-full w-full place-items-center bg-[linear-gradient(135deg,#dcebd8,#4d8676)] p-5 text-center text-[#123b39] ${className}`}><div><span className="text-4xl">âœ¦</span><p className="mt-2 text-xs font-bold uppercase tracking-[.16em]">{label}</p><p className="mt-1 text-xs opacity-70">Resort owner media placeholder</p></div></div>;
}

function Actions({ label }) {
  const [liked, setLiked] = useState(false);
  const share = async () => navigator.share ? navigator.share({ title: label, url: window.location.href }) : navigator.clipboard?.writeText(window.location.href);
  return <div className="flex flex-wrap gap-1.5 text-[10px] font-bold text-[#50716c]"><button type="button" onClick={() => setLiked(!liked)} className={`rounded-full border px-2.5 py-1.5 ${liked ? 'border-rose-200 bg-rose-50 text-rose-600' : 'border-[#d7e6dc] bg-white'}`}>â™¥ {liked ? 'Liked' : 'Like'}</button><button type="button" onClick={share} className="rounded-full border border-[#d7e6dc] bg-white px-2.5 py-1.5">â†— Share</button><a href="#contact" className="rounded-full border border-[#d7e6dc] bg-white px-2.5 py-1.5">ðŸ’¬ Comment</a><a href="#contact" className="rounded-full border border-[#d7e6dc] bg-white px-2.5 py-1.5">âš‘ Report</a></div>;
}

function Floating({ phone, whatsapp, social }) {
  const call = phone ? `tel:${String(phone).replace(/\s/g, '')}` : '#contact'; const instagram = safeUrl(social.instagram); const youtube = safeUrl(social.youtube);
  return <div className="fixed right-4 top-1/2 z-40 hidden -translate-y-1/2 flex-col gap-2 md:flex"><a href={whatsapp || '#contact'} target={whatsapp ? '_blank' : undefined} rel="noreferrer" title="WhatsApp" className="grid h-11 w-11 place-items-center rounded-full bg-[#1e9c63] text-white shadow-lg">â—‰</a><a href={call} title="Call Now" className="grid h-11 w-11 place-items-center rounded-full bg-[#1677d2] text-white shadow-lg">â˜Ž</a><a href="#contact" title="Live Chat" className="grid h-11 w-11 place-items-center rounded-full bg-[#e1a63e] text-[#123b39] shadow-lg">âŒ</a>{instagram && <a href={instagram} target="_blank" rel="noreferrer" title="Instagram" className="grid h-11 w-11 place-items-center rounded-full bg-[#d62976] text-xs font-bold text-white shadow-lg">IG</a>}{youtube && <a href={youtube} target="_blank" rel="noreferrer" title="YouTube" className="grid h-11 w-11 place-items-center rounded-full bg-red-600 text-xs font-bold text-white shadow-lg">â–¶</a>}</div>;
}

export default function ResortWebsite({ place }) {
  const profile = getProfileData(place); const specific = place.attributes?.businessProfile?.categorySpecific || {};
  const gallery = (profile.gallery?.length ? profile.gallery : place.images || []).filter(Boolean).slice(0, 10); const social = profile.socialMedia || {};
  const phone = place.phone || profile.phone || ''; const whatsapp = getWhatsAppUrl(social.whatsapp || profile.whatsapp || phone); const call = phone ? `tel:${String(phone).replace(/\s/g, '')}` : '#contact'; const email = place.email || profile.email || '';
  const location = [place.address, place.location?.area?.name, place.location?.city?.name, place.location?.district?.name, place.location?.state?.name, profile.pincode].filter(Boolean).join(', '); const maps = place.coordinates?.lat ? `https://www.google.com/maps/search/?api=1&query=${place.coordinates.lat},${place.coordinates.lng}` : `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(location)}`;
  const stays = items(specific.Rooms || profile.stays || profile.rooms); const activities = items(specific.Activities || profile.activities, defaultActivities); const facilities = items(specific.Facilities || profile.facilities || place.facilities, defaultFacilities); const infrastructure = items(specific.Infrastructure || profile.infrastructure); const highlights = list(specific.Highlights || profile.highlights).length ? list(specific.Highlights || profile.highlights) : defaultHighlights;
  const videos = Array.isArray(profile.videos) ? profile.videos.filter(Boolean).map((item) => typeof item === 'string' ? { url: item, title: 'Resort experience' } : item) : [];
  const tagline = first(profile.tagline, 'Nature | Relaxation | Adventure'); const about = first(profile.about, 'Luxury villas, peaceful surroundings, exciting activities and unforgettable experiences for families and friends.'); const philosophy = first(specific['Resort Philosophy'], profile.mission, 'A peaceful place to slow down, reconnect, and enjoy the outdoors.'); const hero = profile.coverImage || place.coverImage;
  const [menuOpen, setMenuOpen] = useState(false); const [lightbox, setLightbox] = useState(null); const [bookingSent, setBookingSent] = useState(false); const [bookingError, setBookingError] = useState(''); const [saving, setSaving] = useState(false);
  const submitBooking = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); setBookingError(''); setSaving(true); try { await api.post('/enquiries', { place: place._id, name: form.get('name'), phone: form.get('phone'), email: form.get('email'), message: [`Check-in: ${form.get('checkIn')}`, `Check-out: ${form.get('checkOut')}`, `Guests: ${form.get('guests')}`, `Accommodation: ${form.get('accommodation')}`, `Activity preference: ${form.get('activity')}`, `Special request: ${form.get('message')}`].join('\n') }); setBookingSent(true); event.currentTarget.reset(); } catch (error) { setBookingError(error.message || 'Unable to send your booking enquiry.'); } finally { setSaving(false); } };
  const heading = (eyebrow, title) => <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-[#b27728]">{eyebrow}</p><h2 className="mt-2 font-display text-4xl font-bold text-[#173c3a] sm:text-5xl">{title}</h2></div><Actions label={title} /></div>;
  return <div className="min-h-screen bg-[#f8fbf7] font-body text-[#173c3a]" style={{ '--resort-green': '#173c3a', '--resort-gold': '#d19a38' }}>
    <header className="sticky top-0 z-40 border-b border-[#d7e6dc] bg-white/95 shadow-sm backdrop-blur"><div className="mx-auto flex max-w-[1450px] items-center justify-between gap-4 px-5 py-3 sm:px-8"><a href="#home" className="flex min-w-0 items-center gap-3"><div className="h-12 w-12 shrink-0 overflow-hidden rounded-full border border-[#d7e6dc] bg-[#eaf3e8]"><Media src={profile.logo || place.logo} alt={`${place.name} logo`} label="Resort logo" /></div><div className="min-w-0"><p className="truncate font-display text-xl font-bold">{place.name}</p><p className="truncate text-[11px] text-[#67837b]">{tagline}</p></div></a><nav className="hidden items-center gap-5 text-xs font-bold lg:flex">{['Home', 'About', 'Villas & Rooms', 'Activities', 'Facilities', 'Gallery', 'Videos', 'Contact'].map((item) => <a key={item} href={href(item)} className="hover:text-[#b27728]">{item}</a>)}</nav><div className="hidden items-center gap-2 md:flex"><a href={safeUrl(social.instagram) || '#contact'} target={social.instagram ? '_blank' : undefined} rel="noreferrer" className="grid h-8 w-8 place-items-center rounded-full bg-[#d62976] text-xs font-bold text-white">IG</a><a href={safeUrl(social.facebook) || '#contact'} target={social.facebook ? '_blank' : undefined} rel="noreferrer" className="grid h-8 w-8 place-items-center rounded-full bg-[#1877f2] text-xs font-bold text-white">f</a><a href={safeUrl(social.youtube) || '#contact'} target={social.youtube ? '_blank' : undefined} rel="noreferrer" className="grid h-8 w-8 place-items-center rounded-full bg-red-600 text-xs font-bold text-white">â–¶</a><a href="#contact" className="grid h-8 w-8 place-items-center rounded-full border border-[#d7e6dc]">âŒ•</a><a href="#contact" className="rounded-full bg-[#d19a38] px-5 py-2.5 text-xs font-bold text-white">Book Now</a></div><button type="button" onClick={() => setMenuOpen(!menuOpen)} className="rounded-lg border border-[#d7e6dc] px-3 py-2 text-lg lg:hidden" aria-label="Open navigation">â˜°</button></div>{menuOpen && <nav className="border-t border-[#d7e6dc] bg-white px-5 py-2 lg:hidden">{['Home', 'About', 'Villas & Rooms', 'Activities', 'Facilities', 'Gallery', 'Videos', 'Contact'].map((item) => <a key={item} href={href(item)} className="block border-b border-[#edf4ee] py-3 text-sm font-semibold">{item}</a>)}</nav>}</header>
    <main><section id="home" className="relative isolate min-h-[590px] overflow-hidden bg-[#173c3a] text-white sm:min-h-[690px]"><div className="absolute inset-0"><Media src={hero || gallery[0]} alt={`${place.name} resort hero`} label="Hero image" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(10,47,46,.9),rgba(23,60,58,.53),rgba(23,60,58,.08))]" /></div><div className="relative mx-auto flex min-h-[590px] max-w-[1450px] items-center px-6 py-16 sm:min-h-[690px] sm:px-12"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.28em] text-[#f3d28a]">{tagline}</p><h1 className="mt-4 font-display text-5xl font-bold leading-[.98] sm:text-7xl">{first(profile.heroHeading, 'Experience Natureâ€™s Paradise')}</h1><p className="mt-5 max-w-xl text-base leading-7 text-white/80">{about}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#contact" className="rounded-full bg-[#d19a38] px-6 py-3 text-sm font-bold text-white">Book Your Stay</a>{videos[0] && <a href="#videos" className="rounded-full border border-white/50 bg-white/10 px-6 py-3 text-sm font-bold">â–· Watch Video</a>}</div>{location && <p className="mt-6 text-sm text-white/70">âŒ– {location}</p>}</div></div></section>
    <section className="border-b border-[#d7e6dc] bg-white"><div className="mx-auto grid max-w-[1300px] grid-cols-2 gap-px bg-[#d7e6dc] sm:grid-cols-3 lg:grid-cols-6">{highlights.slice(0, 6).map((item) => <div key={item} className="bg-white px-3 py-5 text-center"><span className="text-xl text-[#18796e]">{icons[item] || 'âœ¦'}</span><p className="mt-2 text-xs font-bold">{item}</p></div>)}</div></section>
    <section id="about" className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><div className="h-[350px] overflow-hidden rounded-3xl shadow-xl sm:h-[470px]"><Media src={gallery[0]} alt={`${place.name} resort`} label="About resort image" /></div><div>{heading('Welcome to nature', 'About Our Resort')}<p className="mt-6 whitespace-pre-line text-base leading-8 text-[#56736d]">{about}</p><p className="mt-4 text-sm leading-7 text-[#56736d]">{philosophy}</p><div className="mt-7 grid grid-cols-2 gap-3">{highlights.slice(0, 6).map((item) => <div key={item} className="rounded-xl bg-[#eaf3e8] p-4"><span className="text-xl text-[#18796e]">{icons[item] || 'âœ¦'}</span><p className="mt-2 text-xs font-bold">{item}</p></div>)}</div></div></section>
    <section id="villas-rooms" className="bg-white px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl">{heading('Stay your way', 'Stay Options')}<p className="mt-2 text-sm text-[#67837b]">Choose from peaceful villas, rooms, cottages and family spaces.</p><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{stays.length ? stays.map((stay, index) => <article key={`${stay.name || stay.title}-${index}`} className="overflow-hidden rounded-2xl border border-[#d7e6dc] bg-white shadow-sm"><div className="h-40"><Media src={stay.image || gallery[(index + 1) % Math.max(gallery.length, 1)]} alt={stay.name || stay.title || 'Resort stay'} label="Stay image" /></div><div className="p-4"><h3 className="font-display text-xl font-bold">{stay.name || stay.title || 'Stay option'}</h3><p className="mt-2 text-xs text-[#56736d]">{stay.guests || stay.capacity || 'Guests'} Â· {stay.bed || stay.bedType || 'Comfortable bed'}</p><p className="mt-2 text-xs text-[#56736d]">{stay.view || 'Nature view'} Â· {stay.facilities || 'Resort facilities'}</p>{stay.price && <p className="mt-4 text-lg font-bold text-[#b27728]">{stay.price}<span className="text-xs font-normal"> / Night</span></p>}<a href="#contact" className="mt-4 block rounded-full bg-[#d19a38] px-3 py-2 text-center text-xs font-bold text-white">Book Now</a></div></article>) : <div className="col-span-full rounded-2xl border border-dashed border-[#9fc1ad] p-10 text-center text-sm text-[#67837b]">Stay options added by the resort owner will appear here.</div>}</div></div></section>
    <section id="activities" className="px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl">{heading('Make memories', 'Activities')}<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{activities.map((activity, index) => <article key={`${activity.name}-${index}`} className="group relative min-h-[230px] overflow-hidden rounded-2xl"><Media src={activity.image || gallery[(index + 2) % Math.max(gallery.length, 1)]} alt={activity.name} label="Activity image" className="transition duration-500 group-hover:scale-105" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#0a2f2ecc] to-transparent p-5 pt-16 text-white"><span className="text-2xl">{icons[activity.name] || 'âœ¦'}</span><h3 className="mt-2 font-display text-xl font-bold">{activity.name}</h3><p className="mt-1 text-sm text-white/75">{activity.description || 'A memorable resort experience.'}</p>{activity.duration && <p className="mt-2 text-xs font-bold text-[#f3d28a]">{activity.duration}{activity.price ? ` Â· ${activity.price}` : ''}</p>}</div></article>)}</div></div></section>
    <section id="facilities" className="bg-[#eaf3e8] px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl">{heading('Comfort in nature', 'Facilities & Infrastructure')}<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(infrastructure.length ? infrastructure : facilities).map((item, index) => <div key={`${item.name}-${index}`} className="rounded-xl border border-[#c9dfcf] bg-white p-5"><span className="text-2xl text-[#18796e]">{icons[item.name] || 'âœ¦'}</span><h3 className="mt-3 font-bold">{item.name}</h3><p className="mt-2 text-sm text-[#67837b]">{item.description || 'Thoughtfully designed for a relaxed stay.'}</p></div>)}</div></div></section>
    <section id="gallery" className="bg-[#173c3a] px-5 py-20 text-white sm:px-8"><div className="mx-auto max-w-7xl">{heading('The resort story', 'Our Gallery')}<div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{gallery.length ? gallery.map((image, index) => <button type="button" key={`${image}-${index}`} onClick={() => setLightbox(image)} className={`overflow-hidden rounded-xl ${index === 0 ? 'col-span-2 row-span-2 aspect-square' : 'aspect-square'}`}><img src={image} alt={`${place.name} gallery ${index + 1}`} className="h-full w-full object-cover transition duration-500 hover:scale-105" /></button>) : <div className="col-span-full rounded-2xl border border-dashed border-white/30 p-10 text-center text-white/70">Gallery photos uploaded by the resort owner will appear here. Maximum 10 photos.</div>}</div><p className="mt-4 text-xs text-white/50">Gallery Photos: {gallery.length} / 10 Â· Maximum 10 gallery photos allowed.</p></div></section>
    {videos.length > 0 && <section id="videos" className="mx-auto max-w-7xl px-5 py-20 sm:px-8">{heading('See the experience', 'Our Videos')}<div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{videos.slice(0, 6).map((video, index) => <div key={`${video.url}-${index}`}><PublicVideoCard video={video} /><p className="mt-2 text-sm font-bold">{video.title || 'Resort experience'}</p></div>)}</div></section>}
    <section id="reels" className="bg-[#f5ead4] px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl">{heading('Short escapes', 'Watch Our Reels')}<div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-4">{videos.filter((video) => /instagram|short|reel/i.test(`${video.platform || ''} ${video.url || ''}`)).slice(0, 4).map((video, index) => <a key={`${video.url}-${index}`} href={safeUrl(video.url)} target="_blank" rel="noreferrer" className="relative aspect-[9/16] overflow-hidden rounded-2xl bg-[#173c3a] p-4 text-white"><span className="absolute inset-0 grid place-items-center text-4xl">â–¶</span><span className="absolute inset-x-4 bottom-4 text-sm font-bold">{video.title || 'Resort reel'}<br /><small className="text-[#f3d28a]">View Reel â†—</small></span></a>)}</div></div></section>
    <section id="reviews" className="bg-white px-5 py-20 sm:px-8"><div className="mx-auto max-w-5xl">{heading('From our guests', 'Guest Reviews')}<div className="mt-8 rounded-2xl bg-[#f5ead4] p-5 sm:p-8"><ReviewsSection placeId={place._id} /></div></div></section>
    <section id="contact" className="bg-[#f8fbf7] px-5 py-20 sm:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-[#b27728]">Plan your escape</p><h2 className="mt-2 font-display text-4xl font-bold">Book Your Stay</h2><div className="mt-6 space-y-3 text-sm leading-6 text-[#56736d]">{location && <p>âŒ– {location}</p>}{phone && <p>â˜Ž <a href={call} className="font-bold">{phone}</a></p>}{email && <p>âœ‰ {email}</p>}{whatsapp && <p>â—‰ WhatsApp available</p>}</div><a href={maps} target="_blank" rel="noreferrer" className="mt-6 inline-block rounded-full bg-[#173c3a] px-5 py-3 text-sm font-bold text-white">Get Directions</a></div><form onSubmit={submitBooking} className="rounded-3xl bg-white p-6 shadow-sm sm:p-8"><h3 className="font-display text-2xl font-bold">Check Availability</h3><div className="mt-5 grid gap-3 sm:grid-cols-2"><input name="name" required placeholder="Guest name" className="rounded-xl border-0 px-4 py-3 text-sm ring-1 ring-[#d7e6dc]" /><input name="phone" required placeholder="Phone" className="rounded-xl border-0 px-4 py-3 text-sm ring-1 ring-[#d7e6dc]" /><input name="email" type="email" placeholder="Email" className="rounded-xl border-0 px-4 py-3 text-sm ring-1 ring-[#d7e6dc]" /><input name="accommodation" placeholder="Accommodation type" className="rounded-xl border-0 px-4 py-3 text-sm ring-1 ring-[#d7e6dc]" /><input name="checkIn" type="date" className="rounded-xl border-0 px-4 py-3 text-sm ring-1 ring-[#d7e6dc]" /><input name="checkOut" type="date" className="rounded-xl border-0 px-4 py-3 text-sm ring-1 ring-[#d7e6dc]" /><input name="guests" type="number" min="1" placeholder="Guests" className="rounded-xl border-0 px-4 py-3 text-sm ring-1 ring-[#d7e6dc]" /><input name="activity" placeholder="Activity preference" className="rounded-xl border-0 px-4 py-3 text-sm ring-1 ring-[#d7e6dc]" /><textarea name="message" placeholder="Special request" rows="4" className="sm:col-span-2 rounded-xl border-0 px-4 py-3 text-sm ring-1 ring-[#d7e6dc]" /></div>{bookingError && <p className="mt-3 text-sm text-red-600">{bookingError}</p>}<div className="mt-5 flex flex-wrap gap-2"><button disabled={saving} className="rounded-full bg-[#d19a38] px-5 py-3 text-sm font-bold text-white">{saving ? 'Sendingâ€¦' : bookingSent ? 'Request sent' : 'Check Availability'}</button><a href={whatsapp || '#contact'} target={whatsapp ? '_blank' : undefined} rel="noreferrer" className="rounded-full bg-[#1e9c63] px-5 py-3 text-sm font-bold text-white">WhatsApp</a><a href={call} className="rounded-full border border-[#bdd4c4] px-5 py-3 text-sm font-bold">Call</a></div></form></div></section></main>
    <footer className="bg-[#071f2d] px-5 py-12 text-white sm:px-8"><div className="mx-auto grid max-w-7xl gap-10 sm:grid-cols-2 lg:grid-cols-4"><div><h3 className="font-bold text-[#f3d28a]">Our Location</h3><p className="mt-4 text-sm leading-6 text-white/60">{location || 'Address added by the resort owner'}</p><a href={maps} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-bold text-[#f3d28a]">Google Maps Â· Get Directions</a></div><div><h3 className="font-bold text-[#f3d28a]">Contact Details</h3><div className="mt-4 space-y-2 text-sm text-white/60">{phone && <a href={call} className="block">{phone}</a>}{whatsapp && <a href={whatsapp} target="_blank" rel="noreferrer" className="block">WhatsApp</a>}{email && <a href={`mailto:${email}`} className="block">{email}</a>}<p>Open for stay enquiries</p></div></div><div><h3 className="font-bold text-[#f3d28a]">Follow Us</h3><p className="mt-4 text-sm text-white/60">Follow Us for Latest Updates, Offers & Reels</p><div className="mt-4 flex flex-wrap gap-2">{[['Instagram', social.instagram], ['Facebook', social.facebook], ['YouTube', social.youtube], ['WhatsApp', whatsapp]].map(([name, url]) => <a key={name} href={url ? safeUrl(url) : '#contact'} target={url ? '_blank' : undefined} rel="noreferrer" className="rounded-full border border-white/20 px-3 py-2 text-xs">{name}</a>)}</div></div><div><h3 className="font-bold text-[#f3d28a]">Listed on G-PAGES</h3><p className="mt-4 text-sm text-white/60">This resort is proudly listed on G-PAGES.</p><div className="mt-4 flex flex-wrap gap-2"><a href="/" className="rounded-full bg-[#d19a38] px-3 py-2 text-xs font-bold">Contact G-PAGES</a><a href="/" className="rounded-full border border-white/30 px-3 py-2 text-xs font-bold">Back to Home</a></div></div></div><div className="mx-auto mt-10 max-w-7xl border-t border-white/15 pt-5 text-xs text-white/40">Â© {new Date().getFullYear()} {place.name}. All rights reserved.</div></footer><Floating phone={phone} whatsapp={whatsapp} social={social} />
    {lightbox && <div className="fixed inset-0 z-50 grid place-items-center bg-black/90 p-4" onClick={() => setLightbox(null)}><img src={lightbox} alt="Resort gallery enlarged" className="max-h-[90vh] max-w-[94vw] object-contain" /></div>}
  </div>;
}
