import React, { useState } from 'react';
import ReviewsSection from '../ReviewsSection';
import { getProfileData, ImageFrame, VideoGallery } from './PublicProfileShared';
import { getWhatsAppUrl } from '../../utils/healthcare';

const configs = {
  'marriage-bureau': { label: 'Marriage Bureau', eyebrow: 'Meaningful connections. New beginnings.', nav: ['Home', 'About', 'Services', 'How It Works', 'Gallery', 'Contact'], cta: 'Enquire Now' },
  'function-hall': { label: 'Function Hall', eyebrow: 'A beautiful setting for your celebration.', nav: ['Home', 'About', 'Venue', 'Packages', 'Gallery', 'Contact'], cta: 'Check Availability' },
  'event-organizer': { label: 'Event Organizer', eyebrow: 'Thoughtful planning for unforgettable moments.', nav: ['Home', 'About', 'Services', 'Packages', 'Portfolio', 'Contact'], cta: 'Request a Quote' },
  'catering-service': { label: 'Catering Services', eyebrow: 'Food, hospitality, and celebrations made memorable.', nav: ['Home', 'About', 'Services', 'Menu', 'Gallery', 'Contact'], cta: 'Enquire Now' },
  'flower-decoration': { label: 'Flower Decoration', eyebrow: 'Floral details that transform every celebration.', nav: ['Home', 'About', 'Services', 'Packages', 'Portfolio', 'Contact'], cta: 'Enquire Now' },
  'fashion-designer': { label: 'Fashion Designer', eyebrow: 'Designs made for your most important moments.', nav: ['Home', 'About', 'Collections', 'Services', 'Gallery', 'Contact'], cta: 'Enquire Now' },
  'beauty-parlour': { label: 'Beauty Parlour', eyebrow: 'Feel confident for your special day.', nav: ['Home', 'About', 'Services', 'Packages', 'Gallery', 'Contact'], cta: 'Book Now' },
  'saloon-spa': { label: 'Saloon & Spa', eyebrow: 'Relax, refresh, and get celebration-ready.', nav: ['Home', 'About', 'Services', 'Packages', 'Gallery', 'Contact'], cta: 'Book Now' },
};

const list = (value) => Array.isArray(value) ? value.filter(Boolean) : String(value || '').split(/[\n,]/).map((item) => item.trim()).filter(Boolean);
const safeUrl = (value) => value && (/^https?:\/\//i.test(value) ? value : `https://${value}`);
const profileValue = (profile, ...keys) => keys.map((key) => profile[key]).find((value) => value !== undefined && value !== null && value !== '');

export default function WeddingBusinessWebsite({ place, weddingType }) {
  const profile = getProfileData(place);
  const config = configs[weddingType] || configs['event-organizer'];
  const [menuOpen, setMenuOpen] = useState(false);
  const [lightbox, setLightbox] = useState(null);
  const gallery = (profile.gallery?.length ? profile.gallery : place.images || []).filter(Boolean).slice(0, 10);
  const videos = profile.videos?.length ? profile.videos : (Array.isArray(place.video) ? place.video : place.video ? [place.video] : []);
  const services = list(profile.services || place.services);
  const facilities = list(profile.infrastructure || place.facilities);
  const packages = profileValue(profile, 'packages', 'packageDetails');
  const packageList = Array.isArray(packages) ? packages : [];
  const social = profile.socialMedia || {};
  const phone = place.phone || profile.phone;
  const whatsapp = getWhatsAppUrl(social.whatsapp || profile.whatsapp || phone);
  const website = safeUrl(place.website || profile.website);
  const maps = place.coordinates?.lat ? `https://www.google.com/maps/search/?api=1&query=${place.coordinates.lat},${place.coordinates.lng}` : place.address ? `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(place.address)}` : '';
  const location = [place.address, place.location?.area?.name, place.location?.city?.name, place.location?.district?.name, place.location?.state?.name, profile.pincode].filter(Boolean).join(', ');
  const enquiry = profileValue(profile, 'enquiryUrl', 'bookingUrl', 'appointmentUrl') || (phone ? `tel:${phone}` : '#contact');
  const callUrl = phone ? `tel:${String(phone).replace(/\s/g, '')}` : '';
  const actionClass = 'inline-flex items-center justify-center rounded-md px-5 py-3 text-sm font-bold transition hover:brightness-95';
  const hrefFor = (label) => `#${label.toLowerCase().replace(/[^a-z]+/g, '-')}`;

  return <div className="min-h-screen bg-[#fffafa] text-[#351b25]" style={{ '--wedding-accent': '#941f43', '--wedding-gold': '#c69b52', '--wedding-dark': '#4b1227' }}>
    <header className="sticky top-0 z-40 border-b border-[#ead9df] bg-white/95 shadow-sm backdrop-blur"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-5 py-3 sm:px-8"><a href="#home" className="flex min-w-0 items-center gap-3"><div className="h-12 w-12 shrink-0 overflow-hidden rounded-full border border-[#ead9df] bg-white"><ImageFrame src={profile.logo} alt={`${place.name} logo`} /></div><div className="min-w-0"><p className="truncate font-display text-xl font-bold text-[#4b1227]">{place.name}</p><p className="truncate text-[11px] text-[#8c6b75]">{profile.tagline || config.label}</p></div></a><nav className="hidden items-center gap-6 text-xs font-bold lg:flex">{config.nav.map((item) => <a key={item} href={hrefFor(item)} className="hover:text-[#941f43]">{item}</a>)}</nav><div className="hidden items-center gap-2 md:flex">{whatsapp && <a href={whatsapp} target="_blank" rel="noreferrer" title="Chat on WhatsApp" className="grid h-10 w-10 place-items-center rounded-full bg-emerald-500 text-xl text-white">💬</a>}{enquiry && <a href={enquiry} target={enquiry.startsWith('http') ? '_blank' : undefined} rel="noreferrer" className={`${actionClass} bg-[#941f43] text-white`}>{config.cta}</a>}</div><button type="button" onClick={() => setMenuOpen((value) => !value)} className="rounded border border-[#ead9df] px-3 py-2 text-lg lg:hidden" aria-label="Open navigation">☰</button></div>{menuOpen && <nav className="border-t border-[#ead9df] bg-white px-5 py-2 lg:hidden">{config.nav.map((item) => <a key={item} href={hrefFor(item)} onClick={() => setMenuOpen(false)} className="block border-b border-[#f0e2e7] py-3 text-sm font-semibold">{item}</a>)}</nav>}</header>

    <main><section id="home" className="relative isolate min-h-[480px] overflow-hidden text-white sm:min-h-[570px]"><div className="absolute inset-0"><ImageFrame src={profile.coverImage || gallery[0]} alt={`${place.name} cover`} eager /><div className="absolute inset-0 bg-gradient-to-r from-[#4b1227e8] via-[#4b122799] to-transparent" /></div><div className="relative mx-auto flex min-h-[480px] max-w-[1500px] items-end px-6 py-12 sm:min-h-[570px] sm:px-12 sm:py-16"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.24em] text-[#f4dca9]">{config.eyebrow}</p><p className="mt-4 text-sm font-semibold uppercase tracking-[0.15em] text-white/75">{place.subcategory?.name || config.label}</p><h1 className="mt-2 font-display text-5xl font-bold leading-[0.98] sm:text-7xl">{profile.tagline || place.name}</h1>{profile.about && <p className="mt-5 max-w-xl text-base leading-7 text-white/85">{profile.about}</p>}<div className="mt-7 flex flex-wrap gap-3"><a href="#services" className={`${actionClass} bg-[#941f43] text-white`}>Explore Services</a><a href={enquiry} target={enquiry.startsWith('http') ? '_blank' : undefined} rel="noreferrer" className={`${actionClass} border border-white/70 bg-white/10 text-white`}>{config.cta}</a></div>{location && <p className="mt-5 text-sm text-white/75">⌖ {location}</p>}</div></div></section>

    {services.length > 0 && <section className="border-b border-[#ead9df] bg-white"><div className="mx-auto grid max-w-[1400px] grid-cols-2 divide-x divide-[#ead9df] sm:grid-cols-3 lg:grid-cols-6">{services.slice(0, 6).map((service) => <div key={service} className="px-4 py-6 text-center"><div className="mx-auto mb-2 text-2xl text-[#c69b52]">✿</div><p className="text-sm font-bold">{service}</p></div>)}</div></section>}

    <section id="about" className="mx-auto grid max-w-7xl gap-8 px-5 py-14 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div className="h-72 overflow-hidden rounded-lg sm:h-96"><ImageFrame src={gallery[1] || profile.coverImage} alt={`${place.name} gallery`} /></div><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-[#941f43]">About Us</p><h2 className="mt-2 font-display text-4xl font-bold text-[#4b1227]">{place.name}</h2>{profile.about && <p className="mt-5 whitespace-pre-line text-sm leading-7 text-black/65">{profile.about}</p>}{facilities.length > 0 && <div className="mt-6 flex flex-wrap gap-2">{facilities.map((item) => <span key={item} className="rounded-full bg-[#f7e9ee] px-3 py-2 text-xs font-semibold text-[#701d38]">{item}</span>)}</div>}</div></section>

    {services.length > 0 && <section id="services" className="bg-[#fff3f6] px-5 py-14 sm:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.25em] text-[#941f43]">What We Do</p><h2 className="mt-2 font-display text-4xl font-bold text-[#4b1227]">{config.label} Services</h2><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{services.map((service) => <div key={service} className="rounded-lg border border-[#ead9df] bg-white p-5 shadow-sm"><div className="text-2xl text-[#c69b52]">✿</div><h3 className="mt-4 font-bold">{service}</h3></div>)}</div></div></section>}

    {packageList.length > 0 && <section id="packages" className="mx-auto max-w-7xl px-5 py-14 sm:px-8"><p className="text-xs font-bold uppercase tracking-[0.25em] text-[#941f43]">Curated Options</p><h2 className="mt-2 font-display text-4xl font-bold text-[#4b1227]">Packages</h2><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{packageList.map((item, index) => <article key={`${item.name || item.title}-${index}`} className="rounded-lg border border-[#ead9df] bg-white p-5 shadow-sm"><h3 className="font-bold">{item.name || item.title}</h3>{item.description && <p className="mt-2 text-sm text-black/60">{item.description}</p>}{item.price && <p className="mt-4 font-bold text-[#941f43]">{item.price}</p>}</article>)}</div></section>}

    {gallery.length > 0 && <section id="gallery" className="bg-[#4b1227] px-5 py-14 text-white sm:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.25em] text-[#f4dca9]">Portfolio</p><h2 className="mt-2 font-display text-4xl font-bold">Gallery</h2><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{gallery.map((image, index) => <button type="button" key={`${image}-${index}`} onClick={() => setLightbox(image)} className="aspect-square overflow-hidden rounded-lg"><img src={image} alt={`${place.name} gallery ${index + 1}`} loading="lazy" className="h-full w-full object-cover transition hover:scale-105" /></button>)}</div></div></section>}
    {videos.length > 0 && <VideoGallery videos={videos} title="Wedding videos" />}

    <section id="reviews" className="bg-white px-5 py-14 sm:px-8"><div className="mx-auto max-w-5xl">{place.rating?.count > 0 && <ReviewsSection placeId={place._id} />}</div></section>
    <section id="contact" className="mx-auto grid max-w-7xl gap-8 px-5 py-14 sm:px-8 lg:grid-cols-[1fr_.8fr]"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-[#941f43]">Contact</p><h2 className="mt-2 font-display text-4xl font-bold text-[#4b1227]">Let&apos;s plan something memorable</h2><div className="mt-5 space-y-3 text-sm text-black/65">{location && <p>⌖ {location}</p>}{phone && <p>☎ {phone}</p>}{place.email && <p>✉ {place.email}</p>}{website && <p>◉ {website}</p>}</div><div className="mt-6 flex flex-wrap gap-2">{phone && <a href={callUrl} className={`${actionClass} bg-[#941f43] text-white`}>Call</a>}{whatsapp && <a href={whatsapp} target="_blank" rel="noreferrer" className={`${actionClass} bg-emerald-500 text-white`}>WhatsApp</a>}{maps && <a href={maps} target="_blank" rel="noreferrer" className={`${actionClass} border border-[#ead9df] bg-white`}>Directions</a>}</div><div className="mt-6 flex flex-wrap gap-3 text-sm font-semibold text-[#941f43]">{Object.entries(social).filter(([, value]) => value).map(([name, value]) => <a key={name} href={safeUrl(value)} target="_blank" rel="noreferrer">{name}</a>)}</div></div>{place.address && <iframe title={`${place.name} map`} src={`https://www.google.com/maps?q=${encodeURIComponent(place.address)}&output=embed`} className="h-72 w-full rounded-lg border border-[#ead9df]" loading="lazy" referrerPolicy="no-referrer-when-downgrade" />}</section></main>

    <footer className="bg-[#4b1227] px-5 py-10 text-white sm:px-8"><div className="mx-auto grid max-w-7xl gap-8 sm:grid-cols-2 lg:grid-cols-4"><div><div className="flex items-center gap-3"><div className="h-11 w-11 overflow-hidden rounded-full bg-white"><ImageFrame src={profile.logo} alt={`${place.name} logo`} /></div><p className="font-display text-xl font-bold">{place.name}</p></div>{profile.about && <p className="mt-4 text-sm leading-6 text-white/65">{profile.about}</p>}</div><div><h3 className="font-bold">Quick Links</h3><div className="mt-3 space-y-2 text-sm text-white/70">{config.nav.slice(0, 6).map((item) => <a key={item} href={hrefFor(item)} className="block hover:text-white">{item}</a>)}</div></div><div><h3 className="font-bold">Contact</h3><div className="mt-3 space-y-2 text-sm text-white/70">{phone && <a href={callUrl} className="block">{phone}</a>}{place.email && <a href={`mailto:${place.email}`} className="block">{place.email}</a>}{location && <p>{location}</p>}</div></div><div><h3 className="font-bold">Social</h3><div className="mt-3 flex flex-wrap gap-2 text-sm text-white/70">{Object.entries(social).filter(([, value]) => value).map(([name, value]) => <a key={name} href={safeUrl(value)} target="_blank" rel="noreferrer" className="rounded-full border border-white/20 px-3 py-2">{name}</a>)}</div></div></div><div className="mx-auto mt-8 max-w-7xl border-t border-white/15 pt-4 text-xs text-white/45">© {new Date().getFullYear()} {place.name}. All rights reserved.</div></footer>
    <div className="fixed inset-x-0 bottom-0 z-40 border-t border-[#ead9df] bg-white/95 p-2 shadow-xl backdrop-blur lg:hidden"><div className="mx-auto flex max-w-md gap-2">{phone && <a href={callUrl} className="flex-1 rounded bg-[#941f43] px-2 py-2.5 text-center text-xs font-bold text-white">Call</a>}{whatsapp && <a href={whatsapp} target="_blank" rel="noreferrer" className="flex-1 rounded bg-emerald-500 px-2 py-2.5 text-center text-xs font-bold text-white">WhatsApp</a>}<a href={enquiry} className="flex-1 rounded bg-[#c69b52] px-2 py-2.5 text-center text-xs font-bold text-[#4b1227]">{config.cta}</a></div></div>
    {lightbox && <div className="fixed inset-0 z-50 grid place-items-center bg-black/90 p-4" onClick={() => setLightbox(null)}><button type="button" onClick={() => setLightbox(null)} className="absolute right-4 top-4 rounded bg-white px-3 py-2 text-sm font-bold text-black">Close</button><img src={lightbox} alt={`${place.name} enlarged gallery`} className="max-h-[90vh] max-w-[94vw] object-contain" onClick={(event) => event.stopPropagation()} /></div>}
  </div>;
}
